/**
 * ACLSAlgorithm Generator
 * Auto-generated by create-generator.ts
 * 
 * Generates comprehensive aCLSAlgorithm records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface ACLSAlgorithmData {
  algorithm: string;
  correctIndex: number;
  category: string;
  explanation: string;
  algorithmName: string;
  algorithmStep: number;
  boardYieldFacts: string[];
  clinicalContext: string;
  clinicalPearls: string[];
  commonMistakes: string[];
  correctIntervention: string;
  cprGuidance: string;
  criticalActions: string[];
  drugDose: string;
  drugTiming: string;
  ecgFindings: string[];
  energyDose: string;
  isHighYield: boolean;
  mnemonics: string[];
  panceYield: number;
  patientAge: string;
  relatedAlgorithms: string[];
  rhythm: string;
  rhythmDescription: string;
  testQuestionTips: string[];
  videoUrl: string;
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "algorithm": "value",
  "correctIndex": 0,
  "category": "value",
  "explanation": "value",
  "algorithmName": "value",
  "algorithmStep": 0,
  "boardYieldFacts": ["item1", "item2"],
  "clinicalContext": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "correctIntervention": "value",
  "cprGuidance": "value",
  "criticalActions": ["item1", "item2"],
  "drugDose": "value",
  "drugTiming": "value",
  "ecgFindings": ["item1", "item2"],
  "energyDose": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "panceYield": 0,
  "patientAge": "value",
  "relatedAlgorithms": ["item1", "item2"],
  "rhythm": "value",
  "rhythmDescription": "value",
  "testQuestionTips": ["item1", "item2"],
  "videoUrl": "value"
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateACLSAlgorithm(item: { name: string; category: string }, retryCount = 0): Promise<ACLSAlgorithmData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
  
  let prompt = PROMPT_TEMPLATE
    .replace('{{ITEM_NAME}}', item.name)
    .replace('{{CATEGORY}}', item.category);
  
  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for aCLSAlgorithm: "${item.name}"
    
Return this structure with NO markdown:
{
  "algorithm": "value",
  "correctIndex": 0,
  "category": "value",
  "explanation": "value",
  "algorithmName": "value",
  "algorithmStep": 0,
  "boardYieldFacts": ["item1", "item2"],
  "clinicalContext": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "correctIntervention": "value",
  "cprGuidance": "value",
  "criticalActions": ["item1", "item2"],
  "drugDose": "value",
  "drugTiming": "value",
  "ecgFindings": ["item1", "item2"],
  "energyDose": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "panceYield": 0,
  "patientAge": "value",
  "relatedAlgorithms": ["item1", "item2"],
  "rhythm": "value",
  "rhythmDescription": "value",
  "testQuestionTips": ["item1", "item2"],
  "videoUrl": "value"
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }
  
  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();
    
    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');
    
    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
    
    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');
    
    let parsed: ACLSAlgorithmData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);
      
      // Try fixing string values
      const fixed = jsonStr.replace(
        /"([^"]+)"\s*:\s*"([^"]*)"/g,
        (match, key, value) => {
          if (value.includes('"')) {
            return `"${key}": "${value.replace(/"/g, "'")}"`;
          }
          return match;
        }
      );
      
      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise(resolve => setTimeout(resolve, 1000));
          return generateACLSAlgorithm(item, 1);
        }
        throw parseError;
      }
    }
    
    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return generateACLSAlgorithm(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.aCLSAlgorithm.findMany({
    select: { id: true, algorithm: true, createdAt: true }
  });
  
  const toDelete: string[] = [];
  const seen = new Map<string, typeof all[0]>();
  
  for (const item of all) {
    const key = item.algorithm.toLowerCase().trim();
    const existing = seen.get(key);
    
    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.algorithm}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.algorithm}"`);
      }
    } else {
      seen.set(key, item);
    }
  }
  
  if (toDelete.length > 0) {
    await prisma.aCLSAlgorithm.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 ACLSAlgorithm Generator');
  console.log('='.repeat(60));
  
  await removeDuplicates();
  
  const ITEMS_TO_GENERATE = [
    // Cardiac Arrest Algorithms
    { name: 'Ventricular Fibrillation/Pulseless VT', category: 'Cardiac Arrest' },
    { name: 'Pulseless Electrical Activity (PEA)', category: 'Cardiac Arrest' },
    { name: 'Asystole', category: 'Cardiac Arrest' },
    { name: 'Cardiac Arrest Circular Algorithm', category: 'Cardiac Arrest' },
    { name: 'Post-Cardiac Arrest Care', category: 'Cardiac Arrest' },
    
    // Bradycardia
    { name: 'Symptomatic Bradycardia', category: 'Bradycardia' },
    { name: 'Heart Block Management', category: 'Bradycardia' },
    { name: 'Atropine Protocol', category: 'Bradycardia' },
    { name: 'Transcutaneous Pacing', category: 'Bradycardia' },
    
    // Tachycardia - Narrow Complex
    { name: 'Narrow Complex Tachycardia - Stable', category: 'Tachycardia' },
    { name: 'Narrow Complex Tachycardia - Unstable', category: 'Tachycardia' },
    { name: 'SVT Management', category: 'Tachycardia' },
    { name: 'Atrial Fibrillation with RVR', category: 'Tachycardia' },
    { name: 'Atrial Flutter Management', category: 'Tachycardia' },
    { name: 'Vagal Maneuvers', category: 'Tachycardia' },
    { name: 'Adenosine Administration', category: 'Tachycardia' },
    
    // Tachycardia - Wide Complex
    { name: 'Wide Complex Tachycardia - Stable', category: 'Tachycardia' },
    { name: 'Wide Complex Tachycardia - Unstable', category: 'Tachycardia' },
    { name: 'Monomorphic VT with Pulse', category: 'Tachycardia' },
    { name: 'Polymorphic VT/Torsades de Pointes', category: 'Tachycardia' },
    { name: 'Synchronized Cardioversion', category: 'Tachycardia' },
    
    // Acute Coronary Syndromes
    { name: 'STEMI Management', category: 'Acute Coronary Syndrome' },
    { name: 'NSTEMI/Unstable Angina', category: 'Acute Coronary Syndrome' },
    { name: 'Fibrinolytic Checklist', category: 'Acute Coronary Syndrome' },
    { name: 'PCI vs Fibrinolysis Decision', category: 'Acute Coronary Syndrome' },
    
    // Stroke
    { name: 'Acute Ischemic Stroke', category: 'Stroke' },
    { name: 'Hemorrhagic Stroke', category: 'Stroke' },
    { name: 'tPA Inclusion/Exclusion', category: 'Stroke' },
    { name: 'NIH Stroke Scale', category: 'Stroke' },
    
    // Respiratory Emergencies
    { name: 'Anaphylaxis', category: 'Respiratory' },
    { name: 'Severe Asthma/Status Asthmaticus', category: 'Respiratory' },
    { name: 'Tension Pneumothorax', category: 'Respiratory' },
    { name: 'Pulmonary Embolism', category: 'Respiratory' },
    
    // Pediatric Algorithms
    { name: 'Pediatric Cardiac Arrest', category: 'Pediatric' },
    { name: 'Pediatric Bradycardia', category: 'Pediatric' },
    { name: 'Pediatric Tachycardia', category: 'Pediatric' },
    { name: 'Pediatric Septic Shock', category: 'Pediatric' },
    
    // Special Situations
    { name: 'Hypothermia Cardiac Arrest', category: 'Special Situations' },
    { name: 'Drowning', category: 'Special Situations' },
    { name: 'Electrolyte Emergencies', category: 'Special Situations' },
    { name: 'Toxicologic Emergencies', category: 'Special Situations' },
    { name: 'Pregnancy Cardiac Arrest', category: 'Special Situations' },
    { name: 'Opioid Overdose', category: 'Special Situations' },
    
    // Medications
    { name: 'Epinephrine Dosing', category: 'Medications' },
    { name: 'Amiodarone Protocol', category: 'Medications' },
    { name: 'Lidocaine Protocol', category: 'Medications' },
    { name: 'Vasopressin Use', category: 'Medications' },
    { name: 'Calcium Chloride/Gluconate', category: 'Medications' },
    { name: 'Sodium Bicarbonate Use', category: 'Medications' },
    { name: 'Magnesium Sulfate', category: 'Medications' },
  ];
  
  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} aCLSAlgorithm records...\n`);
  
  const existing = await prisma.aCLSAlgorithm.findMany({ 
    select: { algorithm: true, id: true } 
  });
  const existingNames = new Set(existing.map(e => e.algorithm.toLowerCase()));
  
  let created = 0;
  let skipped = 0;
  let failed = 0;
  
  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }
    
    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateACLSAlgorithm(item);
    
    if (!data) {
      failed++;
      continue;
    }
    
    try {
      await prisma.aCLSAlgorithm.create({
        data: {
          id: crypto.randomUUID(),
          ...data,
          updatedAt: new Date()
        }
      });
      
      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }
    
    await new Promise(resolve => setTimeout(resolve, 800));
  }
  
  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);
  
  const total = await prisma.aCLSAlgorithm.count();
  console.log(`   Total in database: ${total}`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
