/**
 * AntibioticGuideline Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive antibioticGuideline records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface AntibioticGuidelineData {
  organism: string;
  class: string;
  effective: any;
  resistant: any;
  notes: string;
  description: string;
  aliases: string[];
  alternativeAntibiotics: string[];
  arrangement: string;
  boardYieldFacts: string[];
  carbapenemResistant: boolean;
  classicPresentation: string;
  clinicalPearls: string[];
  commonInfections: string[];
  commonMistakes: string[];
  cultureCharacteristics: string;
  deEscalationGuidance: string;
  diagnosticClues: string[];
  doseRecommendations: any;
  emergingResistance: string[];
  esblProducer: boolean;
  firstLineAntibiotics: string[];
  gramStain: string;
  growthConditions: string;
  infectionControl: string[];
  isHighYield: boolean;
  mnemonics: string[];
  morphology: string;
  mrResistance: boolean;
  panceYield: number;
  prophylaxis: string;
  reservoirs: string[];
  resistanceMechanisms: string[];
  testQuestionTips: string[];
  transmission: string[];
  treatmentDuration: string;
  vaccines: string[];
  vancomycinResistant: boolean;
  virulenceFactors: string[];
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "organism": "value",
  "class": "value",
  "effective": "value",
  "resistant": "value",
  "notes": "value",
  "description": "value",
  "aliases": ["item1", "item2"],
  "alternativeAntibiotics": ["item1", "item2"],
  "arrangement": "value",
  "boardYieldFacts": ["item1", "item2"],
  "carbapenemResistant": true,
  "classicPresentation": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonInfections": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "cultureCharacteristics": "value",
  "deEscalationGuidance": "value",
  "diagnosticClues": ["item1", "item2"],
  "doseRecommendations": "value",
  "emergingResistance": ["item1", "item2"],
  "esblProducer": true,
  "firstLineAntibiotics": ["item1", "item2"],
  "gramStain": "value",
  "growthConditions": "value",
  "infectionControl": ["item1", "item2"],
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "morphology": "value",
  "mrResistance": true,
  "panceYield": 0,
  "prophylaxis": "value",
  "reservoirs": ["item1", "item2"],
  "resistanceMechanisms": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "transmission": ["item1", "item2"],
  "treatmentDuration": "value",
  "vaccines": ["item1", "item2"],
  "vancomycinResistant": true,
  "virulenceFactors": ["item1", "item2"]
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateAntibioticGuideline(
  item: { name: string; category: string },
  retryCount = 0
): Promise<AntibioticGuidelineData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for antibioticGuideline: "${item.name}"
    
Return this structure with NO markdown:
{
  "organism": "value",
  "class": "value",
  "effective": "value",
  "resistant": "value",
  "notes": "value",
  "description": "value",
  "aliases": ["item1", "item2"],
  "alternativeAntibiotics": ["item1", "item2"],
  "arrangement": "value",
  "boardYieldFacts": ["item1", "item2"],
  "carbapenemResistant": true,
  "classicPresentation": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonInfections": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "cultureCharacteristics": "value",
  "deEscalationGuidance": "value",
  "diagnosticClues": ["item1", "item2"],
  "doseRecommendations": "value",
  "emergingResistance": ["item1", "item2"],
  "esblProducer": true,
  "firstLineAntibiotics": ["item1", "item2"],
  "gramStain": "value",
  "growthConditions": "value",
  "infectionControl": ["item1", "item2"],
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "morphology": "value",
  "mrResistance": true,
  "panceYield": 0,
  "prophylaxis": "value",
  "reservoirs": ["item1", "item2"],
  "resistanceMechanisms": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "transmission": ["item1", "item2"],
  "treatmentDuration": "value",
  "vaccines": ["item1", "item2"],
  "vancomycinResistant": true,
  "virulenceFactors": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: AntibioticGuidelineData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generateAntibioticGuideline(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generateAntibioticGuideline(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.antibioticGuideline.findMany({
    select: { id: true, organism: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.organism.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.organism}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.organism}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.antibioticGuideline.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 AntibioticGuideline Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Gram-positive cocci
    { name: 'Staphylococcus aureus (MSSA)', category: 'Gram-positive cocci' },
    { name: 'Staphylococcus aureus (MRSA)', category: 'Gram-positive cocci' },
    { name: 'Streptococcus pneumoniae', category: 'Gram-positive cocci' },
    { name: 'Streptococcus pyogenes (Group A Strep)', category: 'Gram-positive cocci' },
    { name: 'Streptococcus agalactiae (Group B Strep)', category: 'Gram-positive cocci' },
    { name: 'Enterococcus faecalis', category: 'Gram-positive cocci' },
    { name: 'Enterococcus faecium (VRE)', category: 'Gram-positive cocci' },
    { name: 'Coagulase-negative Staphylococcus', category: 'Gram-positive cocci' },
    { name: 'Viridans group Streptococci', category: 'Gram-positive cocci' },
    // Gram-positive rods
    { name: 'Clostridium difficile', category: 'Gram-positive rods' },
    { name: 'Clostridium perfringens', category: 'Gram-positive rods' },
    { name: 'Clostridium botulinum', category: 'Gram-positive rods' },
    { name: 'Clostridium tetani', category: 'Gram-positive rods' },
    { name: 'Listeria monocytogenes', category: 'Gram-positive rods' },
    { name: 'Bacillus anthracis', category: 'Gram-positive rods' },
    { name: 'Corynebacterium diphtheriae', category: 'Gram-positive rods' },
    // Gram-negative cocci
    { name: 'Neisseria meningitidis', category: 'Gram-negative cocci' },
    { name: 'Neisseria gonorrhoeae', category: 'Gram-negative cocci' },
    { name: 'Moraxella catarrhalis', category: 'Gram-negative cocci' },
    // Gram-negative rods - Enterobacteriaceae
    { name: 'Escherichia coli', category: 'Enterobacteriaceae' },
    { name: 'Escherichia coli (ESBL)', category: 'Enterobacteriaceae' },
    { name: 'Klebsiella pneumoniae', category: 'Enterobacteriaceae' },
    { name: 'Klebsiella pneumoniae (CRE)', category: 'Enterobacteriaceae' },
    { name: 'Proteus mirabilis', category: 'Enterobacteriaceae' },
    { name: 'Enterobacter cloacae', category: 'Enterobacteriaceae' },
    { name: 'Serratia marcescens', category: 'Enterobacteriaceae' },
    { name: 'Citrobacter freundii', category: 'Enterobacteriaceae' },
    { name: 'Salmonella enterica', category: 'Enterobacteriaceae' },
    { name: 'Salmonella typhi', category: 'Enterobacteriaceae' },
    { name: 'Shigella species', category: 'Enterobacteriaceae' },
    // Other Gram-negative rods
    { name: 'Pseudomonas aeruginosa', category: 'Non-fermenter' },
    { name: 'Acinetobacter baumannii', category: 'Non-fermenter' },
    { name: 'Stenotrophomonas maltophilia', category: 'Non-fermenter' },
    { name: 'Haemophilus influenzae', category: 'Fastidious GNR' },
    { name: 'Legionella pneumophila', category: 'Fastidious GNR' },
    { name: 'Bordetella pertussis', category: 'Fastidious GNR' },
    { name: 'Campylobacter jejuni', category: 'Curved GNR' },
    { name: 'Helicobacter pylori', category: 'Curved GNR' },
    { name: 'Vibrio cholerae', category: 'Curved GNR' },
    { name: 'Vibrio vulnificus', category: 'Curved GNR' },
    // Anaerobes
    { name: 'Bacteroides fragilis', category: 'Anaerobe' },
    { name: 'Prevotella species', category: 'Anaerobe' },
    { name: 'Fusobacterium necrophorum', category: 'Anaerobe' },
    { name: 'Peptostreptococcus species', category: 'Anaerobe' },
    // Atypicals
    { name: 'Mycoplasma pneumoniae', category: 'Atypical' },
    { name: 'Chlamydia pneumoniae', category: 'Atypical' },
    { name: 'Chlamydia trachomatis', category: 'Atypical' },
    // Mycobacteria
    { name: 'Mycobacterium tuberculosis', category: 'Mycobacteria' },
    { name: 'Mycobacterium avium complex (MAC)', category: 'Mycobacteria' },
    // Spirochetes
    { name: 'Treponema pallidum', category: 'Spirochete' },
    { name: 'Borrelia burgdorferi', category: 'Spirochete' },
    { name: 'Leptospira interrogans', category: 'Spirochete' },
    // Rickettsia
    { name: 'Rickettsia rickettsii', category: 'Rickettsia' },
    { name: 'Ehrlichia chaffeensis', category: 'Rickettsia' },
    { name: 'Anaplasma phagocytophilum', category: 'Rickettsia' },
    { name: 'Coxiella burnetii', category: 'Rickettsia' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} antibioticGuideline records...\n`);

  const existing = await prisma.antibioticGuideline.findMany({
    select: { organism: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.organism.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateAntibioticGuideline(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      await prisma.antibioticGuideline.create({
        data: {
          id: uuidv4(),
          ...data,
          updatedAt: new Date(),
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.antibioticGuideline.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
