#!/usr/bin/env tsx
/**
 * Generator Generator - Creates new table generator scripts from templates
 * 
 * Analyzes the Prisma schema and creates complete, working generator scripts
 * based on proven patterns from:
 *   - clinical-guideline-generator.ts (best JSON handling, retry logic)
 *   - imaging-study-doctor.ts (rate limiting, batch processing)
 *   - drug-doctor-enhanced.ts (gap analysis, deduplication)
 *   - condition-link-generator.ts (relationship tables)
 * 
 * Usage: 
 *   npx tsx scripts/generators/create-generator.ts <TableName>
 *   npx tsx scripts/generators/create-generator.ts Procedure
 *   npx tsx scripts/generators/create-generator.ts --list   # Show all tables
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

const args = process.argv.slice(2);
const TABLE_NAME = args.find(a => !a.startsWith('--'));
const LIST_TABLES = args.includes('--list');

if (LIST_TABLES || !TABLE_NAME) {
  const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
  const schemaContent = fs.readFileSync(schemaPath, 'utf-8');
  const models = schemaContent.match(/model\s+(\w+)\s*{/g);
  
  console.log('\n📋 Available tables:\n');
  models?.forEach(m => {
    const name = m.replace('model ', '').replace(' {', '');
    console.log(`   npx tsx scripts/generators/create-generator.ts ${name}`);
  });
  console.log('');
  process.exit(0);
}

// Proven generator template based on successful patterns
const GENERATOR_TEMPLATE = `/**
 * {{TABLE_NAME}} Generator
 * Auto-generated by create-generator.ts
 * 
 * Generates comprehensive {{TABLE_NAME_LOWER}} records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface {{TABLE_NAME}}Data {
{{INTERFACE_FIELDS}}
}

const PROMPT_TEMPLATE = \`You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{{JSON_STRUCTURE}}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:\`;

async function generate{{TABLE_NAME}}(item: { name: string; category: string }, retryCount = 0): Promise<{{TABLE_NAME}}Data | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-pro' });
  
  let prompt = PROMPT_TEMPLATE
    .replace('{{ITEM_NAME}}', item.name)
    .replace('{{CATEGORY}}', item.category);
  
  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = \`Generate valid JSON for {{TABLE_NAME_LOWER}}: "\${item.name}"
    
Return this structure with NO markdown:
{{SIMPLIFIED_JSON_STRUCTURE}}

Rules: Use apostrophes not quotes, spell out symbols, no null values\`;
  }
  
  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();
    
    // Clean up response
    jsonStr = jsonStr
      .replace(/^\`\`\`json\\s*/i, '')
      .replace(/^\`\`\`\\s*/, '')
      .replace(/\`\`\`\\s*$/, '')
      .replace(/^\\uFEFF/, '')
      .replace(/\\r\\n/g, '\\n');
    
    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
    
    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\\s*[}\\]])/g, '$1');
    
    let parsed: {{TABLE_NAME}}Data;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(\`  ⚠️  JSON parse error: \${parseError}\`);
      
      // Try fixing string values
      const fixed = jsonStr.replace(
        /"([^"]+)"\\s*:\\s*"([^"]*)"/g,
        (match, key, value) => {
          if (value.includes('"')) {
            return \`"\${key}": "\${value.replace(/"/g, "'")}"\`;
          }
          return match;
        }
      );
      
      try {
        parsed = JSON.parse(fixed);
        console.log(\`  ℹ️  JSON fixed automatically\`);
      } catch {
        if (retryCount === 0) {
          console.log(\`  🔄 Retrying with simplified prompt...\`);
          await new Promise(resolve => setTimeout(resolve, 1000));
          return generate{{TABLE_NAME}}(item, 1);
        }
        throw parseError;
      }
    }
    
    return parsed;
  } catch (error) {
    console.error(\`  ❌ Error: \${error}\`);
    if (retryCount === 0) {
      console.log(\`  🔄 Retrying...\`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return generate{{TABLE_NAME}}(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\\n🔍 Checking for duplicates...');
  const all = await prisma.{{TABLE_NAME_LOWER}}.findMany({
    select: { id: true, name: true, createdAt: true }
  });
  
  const toDelete: string[] = [];
  const seen = new Map<string, typeof all[0]>();
  
  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);
    
    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(\`  🗑️  Duplicate: "\${item.name}"\`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(\`  🗑️  Duplicate: "\${existing.name}"\`);
      }
    } else {
      seen.set(key, item);
    }
  }
  
  if (toDelete.length > 0) {
    await prisma.{{TABLE_NAME_LOWER}}.deleteMany({ where: { id: { in: toDelete } } });
    console.log(\`  ✅ Removed \${toDelete.length} duplicate(s)\`);
  } else {
    console.log(\`  ✅ No duplicates found\`);
  }
}

async function main() {
  console.log('🏥 {{TABLE_NAME}} Generator');
  console.log('='.repeat(60));
  
  await removeDuplicates();
  
  const ITEMS_TO_GENERATE = [
{{ITEMS_LIST}}
  ];
  
  console.log(\`\\nGenerating \${ITEMS_TO_GENERATE.length} {{TABLE_NAME_LOWER}} records...\\n\`);
  
  const existing = await prisma.{{TABLE_NAME_LOWER}}.findMany({ 
    select: { name: true, id: true } 
  });
  const existingNames = new Set(existing.map(e => e.name.toLowerCase()));
  
  let created = 0;
  let skipped = 0;
  let failed = 0;
  
  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(\`  ⏭️  Skipped: \${item.name}\`);
      skipped++;
      continue;
    }
    
    console.log(\`  🔄 Creating: \${item.name}...\`);
    const data = await generate{{TABLE_NAME}}(item);
    
    if (!data) {
      failed++;
      continue;
    }
    
    try {
      await prisma.{{TABLE_NAME_LOWER}}.create({
        data: {
          id: crypto.randomUUID(),
          ...data,
          updatedAt: new Date()
        }
      });
      
      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(\`  ✅ Created: \${item.name}\`);
    } catch (error) {
      console.error(\`  ❌ Failed to save: \${error}\`);
      failed++;
    }
    
    await new Promise(resolve => setTimeout(resolve, 800));
  }
  
  console.log('\\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(\`   Created: \${created}\`);
  console.log(\`   Skipped: \${skipped}\`);
  console.log(\`   Failed: \${failed}\`);
  
  const total = await prisma.{{TABLE_NAME_LOWER}}.count();
  console.log(\`   Total in database: \${total}\`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
`;

async function analyzeSchema() {
  console.log(`\n🔍 Analyzing schema for table: ${TABLE_NAME}\n`);
  
  // Read the schema file
  const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
  const schemaContent = fs.readFileSync(schemaPath, 'utf-8');
  
  // Find the model definition
  const modelRegex = new RegExp(`model ${TABLE_NAME}\\s*{([^}]+)}`, 's');
  const match = schemaContent.match(modelRegex);
  
  if (!match) {
    console.error(`❌ Table ${TABLE_NAME} not found in schema!`);
    console.log('\n💡 Available tables:');
    const models = schemaContent.match(/model\s+(\w+)\s*{/g);
    models?.forEach(m => console.log(`   - ${m.replace('model ', '').replace(' {', '')}`));
    process.exit(1);
  }
  
  const modelContent = match[1];
  const fields: Array<{ name: string; type: string; isOptional: boolean; isArray: boolean }> = [];
  
  // Parse fields
  const fieldLines = modelContent.split('\n').filter(l => l.trim() && !l.trim().startsWith('@@'));
  
  for (const line of fieldLines) {
    const fieldMatch = line.match(/^\s*(\w+)\s+(\w+)(\[\])?(\\?)?/);
    if (fieldMatch && !['id', 'createdAt', 'updatedAt'].includes(fieldMatch[1])) {
      fields.push({
        name: fieldMatch[1],
        type: fieldMatch[2],
        isOptional: !!fieldMatch[4],
        isArray: !!fieldMatch[3]
      });
    }
  }
  
  return { fields };
}

function generateInterfaceFields(fields: Array<{ name: string; type: string; isOptional: boolean; isArray: boolean }>) {
  return fields.map(f => {
    let tsType = 'string';
    if (f.type === 'Int' || f.type === 'Float') tsType = 'number';
    if (f.type === 'Boolean') tsType = 'boolean';
    if (f.type === 'Json') tsType = 'any';
    if (f.isArray) tsType += '[]';
    
    return `  ${f.name}${f.isOptional ? '?' : ''}: ${tsType};`;
  }).join('\n');
}

function generateJSONStructure(fields: Array<{ name: string; type: string; isOptional: boolean; isArray: boolean }>) {
  const lines: string[] = ['{'];
  
  fields.forEach((f, idx) => {
    const isLast = idx === fields.length - 1;
    let example = '"value"';
    
    if (f.type === 'Int') example = '0';
    if (f.type === 'Boolean') example = 'true';
    if (f.isArray && f.type === 'String') example = '["item1", "item2"]';
    if (f.isArray && f.type === 'Int') example = '[1, 2, 3]';
    
    lines.push(`  "${f.name}": ${example}${isLast ? '' : ','}`);
  });
  
  lines.push('}');
  return lines.join('\n');
}

function generateItemsList(tableName: string) {
  const examples = {
    'Procedure': `    { name: 'Central Line Placement', category: 'Critical Care' },
    { name: 'Lumbar Puncture', category: 'Neurology' },
    { name: 'Thoracentesis', category: 'Pulmonology' },
    { name: 'Paracentesis', category: 'Gastroenterology' },
    { name: 'Joint Aspiration', category: 'Orthopedics' }`,
    'PhysicalExam': `    { name: 'Cardiovascular Exam', category: 'Cardiology' },
    { name: 'Respiratory Exam', category: 'Pulmonology' },
    { name: 'Abdominal Exam', category: 'Gastroenterology' },
    { name: 'Neurological Exam', category: 'Neurology' },
    { name: 'Musculoskeletal Exam', category: 'Orthopedics' }`,
    'DiagnosticTest': `    { name: 'Complete Blood Count', category: 'Laboratory' },
    { name: 'Basic Metabolic Panel', category: 'Laboratory' },
    { name: 'Urinalysis', category: 'Laboratory' },
    { name: 'Electrocardiogram', category: 'Cardiology' },
    { name: 'Chest X-Ray', category: 'Radiology' }`
  };
  
  return examples[tableName] || `    { name: 'Example Item 1', category: 'Category A' },
    { name: 'Example Item 2', category: 'Category B' },
    { name: 'Example Item 3', category: 'Category C' }`;
}

async function generateScript() {
  const { fields } = await analyzeSchema();
  
  console.log(`✅ Found ${fields.length} fields\n`);
  
  const tableLower = TABLE_NAME.charAt(0).toLowerCase() + TABLE_NAME.slice(1);
  
  let script = GENERATOR_TEMPLATE
    .replace(/{{TABLE_NAME}}/g, TABLE_NAME)
    .replace(/{{TABLE_NAME_LOWER}}/g, tableLower)
    .replace('{{INTERFACE_FIELDS}}', generateInterfaceFields(fields))
    .replace('{{JSON_STRUCTURE}}', generateJSONStructure(fields))
    .replace('{{SIMPLIFIED_JSON_STRUCTURE}}', generateJSONStructure(fields))
    .replace('{{ITEMS_LIST}}', generateItemsList(TABLE_NAME));
  
  const outputPath = path.join(process.cwd(), 'scripts', 'generators', `${tableLower}-generator.ts`);
  fs.writeFileSync(outputPath, script);
  
  console.log(`✅ Generated: ${outputPath}\n`);
  console.log('📝 Next steps:');
  console.log(`   1. Edit ${tableLower}-generator.ts to add your items list`);
  console.log(`   2. Customize the prompt template if needed`);
  console.log(`   3. Run: unset GEMINI_API_KEY && DOTENV_CONFIG_PATH=.env node -r dotenv/config node_modules/.bin/tsx ${outputPath}`);
}

generateScript().catch(console.error);
