/**
 * FluidCase Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive fluidCase records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface FluidCaseData {
  title: string;
  scenario: string;
  labs: any;
  correctAnswer: number;
  unit: string;
  marginOfError: number;
  explanation: string;
  calculationHint: string;
  category: string;
  difficulty: string;
}

const PROMPT_TEMPLATE = `You are a medical education expert creating IV fluid calculation problems for PA students.

Generate a fluid calculation case for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create a clinical scenario requiring a NUMERICAL fluid calculation.

CRITICAL REQUIREMENTS:
- correctAnswer MUST be a NUMBER (no units, no text, just the number)
- marginOfError MUST be a NUMBER representing acceptable variance
- labs should be an object with lab values

Return this JSON structure:

{
  "title": "Clear case title",
  "scenario": "Clinical scenario with patient weight, condition, vitals",
  "labs": {"sodium": 140, "potassium": 4.0, "creatinine": 1.0},
  "correctAnswer": 110,
  "unit": "mL/hr",
  "marginOfError": 10,
  "explanation": "Step-by-step calculation explanation",
  "calculationHint": "Formula or method hint",
  "category": "{{CATEGORY}}",
  "difficulty": "medium"
}

CRITICAL JSON RULES:
- correctAnswer MUST BE A NUMBER like 110, not "110" or "110 mL/hr"
- marginOfError MUST BE A NUMBER like 10, not "10"
- Return ONLY valid JSON with NO markdown
- NO special characters: ≥ ≤ × ÷ → ∞
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateFluidCase(
  item: { name: string; category: string },
  retryCount = 0
): Promise<FluidCaseData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for fluidCase: "${item.name}"
    
Return this structure with NO markdown:
{
  "title": "value",
  "scenario": "value",
  "labs": "value",
  "correctAnswer": "value",
  "unit": "value",
  "marginOfError": "value",
  "explanation": "value",
  "calculationHint": "value",
  "category": "value",
  "difficulty": "value"
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: FluidCaseData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generateFluidCase(item, 1);
        }
        throw parseError;
      }
    }

    // Ensure correctAnswer and marginOfError are numbers
    if (typeof parsed.correctAnswer === 'string') {
      const num = parseFloat((parsed.correctAnswer as string).replace(/[^0-9.-]/g, ''));
      parsed.correctAnswer = isNaN(num) ? 100 : num;
    }
    if (typeof parsed.marginOfError === 'string') {
      const num = parseFloat((parsed.marginOfError as string).replace(/[^0-9.-]/g, ''));
      parsed.marginOfError = isNaN(num) ? 10 : num;
    }
    // Ensure labs is an object
    if (typeof parsed.labs === 'string') {
      parsed.labs = { notes: parsed.labs };
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generateFluidCase(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.fluidCase.findMany({
    select: { id: true, title: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.title.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.title}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.title}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.fluidCase.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 FluidCase Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Volume Resuscitation Cases
    { name: 'Hypovolemic Shock Fluid Resuscitation', category: 'Resuscitation' },
    { name: 'Septic Shock Initial Bolus', category: 'Resuscitation' },
    { name: 'Hemorrhagic Shock Blood Products', category: 'Resuscitation' },
    { name: 'Burn Resuscitation (Parkland Formula)', category: 'Resuscitation' },
    { name: 'Trauma Resuscitation Crystalloid vs Colloid', category: 'Resuscitation' },
    { name: 'Pediatric Dehydration Correction', category: 'Resuscitation' },
    // Electrolyte Disorders
    { name: 'Hyponatremia Correction Rate', category: 'Electrolyte' },
    { name: 'Hypernatremia Free Water Deficit', category: 'Electrolyte' },
    { name: 'Hypokalemia Replacement', category: 'Electrolyte' },
    { name: 'Hyperkalemia Emergency Treatment', category: 'Electrolyte' },
    { name: 'Hypocalcemia IV Calcium Replacement', category: 'Electrolyte' },
    { name: 'Hypomagnesemia IV Magnesium', category: 'Electrolyte' },
    { name: 'Hypophosphatemia IV Phosphate', category: 'Electrolyte' },
    // DKA/HHS
    { name: 'DKA Initial Fluid Resuscitation', category: 'Endocrine Emergency' },
    { name: 'DKA Potassium Management', category: 'Endocrine Emergency' },
    { name: 'DKA Insulin Drip Calculation', category: 'Endocrine Emergency' },
    { name: 'HHS Fluid Deficit Estimation', category: 'Endocrine Emergency' },
    // Renal
    { name: 'Acute Kidney Injury Fluid Challenge', category: 'Renal' },
    { name: 'Rhabdomyolysis Aggressive Hydration', category: 'Renal' },
    { name: 'Contrast-Induced Nephropathy Prevention', category: 'Renal' },
    { name: 'Peritoneal Dialysis Fluid Balance', category: 'Renal' },
    // Cardiac
    { name: 'Heart Failure Volume Management', category: 'Cardiac' },
    { name: 'Post-Cardiac Surgery Fluid Balance', category: 'Cardiac' },
    { name: 'Cardiogenic Shock Limited Resuscitation', category: 'Cardiac' },
    // Surgical
    { name: 'Post-Operative Fluid Replacement', category: 'Surgical' },
    { name: 'Third-Space Losses Estimation', category: 'Surgical' },
    { name: 'GI Losses Replacement (NG Suction)', category: 'Surgical' },
    { name: 'Bowel Obstruction Fluid Management', category: 'Surgical' },
    // Maintenance Fluids
    { name: 'Adult Maintenance Fluid Calculation', category: 'Maintenance' },
    { name: 'Pediatric Maintenance Fluids (4-2-1 Rule)', category: 'Maintenance' },
    { name: 'NPO Patient Fluid Orders', category: 'Maintenance' },
    // Special Situations
    { name: 'Adrenal Crisis Fluid Resuscitation', category: 'Endocrine Emergency' },
    { name: 'Liver Cirrhosis Ascites Management', category: 'Hepatic' },
    { name: 'Pancreatitis Aggressive Hydration', category: 'GI' },
    { name: 'Tumor Lysis Syndrome Hydration', category: 'Oncologic' },
    { name: 'Heat Stroke Cooling and Fluids', category: 'Environmental' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} fluidCase records...\n`);

  const existing = await prisma.fluidCase.findMany({
    select: { title: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.title.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateFluidCase(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      await prisma.fluidCase.create({
        data: {
          id: uuidv4(),
          ...data,
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.fluidCase.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
