/**
 * HistoryComponent Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive historyComponent records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface HistoryComponentData {
  name: string;
  displayName: string;
  category: string;
  system: string;
  description: string;
  panceYield: number;
  isHighYield: boolean;
  boardYieldFacts: string[];
  elements: string[];
  expandedElements: any;
  requiredFor: string[];
  frameworkName: string;
  frameworkElements: any;
  rosCategory: string;
  positiveIndicators: string[];
  negativeIndicators: string[];
  redFlagResponses: string[];
  reassuringResponses: string[];
  diagnosticValue: any;
  documentationTips: string;
  chartingExamples: string[];
  clinicalPearls: string[];
  commonMistakes: string[];
  testQuestionTips: string[];
  mnemonics: string[];
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "name": "value",
  "displayName": "value",
  "category": "value",
  "system": "value",
  "description": "value",
  "panceYield": 0,
  "isHighYield": true,
  "boardYieldFacts": ["item1", "item2"],
  "elements": ["item1", "item2"],
  "expandedElements": "value",
  "requiredFor": ["item1", "item2"],
  "frameworkName": "value",
  "frameworkElements": "value",
  "rosCategory": "value",
  "positiveIndicators": ["item1", "item2"],
  "negativeIndicators": ["item1", "item2"],
  "redFlagResponses": ["item1", "item2"],
  "reassuringResponses": ["item1", "item2"],
  "diagnosticValue": "value",
  "documentationTips": "value",
  "chartingExamples": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "mnemonics": ["item1", "item2"]
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateHistoryComponent(
  item: { name: string; category: string },
  retryCount = 0
): Promise<HistoryComponentData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for historyComponent: "${item.name}"
    
Return this structure with NO markdown:
{
  "name": "value",
  "displayName": "value",
  "category": "value",
  "system": "value",
  "description": "value",
  "panceYield": 0,
  "isHighYield": true,
  "boardYieldFacts": ["item1", "item2"],
  "elements": ["item1", "item2"],
  "expandedElements": "value",
  "requiredFor": ["item1", "item2"],
  "frameworkName": "value",
  "frameworkElements": "value",
  "rosCategory": "value",
  "positiveIndicators": ["item1", "item2"],
  "negativeIndicators": ["item1", "item2"],
  "redFlagResponses": ["item1", "item2"],
  "reassuringResponses": ["item1", "item2"],
  "diagnosticValue": "value",
  "documentationTips": "value",
  "chartingExamples": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "mnemonics": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: HistoryComponentData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generateHistoryComponent(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generateHistoryComponent(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.historyComponent.findMany({
    select: { id: true, name: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.name}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.name}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.historyComponent.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 HistoryComponent Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Chief Complaint Categories
    { name: 'Chest Pain History', category: 'Chief Complaint' },
    { name: 'Abdominal Pain History', category: 'Chief Complaint' },
    { name: 'Headache History', category: 'Chief Complaint' },
    { name: 'Shortness of Breath History', category: 'Chief Complaint' },
    { name: 'Back Pain History', category: 'Chief Complaint' },
    { name: 'Dizziness History', category: 'Chief Complaint' },
    { name: 'Syncope History', category: 'Chief Complaint' },
    { name: 'Fever History', category: 'Chief Complaint' },
    { name: 'Cough History', category: 'Chief Complaint' },
    { name: 'Fatigue History', category: 'Chief Complaint' },
    // Past Medical History Components
    { name: 'Cardiac History (PMH)', category: 'Past Medical History' },
    { name: 'Pulmonary History (PMH)', category: 'Past Medical History' },
    { name: 'Diabetes History (PMH)', category: 'Past Medical History' },
    { name: 'Cancer History (PMH)', category: 'Past Medical History' },
    { name: 'Surgical History', category: 'Past Medical History' },
    { name: 'Psychiatric History (PMH)', category: 'Past Medical History' },
    { name: 'Obstetric History (Gyn)', category: 'Past Medical History' },
    // Family History Components
    { name: 'Cardiac Family History', category: 'Family History' },
    { name: 'Cancer Family History', category: 'Family History' },
    { name: 'Diabetes Family History', category: 'Family History' },
    { name: 'Autoimmune Family History', category: 'Family History' },
    { name: 'Psychiatric Family History', category: 'Family History' },
    // Social History Components
    { name: 'Tobacco Use History', category: 'Social History' },
    { name: 'Alcohol Use History', category: 'Social History' },
    { name: 'Illicit Drug Use History', category: 'Social History' },
    { name: 'Sexual History', category: 'Social History' },
    { name: 'Occupational History', category: 'Social History' },
    { name: 'Travel History', category: 'Social History' },
    { name: 'Diet and Exercise History', category: 'Social History' },
    // Review of Systems Templates
    { name: 'Constitutional ROS', category: 'Review of Systems' },
    { name: 'Cardiovascular ROS', category: 'Review of Systems' },
    { name: 'Respiratory ROS', category: 'Review of Systems' },
    { name: 'Gastrointestinal ROS', category: 'Review of Systems' },
    { name: 'Genitourinary ROS', category: 'Review of Systems' },
    { name: 'Musculoskeletal ROS', category: 'Review of Systems' },
    { name: 'Neurological ROS', category: 'Review of Systems' },
    { name: 'Psychiatric ROS', category: 'Review of Systems' },
    { name: 'Integumentary ROS', category: 'Review of Systems' },
    { name: 'HEENT ROS', category: 'Review of Systems' },
    // Medication History
    { name: 'Current Medications Review', category: 'Medications' },
    { name: 'Allergy History', category: 'Medications' },
    { name: 'Anticoagulation History', category: 'Medications' },
    { name: 'Immunosuppressant History', category: 'Medications' },
    // Specific Symptom Histories
    { name: 'OPQRST Pain Assessment', category: 'Symptom Characterization' },
    { name: 'OLDCARTS Symptom History', category: 'Symptom Characterization' },
    { name: 'SAMPLE History (Emergency)', category: 'Symptom Characterization' },
    { name: 'Nausea and Vomiting History', category: 'Chief Complaint' },
    { name: 'Weight Change History', category: 'Chief Complaint' },
    { name: 'Palpitations History', category: 'Chief Complaint' },
    { name: 'Joint Pain History', category: 'Chief Complaint' },
    { name: 'Rash History', category: 'Chief Complaint' },
    { name: 'Visual Changes History', category: 'Chief Complaint' },
    { name: 'Weakness History', category: 'Chief Complaint' },

    // === ADDITIONAL COMPREHENSIVE PANCE HISTORY COMPONENTS ===

    // Additional Chief Complaints
    { name: 'Seizure History', category: 'Chief Complaint' },
    { name: 'Altered Mental Status History', category: 'Chief Complaint' },
    { name: 'Leg Swelling History', category: 'Chief Complaint' },
    { name: 'Urinary Symptoms History', category: 'Chief Complaint' },
    { name: 'Vaginal Bleeding History', category: 'Chief Complaint' },
    { name: 'Vaginal Discharge History', category: 'Chief Complaint' },
    { name: 'Rectal Bleeding History', category: 'Chief Complaint' },
    { name: 'Hemoptysis History', category: 'Chief Complaint' },
    { name: 'Hematuria History', category: 'Chief Complaint' },
    { name: 'Epistaxis History', category: 'Chief Complaint' },
    { name: 'Sore Throat History', category: 'Chief Complaint' },
    { name: 'Ear Pain History', category: 'Chief Complaint' },
    { name: 'Eye Pain History', category: 'Chief Complaint' },
    { name: 'Neck Pain History', category: 'Chief Complaint' },
    { name: 'Shoulder Pain History', category: 'Chief Complaint' },
    { name: 'Hip Pain History', category: 'Chief Complaint' },
    { name: 'Knee Pain History', category: 'Chief Complaint' },
    { name: 'Ankle Pain History', category: 'Chief Complaint' },
    { name: 'Hand Pain History', category: 'Chief Complaint' },
    { name: 'Foot Pain History', category: 'Chief Complaint' },
    { name: 'Numbness/Tingling History', category: 'Chief Complaint' },
    { name: 'Tremor History', category: 'Chief Complaint' },
    { name: 'Memory Loss History', category: 'Chief Complaint' },
    { name: 'Insomnia History', category: 'Chief Complaint' },
    { name: 'Anxiety History', category: 'Chief Complaint' },
    { name: 'Depression History', category: 'Chief Complaint' },
    { name: 'Suicidal Ideation Assessment', category: 'Chief Complaint' },
    { name: 'Substance Use History', category: 'Chief Complaint' },
    { name: 'Jaundice History', category: 'Chief Complaint' },
    { name: 'Itching/Pruritus History', category: 'Chief Complaint' },
    { name: 'Lymph Node Swelling History', category: 'Chief Complaint' },
    { name: 'Bruising/Bleeding History', category: 'Chief Complaint' },

    // Past Medical History - Additional
    { name: 'Hypertension History (PMH)', category: 'Past Medical History' },
    { name: 'Heart Failure History (PMH)', category: 'Past Medical History' },
    { name: 'Stroke/TIA History (PMH)', category: 'Past Medical History' },
    { name: 'Asthma/COPD History (PMH)', category: 'Past Medical History' },
    { name: 'Kidney Disease History (PMH)', category: 'Past Medical History' },
    { name: 'Liver Disease History (PMH)', category: 'Past Medical History' },
    { name: 'Thyroid History (PMH)', category: 'Past Medical History' },
    { name: 'Autoimmune History (PMH)', category: 'Past Medical History' },
    { name: 'Bleeding Disorder History (PMH)', category: 'Past Medical History' },
    { name: 'Clotting Disorder History (PMH)', category: 'Past Medical History' },
    { name: 'HIV/Immunocompromised History', category: 'Past Medical History' },
    { name: 'Transplant History (PMH)', category: 'Past Medical History' },
    { name: 'Hospitalization History', category: 'Past Medical History' },

    // Family History - Additional
    { name: 'Stroke Family History', category: 'Family History' },
    { name: 'Blood Clot Family History', category: 'Family History' },
    { name: 'Kidney Disease Family History', category: 'Family History' },
    { name: 'Sudden Death Family History', category: 'Family History' },
    { name: 'Aneurysm Family History', category: 'Family History' },
    { name: 'Genetic Condition Family History', category: 'Family History' },

    // Social History - Additional
    { name: 'Vaping/E-Cigarette History', category: 'Social History' },
    { name: 'Marijuana Use History', category: 'Social History' },
    { name: 'IV Drug Use History', category: 'Social History' },
    { name: 'Domestic Violence Screening', category: 'Social History' },
    { name: 'Housing/Homelessness History', category: 'Social History' },
    { name: 'Food Security Assessment', category: 'Social History' },
    { name: 'Exercise Tolerance History', category: 'Social History' },
    { name: 'Sleep History', category: 'Social History' },
    { name: 'Caffeine Intake History', category: 'Social History' },
    { name: 'Stress/Psychosocial History', category: 'Social History' },
    { name: 'Firearms in Home Assessment', category: 'Social History' },
    { name: 'Pet/Animal Exposure History', category: 'Social History' },

    // Review of Systems - Additional
    { name: 'Endocrine ROS', category: 'Review of Systems' },
    { name: 'Hematologic ROS', category: 'Review of Systems' },
    { name: 'Allergic/Immunologic ROS', category: 'Review of Systems' },

    // Medication History - Additional
    { name: 'Herbal/Supplement History', category: 'Medications' },
    { name: 'Over-the-Counter Medication Use', category: 'Medications' },
    { name: 'Antibiotic History', category: 'Medications' },
    { name: 'Steroid Use History', category: 'Medications' },
    { name: 'Opioid Use History', category: 'Medications' },
    { name: 'Insulin/Diabetes Med History', category: 'Medications' },
    { name: 'Chemotherapy History', category: 'Medications' },
    { name: 'Biologic Therapy History', category: 'Medications' },

    // Symptom Frameworks
    { name: 'SOCRATES Pain Assessment', category: 'Symptom Characterization' },
    { name: 'PQRST Chest Pain', category: 'Symptom Characterization' },
    { name: 'SNOOP for Headache Red Flags', category: 'Symptom Characterization' },
    { name: 'TUNA FISH Syncope', category: 'Symptom Characterization' },
    { name: 'SIGECAPS Depression', category: 'Symptom Characterization' },
    { name: 'DIG FAST Mania', category: 'Symptom Characterization' },
    { name: 'SAD PERSONS Suicide Risk', category: 'Symptom Characterization' },

    // Specific System Histories
    { name: 'Claudication History', category: 'Cardiovascular' },
    { name: 'Orthopnea/PND History', category: 'Cardiovascular' },
    { name: 'Exercise Tolerance (Cardiac)', category: 'Cardiovascular' },
    { name: 'GERD/Reflux History', category: 'Gastrointestinal' },
    { name: 'Bowel Habit Changes', category: 'Gastrointestinal' },
    { name: 'Dysphagia History', category: 'Gastrointestinal' },
    { name: 'Menstrual History', category: 'Reproductive' },
    { name: 'Pregnancy History (G/P)', category: 'Reproductive' },
    { name: 'Contraception History', category: 'Reproductive' },
    { name: 'Erectile Dysfunction History', category: 'Reproductive' },
    { name: 'STI History', category: 'Reproductive' },
    { name: 'Falls Risk Assessment', category: 'Geriatric' },
    { name: 'Functional Status Assessment', category: 'Geriatric' },
    { name: 'ADL/IADL Assessment', category: 'Geriatric' },
    { name: 'Immunization History', category: 'Preventive' },
    { name: 'Cancer Screening History', category: 'Preventive' },
    { name: 'Trauma History', category: 'Emergency' },
    { name: 'Mechanism of Injury', category: 'Emergency' },
    { name: 'Tetanus Status', category: 'Emergency' },
    { name: 'Last Oral Intake (NPO)', category: 'Emergency' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} historyComponent records...\n`);

  const existing = await prisma.historyComponent.findMany({
    select: { name: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.name.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateHistoryComponent(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      await prisma.historyComponent.create({
        data: {
          id: uuidv4(),
          ...data,
        } as any,
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.historyComponent.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
