/**
 * LabCase Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive labCase records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface LabCaseData {
  correctDiagnosis: string;
  clinicalVignette: string;
  labs: any;
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "correctDiagnosis": "value",
  "clinicalVignette": "value",
  "labs": "value"
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateLabCase(
  item: { name: string; category: string },
  retryCount = 0
): Promise<LabCaseData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for labCase: "${item.name}"
    
Return this structure with NO markdown:
{
  "correctDiagnosis": "value",
  "clinicalVignette": "value",
  "labs": "value"
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: LabCaseData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generateLabCase(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generateLabCase(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.labCase.findMany({
    select: { id: true, correctDiagnosis: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.correctDiagnosis.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.correctDiagnosis}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.correctDiagnosis}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.labCase.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 LabCase Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Hematology Cases
    { name: 'Iron Deficiency Anemia', category: 'Hematology' },
    { name: 'Vitamin B12 Deficiency', category: 'Hematology' },
    { name: 'Folate Deficiency Anemia', category: 'Hematology' },
    { name: 'Anemia of Chronic Disease', category: 'Hematology' },
    { name: 'Hemolytic Anemia', category: 'Hematology' },
    { name: 'Sickle Cell Crisis', category: 'Hematology' },
    { name: 'Thalassemia', category: 'Hematology' },
    { name: 'Polycythemia Vera', category: 'Hematology' },
    { name: 'Thrombocytopenia', category: 'Hematology' },
    { name: 'DIC (Disseminated Intravascular Coagulation)', category: 'Hematology' },

    // Electrolyte Cases
    { name: 'Hyponatremia', category: 'Electrolytes' },
    { name: 'Hypernatremia', category: 'Electrolytes' },
    { name: 'Hypokalemia', category: 'Electrolytes' },
    { name: 'Hyperkalemia', category: 'Electrolytes' },
    { name: 'Hypocalcemia', category: 'Electrolytes' },
    { name: 'Hypercalcemia', category: 'Electrolytes' },
    { name: 'Hypomagnesemia', category: 'Electrolytes' },
    { name: 'Hypophosphatemia', category: 'Electrolytes' },

    // Acid-Base Cases
    { name: 'Metabolic Acidosis with High Anion Gap', category: 'Acid-Base' },
    { name: 'Metabolic Acidosis with Normal Anion Gap', category: 'Acid-Base' },
    { name: 'Metabolic Alkalosis', category: 'Acid-Base' },
    { name: 'Respiratory Acidosis', category: 'Acid-Base' },
    { name: 'Respiratory Alkalosis', category: 'Acid-Base' },
    { name: 'Mixed Acid-Base Disorder', category: 'Acid-Base' },
    { name: 'Diabetic Ketoacidosis', category: 'Acid-Base' },
    { name: 'Lactic Acidosis', category: 'Acid-Base' },

    // Renal Cases
    { name: 'Acute Kidney Injury - Prerenal', category: 'Renal' },
    { name: 'Acute Kidney Injury - Intrinsic', category: 'Renal' },
    { name: 'Acute Kidney Injury - Postrenal', category: 'Renal' },
    { name: 'Chronic Kidney Disease', category: 'Renal' },
    { name: 'Nephrotic Syndrome', category: 'Renal' },
    { name: 'Nephritic Syndrome', category: 'Renal' },
    { name: 'Rhabdomyolysis', category: 'Renal' },

    // Hepatic Cases
    { name: 'Acute Hepatitis', category: 'Hepatic' },
    { name: 'Chronic Hepatitis', category: 'Hepatic' },
    { name: 'Cirrhosis', category: 'Hepatic' },
    { name: 'Alcoholic Liver Disease', category: 'Hepatic' },
    { name: 'Drug-Induced Liver Injury', category: 'Hepatic' },
    { name: 'Hemochromatosis', category: 'Hepatic' },
    { name: 'Wilson Disease', category: 'Hepatic' },

    // Endocrine Cases
    { name: 'Hypothyroidism', category: 'Endocrine' },
    { name: 'Hyperthyroidism', category: 'Endocrine' },
    { name: 'Type 1 Diabetes', category: 'Endocrine' },
    { name: 'Type 2 Diabetes', category: 'Endocrine' },
    { name: 'Hyperosmolar Hyperglycemic State', category: 'Endocrine' },
    { name: 'Adrenal Insufficiency', category: 'Endocrine' },
    { name: 'Cushing Syndrome', category: 'Endocrine' },
    { name: 'Pheochromocytoma', category: 'Endocrine' },
    { name: 'Primary Hyperaldosteronism', category: 'Endocrine' },

    // Cardiac Cases
    { name: 'Acute MI (Troponin Elevation)', category: 'Cardiac' },
    { name: 'Heart Failure (BNP Elevation)', category: 'Cardiac' },
    { name: 'Pericarditis', category: 'Cardiac' },

    // Infectious Cases
    { name: 'Sepsis', category: 'Infectious' },
    { name: 'Bacterial Meningitis', category: 'Infectious' },
    { name: 'Urinary Tract Infection', category: 'Infectious' },
    { name: 'Community-Acquired Pneumonia', category: 'Infectious' },
    { name: 'Infectious Mononucleosis', category: 'Infectious' },

    // Rheumatologic Cases
    { name: 'Systemic Lupus Erythematosus', category: 'Rheumatology' },
    { name: 'Rheumatoid Arthritis', category: 'Rheumatology' },
    { name: 'Gout', category: 'Rheumatology' },

    // Oncology Cases
    { name: 'Multiple Myeloma', category: 'Oncology' },
    { name: 'Leukemia', category: 'Oncology' },
    { name: 'Tumor Lysis Syndrome', category: 'Oncology' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} labCase records...\n`);

  const existing = await prisma.labCase.findMany({
    select: { correctDiagnosis: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.correctDiagnosis.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateLabCase(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      await prisma.labCase.create({
        data: {
          id: uuidv4(),
          ...data,
        } as any,
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.labCase.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
