/**
 * LabTest Generator
 * Auto-generated by create-generator.ts
 * 
 * Generates comprehensive labTest records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface LabTestData {
  name: string;
  category: string;
  commonAbnormalities: string[];
  typicalUse: string;
  boardYieldFacts: string[];
  clinicalPearls: string[];
  clinicalScenarios: any;
  collectionTube: string;
  commonMistakes: string[];
  conventionalRange: string;
  conversionFactor: number;
  criticalValues: any;
  decreaseIndicates: string[];
  falsePosNeg: string;
  fastingRequired: boolean;
  followUpTests: string[];
  increaseIndicates: string[];
  interferingFactors: string[];
  interpretationSteps: string;
  isHighYield: boolean;
  mnemonics: string[];
  panceYield: number;
  referenceRanges: any;
  relatedTests: string[];
  sampleType: string;
  siRange: string;
  siUnits: string;
  specialInstructions: string;
  stability: string;
  testQuestionTips: string[];
  turnaroundTime: string;
  units: string;
  whenToOrder: string[];
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "name": "value",
  "category": "value",
  "commonAbnormalities": ["item1", "item2"],
  "typicalUse": "value",
  "boardYieldFacts": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "clinicalScenarios": "value",
  "collectionTube": "value",
  "commonMistakes": ["item1", "item2"],
  "conventionalRange": "value",
  "conversionFactor": "value",
  "criticalValues": "value",
  "decreaseIndicates": ["item1", "item2"],
  "falsePosNeg": "value",
  "fastingRequired": true,
  "followUpTests": ["item1", "item2"],
  "increaseIndicates": ["item1", "item2"],
  "interferingFactors": ["item1", "item2"],
  "interpretationSteps": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "panceYield": 0,
  "referenceRanges": "value",
  "relatedTests": ["item1", "item2"],
  "sampleType": "value",
  "siRange": "value",
  "siUnits": "value",
  "specialInstructions": "value",
  "stability": "value",
  "testQuestionTips": ["item1", "item2"],
  "turnaroundTime": "value",
  "units": "value",
  "whenToOrder": ["item1", "item2"],
  "LabConditionLink": "value"
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateLabTest(item: { name: string; category: string }, retryCount = 0): Promise<LabTestData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
  
  let prompt = PROMPT_TEMPLATE
    .replace('{{ITEM_NAME}}', item.name)
    .replace('{{CATEGORY}}', item.category);
  
  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for labTest: "${item.name}"
    
Return this structure with NO markdown:
{
  "name": "value",
  "category": "value",
  "commonAbnormalities": ["item1", "item2"],
  "typicalUse": "value",
  "boardYieldFacts": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "clinicalScenarios": "value",
  "collectionTube": "value",
  "commonMistakes": ["item1", "item2"],
  "conventionalRange": "value",
  "conversionFactor": "value",
  "criticalValues": "value",
  "decreaseIndicates": ["item1", "item2"],
  "falsePosNeg": "value",
  "fastingRequired": true,
  "followUpTests": ["item1", "item2"],
  "increaseIndicates": ["item1", "item2"],
  "interferingFactors": ["item1", "item2"],
  "interpretationSteps": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "panceYield": 0,
  "referenceRanges": "value",
  "relatedTests": ["item1", "item2"],
  "sampleType": "value",
  "siRange": "value",
  "siUnits": "value",
  "specialInstructions": "value",
  "stability": "value",
  "testQuestionTips": ["item1", "item2"],
  "turnaroundTime": "value",
  "units": "value",
  "whenToOrder": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }
  
  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();
    
    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');
    
    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
    
    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');
    
    let parsed: LabTestData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);
      
      // Try fixing string values
      const fixed = jsonStr.replace(
        /"([^"]+)"\s*:\s*"([^"]*)"/g,
        (match, key, value) => {
          if (value.includes('"')) {
            return `"${key}": "${value.replace(/"/g, "'")}"`;
          }
          return match;
        }
      );
      
      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise(resolve => setTimeout(resolve, 1000));
          return generateLabTest(item, 1);
        }
        throw parseError;
      }
    }
    
    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return generateLabTest(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.labTest.findMany({
    select: { id: true, name: true, createdAt: true }
  });
  
  const toDelete: string[] = [];
  const seen = new Map<string, typeof all[0]>();
  
  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);
    
    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.name}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.name}"`);
      }
    } else {
      seen.set(key, item);
    }
  }
  
  if (toDelete.length > 0) {
    await prisma.labTest.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 LabTest Generator');
  console.log('='.repeat(60));
  
  await removeDuplicates();
  
  const ITEMS_TO_GENERATE = [
    { name: 'Example Item 1', category: 'Category A' },
    { name: 'Example Item 2', category: 'Category B' },
    { name: 'Example Item 3', category: 'Category C' }
  ];
  
  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} labTest records...\n`);
  
  const existing = await prisma.labTest.findMany({ 
    select: { name: true, id: true } 
  });
  const existingNames = new Set(existing.map(e => e.name.toLowerCase()));
  
  let created = 0;
  let skipped = 0;
  let failed = 0;
  
  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }
    
    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateLabTest(item);
    
    if (!data) {
      failed++;
      continue;
    }
    
    try {
      // Remove any relation fields that AI might have included
      const { LabConditionLink, ...createData } = data as any;
      
      await prisma.labTest.create({
        data: {
          id: crypto.randomUUID(),
          ...createData,
          updatedAt: new Date()
        }
      });
      
      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }
    
    await new Promise(resolve => setTimeout(resolve, 800));
  }
  
  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);
  
  const total = await prisma.labTest.count();
  console.log(`   Total in database: ${total}`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
