/**
 * PatientEncounterCase Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive patientEncounterCase records with AI assistance
 */

import { prisma } from '../_shared/db.js';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface PatientEncounterCaseData {
  patientName: string;
  chiefComplaint: string;
  age: number;
  sex: string;
  vitalSigns: any;
  historyData: any;
  physicalExamData: any;
  labData: any;
  essentialQuestions: string[];
  helpfulQuestions: string[];
  unnecessaryQuestions: string[];
  correctDiagnosis: string;
  differentialDiagnoses: string[];
  idealWorkup: string[];
  teachingPoints: string[];
}

const PROMPT_TEMPLATE = `You are a senior physician and PANCE board examiner creating a complex, realistic OSCE patient encounter case for PA students. The case must be at a level appropriate for PANCE/PANRE certification exams.

## CASE REQUIREMENTS FOR: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

### Clinical Realism Standards:
1. **Patient Demographics**: Create a believable patient with a culturally diverse name. Age and sex should be epidemiologically appropriate for the condition.
2. **Chief Complaint**: Use the patient's own words, not medical terminology. Include duration.
3. **Vital Signs**: Must be numerically accurate and consistent with the diagnosis (e.g., fever in infection, tachycardia in PE).
4. **History**: Include subtle red flags and risk factors that a skilled clinician would catch. Add 1-2 misleading details that test clinical reasoning.
5. **Physical Exam**: Include both positive AND negative findings. Negative findings should rule out differentials.
6. **Lab/Imaging**: Include specific numeric values with units. Some should be borderline to test interpretation.

### Question Categories:
- **Essential Questions**: Must-ask questions that would significantly change management if missed (5-7 questions)
- **Helpful Questions**: Good questions that add useful context (3-5 questions)  
- **Unnecessary Questions**: Time-wasters that a skilled interviewer would skip (3-5 questions)

### Teaching Points:
Include 4-6 high-yield pearls that distinguish expert from novice clinicians. Focus on:
- Classic buzzwords and board-favorite presentations
- Time-critical interventions
- Common pitfalls and diagnostic errors
- Evidence-based management priorities

Return ONLY valid JSON with this exact structure:

{
  "patientName": "Realistic full name",
  "chiefComplaint": "Patient's own words with duration",
  "age": 45,
  "sex": "male or female",
  "vitalSigns": {
    "bp": "systolic/diastolic",
    "hr": 82,
    "rr": 16,
    "temp": "98.6F or 37C",
    "spo2": "percentage on room air or oxygen"
  },
  "historyData": {
    "hpi": "Detailed narrative with OLDCARTS elements",
    "pmh": ["List of conditions"],
    "psh": "Surgeries",
    "medications": ["Current meds with doses"],
    "allergies": "Drug allergies with reaction type",
    "social": "Tobacco/alcohol/drugs, occupation, living situation",
    "family": "Relevant family history"
  },
  "physicalExamData": {
    "general": "Appearance and distress level",
    "heent": "If relevant",
    "cardiovascular": "Heart sounds, JVD, edema",
    "pulmonary": "Breath sounds, respiratory effort",
    "abdomen": "Inspection, auscultation, palpation, percussion",
    "neurological": "If relevant",
    "extremities": "Pulses, edema, skin changes",
    "skin": "If relevant"
  },
  "labData": {
    "key_labs_with_values_and_units": "Include abnormal flags",
    "imaging_findings": "If applicable"
  },
  "essentialQuestions": [
    "5-7 critical history questions that change management"
  ],
  "helpfulQuestions": [
    "3-5 useful but not critical questions"
  ],
  "unnecessaryQuestions": [
    "3-5 questions that waste time or are not clinically relevant"
  ],
  "correctDiagnosis": "Most likely diagnosis with any subtypes",
  "differentialDiagnoses": [
    "4-6 reasonable alternative diagnoses ranked by likelihood"
  ],
  "idealWorkup": [
    "Ordered list of tests/studies with rationale"
  ],
  "teachingPoints": [
    "4-6 high-yield clinical pearls"
  ]
}

CRITICAL JSON RULES:
- Return ONLY the JSON object, no markdown formatting or backticks
- Use straight apostrophes (') never curly quotes
- Write out symbols: "greater than" not ">"
- NO special characters: avoid symbols like greater than or equal signs
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Ensure all trailing commas are removed

Return the JSON now:`;

async function generatePatientEncounterCase(
  item: { name: string; category: string },
  retryCount = 0
): Promise<PatientEncounterCaseData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-pro' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for patientEncounterCase: "${item.name}"
    
Return this structure with NO markdown:
{
  "patientName": "value",
  "chiefComplaint": "value",
  "age": 0,
  "sex": "value",
  "vitalSigns": "value",
  "historyData": "value",
  "physicalExamData": "value",
  "labData": "value",
  "essentialQuestions": ["item1", "item2"],
  "helpfulQuestions": ["item1", "item2"],
  "unnecessaryQuestions": ["item1", "item2"],
  "correctDiagnosis": "value",
  "differentialDiagnoses": ["item1", "item2"],
  "idealWorkup": ["item1", "item2"],
  "teachingPoints": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: PatientEncounterCaseData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generatePatientEncounterCase(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generatePatientEncounterCase(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.patientEncounterCase.findMany({
    select: { id: true, chiefComplaint: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.chiefComplaint.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.chiefComplaint}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.chiefComplaint}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.patientEncounterCase.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 PatientEncounterCase Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Cardiovascular
    { name: 'Chest Pain - Acute MI', category: 'Cardiovascular' },
    { name: 'Chest Pain - Unstable Angina', category: 'Cardiovascular' },
    { name: 'Dyspnea - Heart Failure', category: 'Cardiovascular' },
    { name: 'Palpitations - Atrial Fibrillation', category: 'Cardiovascular' },
    { name: 'Syncope Evaluation', category: 'Cardiovascular' },
    { name: 'Hypertensive Emergency', category: 'Cardiovascular' },
    { name: 'Deep Vein Thrombosis', category: 'Cardiovascular' },
    { name: 'Peripheral Arterial Disease', category: 'Cardiovascular' },

    // Pulmonary
    { name: 'Shortness of Breath - Pneumonia', category: 'Pulmonary' },
    { name: 'Shortness of Breath - COPD Exacerbation', category: 'Pulmonary' },
    { name: 'Shortness of Breath - Asthma', category: 'Pulmonary' },
    { name: 'Shortness of Breath - Pulmonary Embolism', category: 'Pulmonary' },
    { name: 'Cough - Bronchitis', category: 'Pulmonary' },
    { name: 'Hemoptysis', category: 'Pulmonary' },

    // Gastrointestinal
    { name: 'Abdominal Pain - Appendicitis', category: 'Gastrointestinal' },
    { name: 'Abdominal Pain - Cholecystitis', category: 'Gastrointestinal' },
    { name: 'Abdominal Pain - Pancreatitis', category: 'Gastrointestinal' },
    { name: 'Abdominal Pain - Bowel Obstruction', category: 'Gastrointestinal' },
    { name: 'GI Bleeding - Upper', category: 'Gastrointestinal' },
    { name: 'GI Bleeding - Lower', category: 'Gastrointestinal' },
    { name: 'Diarrhea - Infectious', category: 'Gastrointestinal' },
    { name: 'Jaundice', category: 'Gastrointestinal' },

    // Neurological
    { name: 'Headache - Migraine', category: 'Neurological' },
    { name: 'Headache - Meningitis', category: 'Neurological' },
    { name: 'Headache - Subarachnoid Hemorrhage', category: 'Neurological' },
    { name: 'Weakness - Stroke', category: 'Neurological' },
    { name: 'Altered Mental Status', category: 'Neurological' },
    { name: 'Seizure', category: 'Neurological' },
    { name: 'Dizziness - Vertigo', category: 'Neurological' },
    { name: 'Back Pain - Cauda Equina', category: 'Neurological' },

    // Infectious
    { name: 'Fever - Sepsis', category: 'Infectious' },
    { name: 'Fever - UTI/Pyelonephritis', category: 'Infectious' },
    { name: 'Fever - Cellulitis', category: 'Infectious' },
    { name: 'Sore Throat - Strep Pharyngitis', category: 'Infectious' },
    { name: 'Rash - Viral Exanthem', category: 'Infectious' },

    // Endocrine/Metabolic
    { name: 'Polyuria/Polydipsia - New Diabetes', category: 'Endocrine' },
    { name: 'Fatigue - Hypothyroidism', category: 'Endocrine' },
    { name: 'Weight Loss - Hyperthyroidism', category: 'Endocrine' },
    { name: 'Diabetic Ketoacidosis', category: 'Endocrine' },
    { name: 'Adrenal Crisis', category: 'Endocrine' },

    // Musculoskeletal
    { name: 'Joint Pain - Gout', category: 'Musculoskeletal' },
    { name: 'Joint Pain - Septic Arthritis', category: 'Musculoskeletal' },
    { name: 'Low Back Pain - Disc Herniation', category: 'Musculoskeletal' },
    { name: 'Knee Pain - ACL Injury', category: 'Musculoskeletal' },
    { name: 'Shoulder Pain - Rotator Cuff', category: 'Musculoskeletal' },

    // Renal/Urological
    { name: 'Flank Pain - Kidney Stone', category: 'Renal' },
    { name: 'Hematuria', category: 'Renal' },
    { name: 'Acute Kidney Injury', category: 'Renal' },
    { name: 'Testicular Pain - Torsion', category: 'Renal' },

    // Psychiatric
    { name: 'Chest Pain - Panic Attack', category: 'Psychiatric' },
    { name: 'Suicidal Ideation', category: 'Psychiatric' },
    { name: 'Acute Psychosis', category: 'Psychiatric' },

    // OB/GYN
    { name: 'Vaginal Bleeding - Ectopic Pregnancy', category: 'OB/GYN' },
    { name: 'Pelvic Pain - PID', category: 'OB/GYN' },
    { name: 'Vaginal Discharge', category: 'OB/GYN' },

    // Pediatric
    { name: 'Fever in Infant', category: 'Pediatric' },
    { name: 'Wheezing Child - Bronchiolitis', category: 'Pediatric' },
    { name: 'Abdominal Pain - Intussusception', category: 'Pediatric' },
    { name: 'Limp in Child', category: 'Pediatric' },

    // Dermatologic
    { name: 'Rash - Stevens-Johnson Syndrome', category: 'Dermatologic' },
    { name: 'Rash - Zoster', category: 'Dermatologic' },

    // Toxicologic
    { name: 'Overdose - Acetaminophen', category: 'Toxicologic' },
    { name: 'Overdose - Opioid', category: 'Toxicologic' },
    { name: 'Alcohol Withdrawal', category: 'Toxicologic' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} patientEncounterCase records...\n`);

  const existing = await prisma.patientEncounterCase.findMany({
    select: { chiefComplaint: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.chiefComplaint.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generatePatientEncounterCase(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      // Remove any relation fields that AI might have included
      const { PatientEncounterSession, ...createData } = data as any;

      await prisma.patientEncounterCase.create({
        data: {
          id: uuidv4(),
          ...createData,
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.patientEncounterCase.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
