/**
 * PhysiologyConcept Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive physiologyConcept records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface PhysiologyConceptData {
  name: string;
  displayName: string;
  aliases: string[];
  system: string;
  category: string;
  description: string;
  mechanism: string;
  clinicalSignificance: string;
  relatedConditions: string[];
  relatedDrugs: string[];
  associatedLabs: string[];
  boardYieldFacts: string[];
  clinicalPearls: string[];
  commonMistakes: string[];
  compareContrast: any;
  compensatoryMechanisms: string[];
  curveDescription: string;
  curveShifts: any;
  curveType: string;
  decompensationSigns: string[];
  drugEffects: any;
  drugTargets: string[];
  feedbackLoops: string;
  graphUrl: string;
  isHighYield: boolean;
  keyEquations: any;
  labChanges: any;
  mnemonics: string[];
  molecularBasis: string;
  normalValues: string;
  panceYield: number;
  pathophysiology: string;
  regulatoryFactors: string[];
  signalTransduction: string;
  testQuestionTips: string[];
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "name": "value",
  "displayName": "value",
  "aliases": ["item1", "item2"],
  "system": "value",
  "category": "value",
  "description": "value",
  "mechanism": "value",
  "clinicalSignificance": "value",
  "relatedConditions": ["item1", "item2"],
  "relatedDrugs": ["item1", "item2"],
  "associatedLabs": ["item1", "item2"],
  "boardYieldFacts": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "compareContrast": "value",
  "compensatoryMechanisms": ["item1", "item2"],
  "curveDescription": "value",
  "curveShifts": "value",
  "curveType": "value",
  "decompensationSigns": ["item1", "item2"],
  "drugEffects": "value",
  "drugTargets": ["item1", "item2"],
  "feedbackLoops": "value",
  "graphUrl": "value",
  "isHighYield": true,
  "keyEquations": "value",
  "labChanges": "value",
  "mnemonics": ["item1", "item2"],
  "molecularBasis": "value",
  "normalValues": "value",
  "panceYield": 0,
  "pathophysiology": "value",
  "regulatoryFactors": ["item1", "item2"],
  "signalTransduction": "value",
  "testQuestionTips": ["item1", "item2"]
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generatePhysiologyConcept(
  item: { name: string; category: string },
  retryCount = 0
): Promise<PhysiologyConceptData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for physiologyConcept: "${item.name}"
    
Return this structure with NO markdown:
{
  "name": "value",
  "displayName": "value",
  "aliases": ["item1", "item2"],
  "system": "value",
  "category": "value",
  "description": "value",
  "mechanism": "value",
  "clinicalSignificance": "value",
  "relatedConditions": ["item1", "item2"],
  "relatedDrugs": ["item1", "item2"],
  "associatedLabs": ["item1", "item2"],
  "boardYieldFacts": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "compareContrast": "value",
  "compensatoryMechanisms": ["item1", "item2"],
  "curveDescription": "value",
  "curveShifts": "value",
  "curveType": "value",
  "decompensationSigns": ["item1", "item2"],
  "drugEffects": "value",
  "drugTargets": ["item1", "item2"],
  "feedbackLoops": "value",
  "graphUrl": "value",
  "isHighYield": true,
  "keyEquations": "value",
  "labChanges": "value",
  "mnemonics": ["item1", "item2"],
  "molecularBasis": "value",
  "normalValues": "value",
  "panceYield": 0,
  "pathophysiology": "value",
  "regulatoryFactors": ["item1", "item2"],
  "signalTransduction": "value",
  "testQuestionTips": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: PhysiologyConceptData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generatePhysiologyConcept(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generatePhysiologyConcept(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.physiologyConcept.findMany({
    select: { id: true, name: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.name}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.name}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.physiologyConcept.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 PhysiologyConcept Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // CARDIOVASCULAR PHYSIOLOGY
    { name: 'Cardiac Output', category: 'Hemodynamics' },
    { name: 'Stroke Volume', category: 'Hemodynamics' },
    { name: 'Preload', category: 'Hemodynamics' },
    { name: 'Afterload', category: 'Hemodynamics' },
    { name: 'Contractility', category: 'Hemodynamics' },
    { name: 'Frank-Starling Mechanism', category: 'Cardiac Mechanics' },
    { name: 'Cardiac Action Potential', category: 'Electrophysiology' },
    { name: 'Automaticity', category: 'Electrophysiology' },
    { name: 'Refractoriness', category: 'Electrophysiology' },
    { name: 'Conduction System', category: 'Electrophysiology' },
    { name: 'Systemic Vascular Resistance', category: 'Hemodynamics' },
    { name: 'Pulmonary Vascular Resistance', category: 'Hemodynamics' },
    { name: 'Mean Arterial Pressure', category: 'Hemodynamics' },
    { name: 'Venous Return', category: 'Hemodynamics' },
    { name: 'Baroreceptor Reflex', category: 'Autonomic Regulation' },
    { name: 'Coronary Blood Flow', category: 'Cardiac Perfusion' },
    { name: 'Cardiac Cycle', category: 'Cardiac Mechanics' },
    { name: 'Pressure-Volume Loop', category: 'Cardiac Mechanics' },
    { name: 'Ejection Fraction', category: 'Cardiac Function' },
    { name: 'Diastolic Function', category: 'Cardiac Function' },

    // RESPIRATORY PHYSIOLOGY
    { name: 'Ventilation-Perfusion Matching', category: 'Gas Exchange' },
    { name: 'Oxygen-Hemoglobin Dissociation Curve', category: 'Gas Transport' },
    { name: 'Bohr Effect', category: 'Gas Transport' },
    { name: 'Haldane Effect', category: 'Gas Transport' },
    { name: 'Pulmonary Compliance', category: 'Lung Mechanics' },
    { name: 'Airway Resistance', category: 'Lung Mechanics' },
    { name: 'Surfactant Function', category: 'Lung Mechanics' },
    { name: 'Lung Volumes and Capacities', category: 'Pulmonary Function' },
    { name: 'Dead Space Ventilation', category: 'Ventilation' },
    { name: 'Alveolar Gas Equation', category: 'Gas Exchange' },
    { name: 'Diffusion Capacity', category: 'Gas Exchange' },
    { name: 'Hypoxic Pulmonary Vasoconstriction', category: 'Pulmonary Circulation' },
    { name: 'Work of Breathing', category: 'Lung Mechanics' },
    { name: 'Respiratory Control', category: 'Neural Regulation' },
    { name: 'Chemoreceptor Response', category: 'Neural Regulation' },

    // RENAL PHYSIOLOGY
    { name: 'Glomerular Filtration', category: 'Renal Function' },
    { name: 'GFR Regulation', category: 'Renal Function' },
    { name: 'Tubuloglomerular Feedback', category: 'Autoregulation' },
    { name: 'Countercurrent Mechanism', category: 'Concentration' },
    { name: 'Sodium Handling', category: 'Electrolyte Balance' },
    { name: 'Potassium Handling', category: 'Electrolyte Balance' },
    { name: 'Acid-Base Balance', category: 'Homeostasis' },
    { name: 'Bicarbonate Reabsorption', category: 'Acid-Base' },
    { name: 'Hydrogen Ion Secretion', category: 'Acid-Base' },
    { name: 'Renin-Angiotensin-Aldosterone System', category: 'Hormonal Regulation' },
    { name: 'ADH and Water Balance', category: 'Hormonal Regulation' },
    { name: 'Atrial Natriuretic Peptide', category: 'Hormonal Regulation' },
    { name: 'Renal Clearance', category: 'Renal Function' },
    { name: 'Fractional Excretion', category: 'Renal Function' },
    { name: 'Calcium and Phosphate Handling', category: 'Mineral Balance' },

    // GASTROINTESTINAL PHYSIOLOGY
    { name: 'Gastric Acid Secretion', category: 'Secretion' },
    { name: 'Pepsin Activation', category: 'Digestion' },
    { name: 'Pancreatic Secretion', category: 'Secretion' },
    { name: 'Bile Secretion and Enterohepatic Circulation', category: 'Hepatobiliary' },
    { name: 'Intestinal Motility', category: 'Motility' },
    { name: 'Migrating Motor Complex', category: 'Motility' },
    { name: 'Lower Esophageal Sphincter', category: 'Motility' },
    { name: 'Carbohydrate Digestion and Absorption', category: 'Absorption' },
    { name: 'Protein Digestion and Absorption', category: 'Absorption' },
    { name: 'Fat Digestion and Absorption', category: 'Absorption' },
    { name: 'Iron Absorption', category: 'Mineral Transport' },
    { name: 'Vitamin B12 Absorption', category: 'Absorption' },
    { name: 'Gastric Emptying Regulation', category: 'Motility' },
    { name: 'Enteric Nervous System', category: 'Neural Control' },
    { name: 'GI Hormones Overview', category: 'Hormonal Regulation' },

    // ENDOCRINE PHYSIOLOGY
    { name: 'Hypothalamic-Pituitary Axis', category: 'Neuroendocrine' },
    { name: 'Thyroid Hormone Synthesis', category: 'Thyroid Function' },
    { name: 'Thyroid Hormone Regulation', category: 'Thyroid Function' },
    { name: 'Cortisol Regulation and Effects', category: 'Adrenal Function' },
    { name: 'Aldosterone Regulation and Effects', category: 'Adrenal Function' },
    { name: 'Catecholamine Release', category: 'Adrenal Function' },
    { name: 'Insulin Secretion and Action', category: 'Glucose Metabolism' },
    { name: 'Glucagon Secretion and Action', category: 'Glucose Metabolism' },
    { name: 'Counter-Regulatory Hormones', category: 'Glucose Metabolism' },
    { name: 'Calcium Homeostasis', category: 'Mineral Balance' },
    { name: 'PTH Effects', category: 'Mineral Balance' },
    { name: 'Vitamin D Metabolism', category: 'Mineral Balance' },
    { name: 'Growth Hormone Axis', category: 'Growth Regulation' },
    { name: 'Prolactin Regulation', category: 'Reproductive' },

    // NEUROPHYSIOLOGY
    { name: 'Action Potential Generation', category: 'Neurophysiology' },
    { name: 'Synaptic Transmission', category: 'Synaptic' },
    { name: 'Neuromuscular Junction', category: 'Synaptic' },
    { name: 'Pain Pathway', category: 'Sensory' },
    { name: 'Motor Control Pathways', category: 'Motor' },
    { name: 'Cerebellar Function', category: 'Motor' },
    { name: 'Basal Ganglia Circuits', category: 'Motor' },
    { name: 'Autonomic Nervous System', category: 'Autonomic' },
    { name: 'Blood-Brain Barrier', category: 'Cerebrovascular' },
    { name: 'CSF Production and Flow', category: 'Cerebrovascular' },
    { name: 'Cerebral Autoregulation', category: 'Cerebrovascular' },
    { name: 'Visual Processing', category: 'Sensory' },
    { name: 'Auditory Processing', category: 'Sensory' },
    { name: 'Vestibular Function', category: 'Sensory' },

    // HEMATOLOGY PHYSIOLOGY
    { name: 'Coagulation Cascade', category: 'Coagulation' },
    { name: 'Platelet Activation', category: 'Hemostasis' },
    { name: 'Fibrinolysis', category: 'Hemostasis' },
    { name: 'Erythropoiesis', category: 'Hematopoiesis' },
    { name: 'Hemoglobin Function', category: 'Oxygen Transport' },
    { name: 'Iron Metabolism', category: 'Mineral Transport' },
    { name: 'Vitamin K Function', category: 'Coagulation' },
    { name: 'White Blood Cell Function', category: 'Immunity' },

    // IMMUNOLOGY PHYSIOLOGY
    { name: 'Innate Immune Response', category: 'Innate Immunity' },
    { name: 'Adaptive Immune Response', category: 'Adaptive Immunity' },
    { name: 'T Cell Activation', category: 'Adaptive Immunity' },
    { name: 'B Cell Activation and Antibody Production', category: 'Adaptive Immunity' },
    { name: 'Complement System', category: 'Innate Immunity' },
    { name: 'Inflammatory Response', category: 'Innate Immunity' },
    { name: 'Cytokine Function', category: 'Immune Regulation' },

    // MUSCULOSKELETAL PHYSIOLOGY
    { name: 'Skeletal Muscle Contraction', category: 'Muscle Physiology' },
    { name: 'Smooth Muscle Contraction', category: 'Muscle Physiology' },
    { name: 'Excitation-Contraction Coupling', category: 'Muscle Physiology' },
    { name: 'Bone Remodeling', category: 'Skelite Metabolism' },
    { name: 'Calcium in Muscle Function', category: 'Muscle Physiology' },

    // REPRODUCTIVE PHYSIOLOGY
    { name: 'Menstrual Cycle Regulation', category: 'Female Reproductive' },
    { name: 'Ovulation', category: 'Female Reproductive' },
    { name: 'Spermatogenesis', category: 'Male Reproductive' },
    { name: 'Testosterone Regulation', category: 'Male Reproductive' },
    { name: 'Pregnancy Hormones', category: 'Pregnancy' },
    { name: 'Lactation Physiology', category: 'Pregnancy' },

    // FLUID AND ELECTROLYTE PHYSIOLOGY
    { name: 'Body Fluid Compartments', category: 'Fluid Balance' },
    { name: 'Osmolality Regulation', category: 'Fluid Balance' },
    { name: 'Starling Forces', category: 'Fluid Exchange' },
    { name: 'Anion Gap', category: 'Acid-Base' },
    { name: 'Henderson-Hasselbalch Equation', category: 'Acid-Base' },
    { name: 'Metabolic Acidosis Compensation', category: 'Acid-Base' },
    { name: 'Respiratory Acidosis Compensation', category: 'Acid-Base' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} physiologyConcept records...\n`);

  const existing = await prisma.physiologyConcept.findMany({
    select: { name: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.name.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generatePhysiologyConcept(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      // Remove any relation fields that AI might have included
      const { PhysiologyConditionLink, ...createData } = data as any;

      await prisma.physiologyConcept.create({
        data: {
          id: uuidv4(),
          ...createData,
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.physiologyConcept.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
