/**
 * PhysicalExamFinding Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive physicalExamFinding records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface PhysicalExamFindingData {
  name: string;
  system: string;
  description: string;
  clinicalSignificance: string;
  aliases: string[];
  associatedFindings: string[];
  boardYieldFacts: string[];
  category: string;
  clinicalPearls: string[];
  commonMistakes: string[];
  differentialFor: string[];
  eponymousName: string;
  equipmentNeeded: string[];
  evidenceQuality: string;
  findingType: string;
  gradingScale: string;
  howToDocument: string;
  howToElicit: string;
  imageUrl: string;
  isHighYield: boolean;
  mnemonics: string[];
  negativeIndicates: string[];
  negativeLR: number;
  normalVariants: string[];
  panceYield: number;
  patientPosition: string;
  positiveIndicates: string[];
  positiveLR: number;
  sensitivity: number;
  specificity: number;
  testQuestionTips: string[];
  videoUrl: string;
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "name": "value",
  "system": "value",
  "description": "value",
  "clinicalSignificance": "value",
  "aliases": ["item1", "item2"],
  "associatedFindings": ["item1", "item2"],
  "boardYieldFacts": ["item1", "item2"],
  "category": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "differentialFor": ["item1", "item2"],
  "eponymousName": "value",
  "equipmentNeeded": ["item1", "item2"],
  "evidenceQuality": "value",
  "findingType": "value",
  "gradingScale": "value",
  "howToDocument": "value",
  "howToElicit": "value",
  "imageUrl": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "negativeIndicates": ["item1", "item2"],
  "negativeLR": "value",
  "normalVariants": ["item1", "item2"],
  "panceYield": 0,
  "patientPosition": "value",
  "positiveIndicates": ["item1", "item2"],
  "positiveLR": "value",
  "sensitivity": "value",
  "specificity": "value",
  "testQuestionTips": ["item1", "item2"],
  "videoUrl": "value"
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generatePhysicalExamFinding(
  item: { name: string; category: string },
  retryCount = 0
): Promise<PhysicalExamFindingData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for physicalExamFinding: "${item.name}"
    
Return this structure with NO markdown:
{
  "name": "value",
  "system": "value",
  "description": "value",
  "clinicalSignificance": "value",
  "aliases": ["item1", "item2"],
  "associatedFindings": ["item1", "item2"],
  "boardYieldFacts": ["item1", "item2"],
  "category": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "differentialFor": ["item1", "item2"],
  "eponymousName": "value",
  "equipmentNeeded": ["item1", "item2"],
  "evidenceQuality": "value",
  "findingType": "value",
  "gradingScale": "value",
  "howToDocument": "value",
  "howToElicit": "value",
  "imageUrl": "value",
  "isHighYield": true,
  "mnemonics": ["item1", "item2"],
  "negativeIndicates": ["item1", "item2"],
  "negativeLR": "value",
  "normalVariants": ["item1", "item2"],
  "panceYield": 0,
  "patientPosition": "value",
  "positiveIndicates": ["item1", "item2"],
  "positiveLR": "value",
  "sensitivity": "value",
  "specificity": "value",
  "testQuestionTips": ["item1", "item2"],
  "videoUrl": "value"
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: PhysicalExamFindingData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generatePhysicalExamFinding(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generatePhysicalExamFinding(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.physicalExamFinding.findMany({
    select: { id: true, name: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.name}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.name}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.physicalExamFinding.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 PhysicalExamFinding Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // CARDIAC FINDINGS
    { name: 'S3 Gallop', category: 'Cardiac' },
    { name: 'S4 Gallop', category: 'Cardiac' },
    { name: 'Systolic Ejection Murmur', category: 'Cardiac' },
    { name: 'Holosystolic Murmur', category: 'Cardiac' },
    { name: 'Diastolic Murmur', category: 'Cardiac' },
    { name: 'Continuous Murmur', category: 'Cardiac' },
    { name: 'Pericardial Friction Rub', category: 'Cardiac' },
    { name: 'Jugular Venous Distension', category: 'Cardiac' },
    { name: 'Hepatojugular Reflux', category: 'Cardiac' },
    { name: 'Displaced PMI', category: 'Cardiac' },
    { name: 'Pulsus Paradoxus', category: 'Cardiac' },
    { name: 'Pulsus Alternans', category: 'Cardiac' },
    { name: 'Diminished Peripheral Pulses', category: 'Cardiac' },
    { name: 'Water Hammer Pulse', category: 'Cardiac' },
    { name: 'Cannon A Waves', category: 'Cardiac' },
    { name: 'Kussmaul Sign', category: 'Cardiac' },
    { name: 'Point of Maximal Impulse', category: 'Cardiac' },
    { name: 'Carotid Bruit', category: 'Vascular' },
    { name: 'Radio-Femoral Delay', category: 'Vascular' },
    { name: 'Unequal Blood Pressures', category: 'Vascular' },

    // PULMONARY FINDINGS
    { name: 'Crackles (Rales)', category: 'Pulmonary' },
    { name: 'Fine Crackles', category: 'Pulmonary' },
    { name: 'Coarse Crackles', category: 'Pulmonary' },
    { name: 'Wheezes', category: 'Pulmonary' },
    { name: 'Rhonchi', category: 'Pulmonary' },
    { name: 'Stridor', category: 'Pulmonary' },
    { name: 'Pleural Friction Rub', category: 'Pulmonary' },
    { name: 'Diminished Breath Sounds', category: 'Pulmonary' },
    { name: 'Absent Breath Sounds', category: 'Pulmonary' },
    { name: 'Bronchial Breath Sounds', category: 'Pulmonary' },
    { name: 'Vesicular Breath Sounds', category: 'Pulmonary' },
    { name: 'Egophony', category: 'Pulmonary' },
    { name: 'Whispered Pectoriloquy', category: 'Pulmonary' },
    { name: 'Tactile Fremitus Increased', category: 'Pulmonary' },
    { name: 'Tactile Fremitus Decreased', category: 'Pulmonary' },
    { name: 'Dullness to Percussion', category: 'Pulmonary' },
    { name: 'Hyperresonance to Percussion', category: 'Pulmonary' },
    { name: 'Tracheal Deviation', category: 'Pulmonary' },
    { name: 'Accessory Muscle Use', category: 'Pulmonary' },
    { name: 'Barrel Chest', category: 'Pulmonary' },
    { name: 'Subcutaneous Emphysema', category: 'Pulmonary' },
    { name: 'Tripod Position', category: 'Pulmonary' },

    // ABDOMINAL FINDINGS
    { name: 'Rebound Tenderness', category: 'Abdominal' },
    { name: 'Voluntary Guarding', category: 'Abdominal' },
    { name: 'Involuntary Guarding', category: 'Abdominal' },
    { name: 'Rigidity', category: 'Abdominal' },
    { name: 'Murphy Sign', category: 'Abdominal' },
    { name: 'McBurney Point Tenderness', category: 'Abdominal' },
    { name: 'Rovsing Sign', category: 'Abdominal' },
    { name: 'Psoas Sign', category: 'Abdominal' },
    { name: 'Obturator Sign', category: 'Abdominal' },
    { name: 'Hepatomegaly', category: 'Abdominal' },
    { name: 'Splenomegaly', category: 'Abdominal' },
    { name: 'Ascites', category: 'Abdominal' },
    { name: 'Fluid Wave', category: 'Abdominal' },
    { name: 'Shifting Dullness', category: 'Abdominal' },
    { name: 'Caput Medusae', category: 'Abdominal' },
    { name: 'Cullen Sign', category: 'Abdominal' },
    { name: 'Grey Turner Sign', category: 'Abdominal' },
    { name: 'Carnett Sign', category: 'Abdominal' },
    { name: 'Courvoisier Sign', category: 'Abdominal' },
    { name: 'Succession Splash', category: 'Abdominal' },
    { name: 'Absent Bowel Sounds', category: 'Abdominal' },
    { name: 'Hyperactive Bowel Sounds', category: 'Abdominal' },
    { name: 'High-Pitched Bowel Sounds', category: 'Abdominal' },
    { name: 'Abdominal Bruit', category: 'Abdominal' },

    // NEUROLOGICAL FINDINGS
    { name: 'Babinski Sign', category: 'Neurological' },
    { name: 'Hoffman Sign', category: 'Neurological' },
    { name: 'Brudzinski Sign', category: 'Neurological' },
    { name: 'Kernig Sign', category: 'Neurological' },
    { name: 'Romberg Sign', category: 'Neurological' },
    { name: 'Pronator Drift', category: 'Neurological' },
    { name: 'Clonus', category: 'Neurological' },
    { name: 'Hyperreflexia', category: 'Neurological' },
    { name: 'Hyporeflexia', category: 'Neurological' },
    { name: 'Areflexia', category: 'Neurological' },
    { name: 'Nystagmus', category: 'Neurological' },
    { name: 'Ptosis', category: 'Neurological' },
    { name: 'Facial Droop', category: 'Neurological' },
    { name: 'Pupil Asymmetry (Anisocoria)', category: 'Neurological' },
    { name: 'Papilledema', category: 'Neurological' },
    { name: 'Chvostek Sign', category: 'Neurological' },
    { name: 'Trousseau Sign', category: 'Neurological' },
    { name: 'Asterixis', category: 'Neurological' },
    { name: 'Intention Tremor', category: 'Neurological' },
    { name: 'Resting Tremor', category: 'Neurological' },
    { name: 'Cogwheel Rigidity', category: 'Neurological' },
    { name: 'Lead Pipe Rigidity', category: 'Neurological' },
    { name: 'Shuffling Gait', category: 'Neurological' },
    { name: 'Ataxic Gait', category: 'Neurological' },
    { name: 'Steppage Gait', category: 'Neurological' },
    { name: 'Scissoring Gait', category: 'Neurological' },
    { name: 'Decerebrate Posturing', category: 'Neurological' },
    { name: 'Decorticate Posturing', category: 'Neurological' },
    { name: 'Battle Sign', category: 'Neurological' },
    { name: 'Raccoon Eyes', category: 'Neurological' },
    { name: 'Doll Eyes Reflex', category: 'Neurological' },
    { name: 'RAPD (Marcus Gunn Pupil)', category: 'Neurological' },
    { name: 'Jaw Jerk Reflex', category: 'Neurological' },
    { name: 'Glabellar Reflex', category: 'Neurological' },

    // MUSCULOSKELETAL FINDINGS
    { name: 'Lachman Test', category: 'Musculoskeletal' },
    { name: 'Anterior Drawer Test (Knee)', category: 'Musculoskeletal' },
    { name: 'Posterior Drawer Test', category: 'Musculoskeletal' },
    { name: 'McMurray Test', category: 'Musculoskeletal' },
    { name: 'Valgus Stress Test', category: 'Musculoskeletal' },
    { name: 'Varus Stress Test', category: 'Musculoskeletal' },
    { name: 'Straight Leg Raise', category: 'Musculoskeletal' },
    { name: 'Crossed Straight Leg Raise', category: 'Musculoskeletal' },
    { name: 'Spurling Test', category: 'Musculoskeletal' },
    { name: 'Phalen Test', category: 'Musculoskeletal' },
    { name: 'Tinel Sign', category: 'Musculoskeletal' },
    { name: 'Finkelstein Test', category: 'Musculoskeletal' },
    { name: 'Empty Can Test', category: 'Musculoskeletal' },
    { name: 'Drop Arm Test', category: 'Musculoskeletal' },
    { name: 'Hawkins Test', category: 'Musculoskeletal' },
    { name: 'Neer Test', category: 'Musculoskeletal' },
    { name: 'Apprehension Test (Shoulder)', category: 'Musculoskeletal' },
    { name: 'Speed Test', category: 'Musculoskeletal' },
    { name: 'Yergason Test', category: 'Musculoskeletal' },
    { name: 'Thompson Test', category: 'Musculoskeletal' },
    { name: 'Anterior Drawer Test (Ankle)', category: 'Musculoskeletal' },
    { name: 'Talar Tilt Test', category: 'Musculoskeletal' },
    { name: 'Thomas Test', category: 'Musculoskeletal' },
    { name: 'FABER Test', category: 'Musculoskeletal' },
    { name: 'FADIR Test', category: 'Musculoskeletal' },
    { name: 'Ober Test', category: 'Musculoskeletal' },
    { name: 'Trendelenburg Test', category: 'Musculoskeletal' },
    { name: 'Schober Test', category: 'Musculoskeletal' },
    { name: 'Sacroiliac Joint Compression', category: 'Musculoskeletal' },
    { name: 'Heberden Nodes', category: 'Musculoskeletal' },
    { name: 'Bouchard Nodes', category: 'Musculoskeletal' },
    { name: 'Swan Neck Deformity', category: 'Musculoskeletal' },
    { name: 'Boutonniere Deformity', category: 'Musculoskeletal' },
    { name: 'Ulnar Deviation', category: 'Musculoskeletal' },
    { name: 'Joint Effusion', category: 'Musculoskeletal' },
    { name: 'Crepitus', category: 'Musculoskeletal' },

    // DERMATOLOGIC FINDINGS
    { name: 'Petechiae', category: 'Dermatologic' },
    { name: 'Purpura', category: 'Dermatologic' },
    { name: 'Ecchymosis', category: 'Dermatologic' },
    { name: 'Jaundice', category: 'Dermatologic' },
    { name: 'Scleral Icterus', category: 'Dermatologic' },
    { name: 'Cyanosis (Central)', category: 'Dermatologic' },
    { name: 'Cyanosis (Peripheral)', category: 'Dermatologic' },
    { name: 'Pallor', category: 'Dermatologic' },
    { name: 'Clubbing', category: 'Dermatologic' },
    { name: 'Koilonychia', category: 'Dermatologic' },
    { name: 'Splinter Hemorrhages', category: 'Dermatologic' },
    { name: 'Janeway Lesions', category: 'Dermatologic' },
    { name: 'Osler Nodes', category: 'Dermatologic' },
    { name: 'Erythema Marginatum', category: 'Dermatologic' },
    { name: 'Erythema Nodosum', category: 'Dermatologic' },
    { name: 'Erythema Multiforme', category: 'Dermatologic' },
    { name: 'Nikolsky Sign', category: 'Dermatologic' },
    { name: 'Auspitz Sign', category: 'Dermatologic' },
    { name: 'Koebner Phenomenon', category: 'Dermatologic' },
    { name: 'Dermatomal Distribution', category: 'Dermatologic' },
    { name: 'Pitting Edema', category: 'Dermatologic' },
    { name: 'Non-Pitting Edema', category: 'Dermatologic' },
    { name: 'Lymphadenopathy', category: 'Dermatologic' },
    { name: 'Spider Angiomata', category: 'Dermatologic' },
    { name: 'Palmar Erythema', category: 'Dermatologic' },
    { name: 'Acanthosis Nigricans', category: 'Dermatologic' },
    { name: 'Xanthomas', category: 'Dermatologic' },
    { name: 'Livedo Reticularis', category: 'Dermatologic' },

    // EENT FINDINGS
    { name: 'Tonsillar Exudate', category: 'EENT' },
    { name: 'Tonsillar Enlargement', category: 'EENT' },
    { name: 'Pharyngeal Erythema', category: 'EENT' },
    { name: 'Uvular Deviation', category: 'EENT' },
    { name: 'Tympanic Membrane Bulging', category: 'EENT' },
    { name: 'Tympanic Membrane Perforation', category: 'EENT' },
    { name: 'Hemotympanum', category: 'EENT' },
    { name: 'Rinne Test Abnormality', category: 'EENT' },
    { name: 'Weber Test Abnormality', category: 'EENT' },
    { name: 'Nasal Septal Deviation', category: 'EENT' },
    { name: 'Nasal Polyps', category: 'EENT' },
    { name: 'Epistaxis', category: 'EENT' },
    { name: 'Periorbital Edema', category: 'EENT' },
    { name: 'Proptosis', category: 'EENT' },
    { name: 'Lid Lag', category: 'EENT' },
    { name: 'Conjunctival Injection', category: 'EENT' },
    { name: 'Subconjunctival Hemorrhage', category: 'EENT' },
    { name: 'Photophobia', category: 'EENT' },
    { name: 'Cotton Wool Spots', category: 'EENT' },
    { name: 'Retinal Hemorrhages', category: 'EENT' },
    { name: 'Cherry Red Spot', category: 'EENT' },
    { name: 'Kayser-Fleischer Rings', category: 'EENT' },
    { name: 'Arcus Senilis', category: 'EENT' },

    // VASCULAR FINDINGS
    { name: 'Ankle Brachial Index Abnormality', category: 'Vascular' },
    { name: 'Capillary Refill Delay', category: 'Vascular' },
    { name: 'Homans Sign', category: 'Vascular' },
    { name: 'Venous Stasis Changes', category: 'Vascular' },
    { name: 'Varicose Veins', category: 'Vascular' },
    { name: 'Arterial Ulcer', category: 'Vascular' },
    { name: 'Venous Ulcer', category: 'Vascular' },
    { name: 'Temperature Asymmetry', category: 'Vascular' },

    // THYROID FINDINGS
    { name: 'Thyroid Nodule', category: 'Endocrine' },
    { name: 'Thyromegaly', category: 'Endocrine' },
    { name: 'Thyroid Bruit', category: 'Endocrine' },
    { name: 'Pretibial Myxedema', category: 'Endocrine' },

    // BREAST FINDINGS
    { name: 'Breast Mass', category: 'Breast' },
    { name: 'Nipple Discharge', category: 'Breast' },
    { name: 'Peau d Orange', category: 'Breast' },
    { name: 'Nipple Retraction', category: 'Breast' },

    // GENITOURINARY FINDINGS
    { name: 'CVA Tenderness', category: 'Genitourinary' },
    { name: 'Suprapubic Tenderness', category: 'Genitourinary' },
    { name: 'Distended Bladder', category: 'Genitourinary' },
    { name: 'Inguinal Hernia', category: 'Genitourinary' },
    { name: 'Femoral Hernia', category: 'Genitourinary' },
    { name: 'Testicular Mass', category: 'Genitourinary' },
    { name: 'Cremasteric Reflex Absent', category: 'Genitourinary' },
    { name: 'Prehn Sign', category: 'Genitourinary' },
    { name: 'Cervical Motion Tenderness', category: 'Genitourinary' },
    { name: 'Adnexal Tenderness', category: 'Genitourinary' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} physicalExamFinding records...\n`);

  const existing = await prisma.physicalExamFinding.findMany({
    select: { name: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.name.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generatePhysicalExamFinding(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      // Remove any relation fields that AI might have included
      const { FindingConditionLink, ...createData } = data as any;

      // Clean numeric fields - convert "Not applicable" or other strings to null
      const cleanNumeric = (val: any): number | null => {
        if (typeof val === 'number' && !isNaN(val)) return val;
        if (typeof val === 'string') {
          const num = parseFloat(val);
          if (!isNaN(num)) return num;
        }
        return null;
      };

      const cleanedData = {
        ...createData,
        negativeLR: cleanNumeric(createData.negativeLR),
        positiveLR: cleanNumeric(createData.positiveLR),
        sensitivity: cleanNumeric(createData.sensitivity),
        specificity: cleanNumeric(createData.specificity),
        panceYield: cleanNumeric(createData.panceYield) ?? 0,
      };

      await prisma.physicalExamFinding.create({
        data: {
          id: uuidv4(),
          ...cleanedData,
          updatedAt: new Date(),
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.physicalExamFinding.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
