/**
 * Procedure Generator
 * Auto-generated by create-generator.ts
 * 
 * Generates comprehensive procedure records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface ProcedureData {
  name: string;
  displayName: string;
  aliases: string[];
  category: string;
  type: string;
  system: string;
  description: string;
  panceYield: number;
  isHighYield: boolean;
  boardYieldFacts: string[];
  indications: string[];
  absoluteContraindications: string[];
  relativeContraindications: string[];
  preparation: string;
  equipment: string[];
  anatomicLandmarks: string[];
  technique: string;
  positioning: string;
  anesthesia: string;
  duration: string;
  complications: string[];
  complicationRates: any;
  emergencyManagement: string;
  safetyChecklist: string[];
  postProcedureCare: string;
  expectedFindings: string;
  abnormalFindings: string[];
  followUp: string;
  recovery: string;
  consentPoints: string[];
  documentationRequirements: string[];
  clinicalPearls: string[];
  commonMistakes: string[];
  testQuestionTips: string[];
  mnemonics: string[];
  videoUrl: string;
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "name": "value",
  "displayName": "value",
  "aliases": ["item1", "item2"],
  "category": "value",
  "type": "value",
  "system": "value",
  "description": "value",
  "panceYield": 0,
  "isHighYield": true,
  "boardYieldFacts": ["item1", "item2"],
  "indications": ["item1", "item2"],
  "absoluteContraindications": ["item1", "item2"],
  "relativeContraindications": ["item1", "item2"],
  "preparation": "value",
  "equipment": ["item1", "item2"],
  "anatomicLandmarks": ["item1", "item2"],
  "technique": "value",
  "positioning": "value",
  "anesthesia": "value",
  "duration": "value",
  "complications": ["item1", "item2"],
  "complicationRates": "value",
  "emergencyManagement": "value",
  "safetyChecklist": ["item1", "item2"],
  "postProcedureCare": "value",
  "expectedFindings": "value",
  "abnormalFindings": ["item1", "item2"],
  "followUp": "value",
  "recovery": "value",
  "consentPoints": ["item1", "item2"],
  "documentationRequirements": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "mnemonics": ["item1", "item2"],
  "videoUrl": "value",
  "ProcedureConditionLink": "value"
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateProcedure(item: { name: string; category: string }, retryCount = 0): Promise<ProcedureData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
  
  let prompt = PROMPT_TEMPLATE
    .replace('{{ITEM_NAME}}', item.name)
    .replace('{{CATEGORY}}', item.category);
  
  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for procedure: "${item.name}"
    
Return this structure with NO markdown:
{
  "name": "value",
  "displayName": "value",
  "aliases": ["item1", "item2"],
  "category": "value",
  "type": "value",
  "system": "value",
  "description": "value",
  "panceYield": 0,
  "isHighYield": true,
  "boardYieldFacts": ["item1", "item2"],
  "indications": ["item1", "item2"],
  "absoluteContraindications": ["item1", "item2"],
  "relativeContraindications": ["item1", "item2"],
  "preparation": "value",
  "equipment": ["item1", "item2"],
  "anatomicLandmarks": ["item1", "item2"],
  "technique": "value",
  "positioning": "value",
  "anesthesia": "value",
  "duration": "value",
  "complications": ["item1", "item2"],
  "complicationRates": "value",
  "emergencyManagement": "value",
  "safetyChecklist": ["item1", "item2"],
  "postProcedureCare": "value",
  "expectedFindings": "value",
  "abnormalFindings": ["item1", "item2"],
  "followUp": "value",
  "recovery": "value",
  "consentPoints": ["item1", "item2"],
  "documentationRequirements": ["item1", "item2"],
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"],
  "mnemonics": ["item1", "item2"],
  "videoUrl": "value",
  "ProcedureConditionLink": "value"
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }
  
  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();
    
    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');
    
    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
    
    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');
    
    let parsed: ProcedureData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);
      
      // Try fixing string values
      const fixed = jsonStr.replace(
        /"([^"]+)"\s*:\s*"([^"]*)"/g,
        (match, key, value) => {
          if (value.includes('"')) {
            return `"${key}": "${value.replace(/"/g, "'")}"`;
          }
          return match;
        }
      );
      
      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise(resolve => setTimeout(resolve, 1000));
          return generateProcedure(item, 1);
        }
        throw parseError;
      }
    }
    
    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise(resolve => setTimeout(resolve, 1000));
      return generateProcedure(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.procedure.findMany({
    select: { id: true, name: true, createdAt: true }
  });
  
  const toDelete: string[] = [];
  const seen = new Map<string, typeof all[0]>();
  
  for (const item of all) {
    const key = item.name.toLowerCase().trim();
    const existing = seen.get(key);
    
    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.name}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.name}"`);
      }
    } else {
      seen.set(key, item);
    }
  }
  
  if (toDelete.length > 0) {
    await prisma.procedure.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 Procedure Generator');
  console.log('='.repeat(60));
  
  await removeDuplicates();
  
  const ITEMS_TO_GENERATE = [
    // Critical Care / Emergency Procedures
    { name: 'Central Line Placement', category: 'Critical Care' },
    { name: 'Arterial Line Placement', category: 'Critical Care' },
    { name: 'Endotracheal Intubation', category: 'Critical Care' },
    { name: 'Emergency Cricothyrotomy', category: 'Emergency' },
    { name: 'Needle Decompression', category: 'Emergency' },
    { name: 'Cardioversion', category: 'Emergency' },
    { name: 'Defibrillation', category: 'Emergency' },
    { name: 'Pericardiocentesis', category: 'Emergency' },
    { name: 'Bag-Valve-Mask Ventilation', category: 'Emergency' },
    { name: 'Laryngeal Mask Airway Insertion', category: 'Emergency' },
    
    // Diagnostic Procedures
    { name: 'Lumbar Puncture', category: 'Diagnostic' },
    { name: 'Joint Aspiration', category: 'Diagnostic' },
    { name: 'Knee Arthrocentesis', category: 'Diagnostic' },
    { name: 'Thoracentesis', category: 'Diagnostic' },
    { name: 'Paracentesis', category: 'Diagnostic' },
    { name: 'Bladder Catheterization', category: 'Diagnostic' },
    { name: 'Nasogastric Tube Insertion', category: 'Diagnostic' },
    { name: 'Bone Marrow Aspiration', category: 'Diagnostic' },
    { name: 'Skin Biopsy', category: 'Diagnostic' },
    
    // Therapeutic Procedures
    { name: 'Chest Tube Insertion', category: 'Therapeutic' },
    { name: 'Incision and Drainage', category: 'Therapeutic' },
    { name: 'Wound Closure (Suturing)', category: 'Therapeutic' },
    { name: 'Laceration Repair', category: 'Therapeutic' },
    { name: 'Joint Injection', category: 'Therapeutic' },
    { name: 'Trigger Point Injection', category: 'Therapeutic' },
    { name: 'Corticosteroid Injection', category: 'Therapeutic' },
    { name: 'Closed Reduction of Fracture', category: 'Therapeutic' },
    { name: 'Splinting', category: 'Therapeutic' },
    { name: 'Casting', category: 'Therapeutic' },
    { name: 'Nail Removal', category: 'Therapeutic' },
    { name: 'Foreign Body Removal (Eye)', category: 'Therapeutic' },
    { name: 'Foreign Body Removal (Skin)', category: 'Therapeutic' },
    { name: 'Cerumen Removal', category: 'Therapeutic' },
    { name: 'Epistaxis Management', category: 'Therapeutic' },
    { name: 'Anterior Nasal Packing', category: 'Therapeutic' },
    
    // GI/GU Procedures
    { name: 'Foley Catheter Insertion', category: 'GI/GU' },
    { name: 'Suprapubic Catheter Insertion', category: 'GI/GU' },
    { name: 'Digital Rectal Exam', category: 'GI/GU' },
    { name: 'Fecal Disimpaction', category: 'GI/GU' },
    { name: 'Hemorrhoid Banding', category: 'GI/GU' },
    { name: 'Anoscopy', category: 'GI/GU' },
    
    // Dermatologic Procedures
    { name: 'Cryotherapy', category: 'Dermatology' },
    { name: 'Electrocautery', category: 'Dermatology' },
    { name: 'Shave Biopsy', category: 'Dermatology' },
    { name: 'Punch Biopsy', category: 'Dermatology' },
    { name: 'Excisional Biopsy', category: 'Dermatology' },
    { name: 'Wound Debridement', category: 'Dermatology' },
    { name: 'Abscess Drainage', category: 'Dermatology' },
    
    // Orthopedic Procedures
    { name: 'Shoulder Reduction', category: 'Orthopedics' },
    { name: 'Hip Dislocation Reduction', category: 'Orthopedics' },
    { name: 'Finger Dislocation Reduction', category: 'Orthopedics' },
    { name: 'Patella Dislocation Reduction', category: 'Orthopedics' },
    { name: 'Nursemaids Elbow Reduction', category: 'Orthopedics' },
    { name: 'Ankle Fracture Reduction', category: 'Orthopedics' },
    { name: 'Colles Fracture Reduction', category: 'Orthopedics' },
    
    // OB/GYN Procedures
    { name: 'Pap Smear', category: 'OB/GYN' },
    { name: 'Pelvic Exam', category: 'OB/GYN' },
    { name: 'IUD Insertion', category: 'OB/GYN' },
    { name: 'Endometrial Biopsy', category: 'OB/GYN' },
    { name: 'Bartholin Cyst Drainage', category: 'OB/GYN' },
    { name: 'Colposcopy', category: 'OB/GYN' },
    
    // Ophthalmologic Procedures
    { name: 'Slit Lamp Examination', category: 'Ophthalmology' },
    { name: 'Tonometry', category: 'Ophthalmology' },
    { name: 'Fluorescein Staining', category: 'Ophthalmology' },
    { name: 'Eye Irrigation', category: 'Ophthalmology' },
    { name: 'Eyelid Eversion', category: 'Ophthalmology' },
    
    // ENT Procedures  
    { name: 'Ear Lavage', category: 'ENT' },
    { name: 'Tympanometry', category: 'ENT' },
    { name: 'Laryngoscopy', category: 'ENT' },
    { name: 'Nasal Cauterization', category: 'ENT' },
    
    // Pediatric Procedures
    { name: 'Venipuncture', category: 'Pediatrics' },
    { name: 'Heel Stick', category: 'Pediatrics' },
    { name: 'Peripheral IV Insertion', category: 'Pediatrics' },
    { name: 'Umbilical Catheterization', category: 'Pediatrics' },
    
    // Pulmonary Procedures
    { name: 'Peak Flow Measurement', category: 'Pulmonary' },
    { name: 'Spirometry', category: 'Pulmonary' },
    { name: 'Nebulizer Treatment', category: 'Pulmonary' },
    { name: 'Bronchoscopy', category: 'Pulmonary' },
    
    // Cardiovascular Procedures
    { name: 'ECG/EKG Interpretation', category: 'Cardiovascular' },
    { name: 'Transesophageal Echo', category: 'Cardiovascular' },
    { name: 'Stress Testing', category: 'Cardiovascular' },
    { name: 'Holter Monitor Placement', category: 'Cardiovascular' },
    
    // === ADDITIONAL COMPREHENSIVE PANCE PROCEDURES ===
    
    // Additional Emergency/Critical Care
    { name: 'CPR (Basic Life Support)', category: 'Emergency' },
    { name: 'Advanced Cardiac Life Support (ACLS)', category: 'Emergency' },
    { name: 'Rapid Sequence Intubation', category: 'Emergency' },
    { name: 'Oropharyngeal Airway Insertion', category: 'Emergency' },
    { name: 'Nasopharyngeal Airway Insertion', category: 'Emergency' },
    { name: 'Emergency Tracheostomy Care', category: 'Emergency' },
    { name: 'IO (Intraosseous) Access', category: 'Emergency' },
    { name: 'Transcutaneous Pacing', category: 'Emergency' },
    { name: 'Synchronized Cardioversion', category: 'Emergency' },
    { name: 'Heimlich Maneuver', category: 'Emergency' },
    
    // Additional Diagnostic
    { name: 'Arterial Blood Gas Sampling', category: 'Diagnostic' },
    { name: 'Capillary Blood Glucose', category: 'Diagnostic' },
    { name: 'Urinalysis (Dipstick)', category: 'Diagnostic' },
    { name: 'Urine Culture Collection', category: 'Diagnostic' },
    { name: 'Wound Culture', category: 'Diagnostic' },
    { name: 'Throat Culture', category: 'Diagnostic' },
    { name: 'Stool Sample Collection', category: 'Diagnostic' },
    { name: 'CSF Analysis Interpretation', category: 'Diagnostic' },
    { name: 'Ascitic Fluid Analysis', category: 'Diagnostic' },
    { name: 'Pleural Fluid Analysis', category: 'Diagnostic' },
    { name: 'Synovial Fluid Analysis', category: 'Diagnostic' },
    
    // Additional Therapeutic
    { name: 'Peripheral IV Insertion', category: 'Therapeutic' },
    { name: 'Blood Transfusion', category: 'Therapeutic' },
    { name: 'Intramuscular Injection', category: 'Therapeutic' },
    { name: 'Subcutaneous Injection', category: 'Therapeutic' },
    { name: 'Intradermal Injection', category: 'Therapeutic' },
    { name: 'Staple Removal', category: 'Therapeutic' },
    { name: 'Suture Removal', category: 'Therapeutic' },
    { name: 'Wound Irrigation', category: 'Therapeutic' },
    { name: 'Negative Pressure Wound Therapy', category: 'Therapeutic' },
    { name: 'Skin Grafting (Basic)', category: 'Therapeutic' },
    { name: 'Local Anesthesia Administration', category: 'Therapeutic' },
    { name: 'Digital Block', category: 'Therapeutic' },
    { name: 'Ring Block', category: 'Therapeutic' },
    { name: 'Field Block', category: 'Therapeutic' },
    { name: 'Hematoma Block', category: 'Therapeutic' },
    
    // Additional Orthopedic
    { name: 'Sugar Tong Splint', category: 'Orthopedics' },
    { name: 'Thumb Spica Splint', category: 'Orthopedics' },
    { name: 'Ulnar Gutter Splint', category: 'Orthopedics' },
    { name: 'Posterior Leg Splint', category: 'Orthopedics' },
    { name: 'Knee Immobilizer Application', category: 'Orthopedics' },
    { name: 'Sling Application', category: 'Orthopedics' },
    { name: 'Figure-of-Eight Clavicle Strap', category: 'Orthopedics' },
    { name: 'Buddy Taping', category: 'Orthopedics' },
    { name: 'Elbow Dislocation Reduction', category: 'Orthopedics' },
    { name: 'Boxer Fracture Reduction', category: 'Orthopedics' },
    { name: 'Mallet Finger Splinting', category: 'Orthopedics' },
    { name: 'Traction Application', category: 'Orthopedics' },
    
    // Additional GI/GU
    { name: 'Rectal Exam', category: 'GI/GU' },
    { name: 'Guaiac Stool Test', category: 'GI/GU' },
    { name: 'Nasogastric Tube Irrigation', category: 'GI/GU' },
    { name: 'Enema Administration', category: 'GI/GU' },
    { name: 'Straight Catheterization', category: 'GI/GU' },
    { name: 'Post-Void Residual Measurement', category: 'GI/GU' },
    
    // Additional Dermatology
    { name: 'Dermoscopy', category: 'Dermatology' },
    { name: 'KOH Preparation', category: 'Dermatology' },
    { name: 'Tzanck Smear', category: 'Dermatology' },
    { name: 'Skin Scraping for Scabies', category: 'Dermatology' },
    { name: 'Wood Lamp Examination', category: 'Dermatology' },
    { name: 'Mohs Surgery Wound Care', category: 'Dermatology' },
    { name: 'Curettage', category: 'Dermatology' },
    { name: 'Lipoma Excision', category: 'Dermatology' },
    { name: 'Sebaceous Cyst Excision', category: 'Dermatology' },
    
    // Additional OB/GYN
    { name: 'Wet Mount Preparation', category: 'OB/GYN' },
    { name: 'KOH Vaginal Prep', category: 'OB/GYN' },
    { name: 'Cervical Culture', category: 'OB/GYN' },
    { name: 'Fetal Heart Tone Assessment', category: 'OB/GYN' },
    { name: 'Leopold Maneuvers', category: 'OB/GYN' },
    { name: 'Cervical Dilation Assessment', category: 'OB/GYN' },
    { name: 'IUD Removal', category: 'OB/GYN' },
    { name: 'Nexplanon Insertion', category: 'OB/GYN' },
    { name: 'Nexplanon Removal', category: 'OB/GYN' },
    
    // Additional Ophthalmology
    { name: 'Visual Acuity Testing', category: 'Ophthalmology' },
    { name: 'Pupillary Response Assessment', category: 'Ophthalmology' },
    { name: 'Confrontation Visual Fields', category: 'Ophthalmology' },
    { name: 'Cover-Uncover Test', category: 'Ophthalmology' },
    { name: 'Eye Patch Application', category: 'Ophthalmology' },
    { name: 'Contact Lens Removal', category: 'Ophthalmology' },
    
    // Additional ENT
    { name: 'Nasal Speculum Exam', category: 'ENT' },
    { name: 'Posterior Nasal Packing', category: 'ENT' },
    { name: 'Myringotomy', category: 'ENT' },
    { name: 'Foreign Body Removal (Ear)', category: 'ENT' },
    { name: 'Foreign Body Removal (Nose)', category: 'ENT' },
    { name: 'Peritonsillar Abscess Drainage', category: 'ENT' },
    { name: 'Indirect Laryngoscopy', category: 'ENT' },
    
    // Neurological Procedures
    { name: 'Fundoscopic Exam', category: 'Neurology' },
    { name: 'Cranial Nerve Examination', category: 'Neurology' },
    { name: 'Motor Strength Testing', category: 'Neurology' },
    { name: 'Deep Tendon Reflex Testing', category: 'Neurology' },
    { name: 'Sensory Examination', category: 'Neurology' },
    { name: 'Gait Assessment', category: 'Neurology' },
    { name: 'Mini-Mental Status Exam', category: 'Neurology' },
    { name: 'Glasgow Coma Scale Assessment', category: 'Neurology' },
    
    // Pulmonary Additional
    { name: 'Incentive Spirometry', category: 'Pulmonary' },
    { name: 'Pulse Oximetry', category: 'Pulmonary' },
    { name: 'Oxygen Therapy Setup', category: 'Pulmonary' },
    { name: 'BiPAP/CPAP Setup', category: 'Pulmonary' },
    { name: 'Chest Physiotherapy', category: 'Pulmonary' },
    { name: 'Sputum Induction', category: 'Pulmonary' },
    
    // Cardiovascular Additional
    { name: 'Blood Pressure Measurement', category: 'Cardiovascular' },
    { name: 'Orthostatic Vital Signs', category: 'Cardiovascular' },
    { name: 'Ankle-Brachial Index', category: 'Cardiovascular' },
    { name: 'Event Monitor Placement', category: 'Cardiovascular' },
    
    // Pediatric Additional
    { name: 'Newborn Resuscitation', category: 'Pediatrics' },
    { name: 'Infant Lumbar Puncture', category: 'Pediatrics' },
    { name: 'Suprapubic Aspiration (Pediatric)', category: 'Pediatrics' },
    { name: 'Developmental Screening', category: 'Pediatrics' },
    { name: 'Growth Assessment', category: 'Pediatrics' },
    
    // Psychiatric
    { name: 'Suicide Risk Assessment', category: 'Psychiatry' },
    { name: 'Mental Status Examination', category: 'Psychiatry' },
    { name: 'PHQ-9 Administration', category: 'Psychiatry' },
    { name: 'GAD-7 Administration', category: 'Psychiatry' },
    { name: 'CAGE Questionnaire', category: 'Psychiatry' },
    { name: 'AUDIT-C Screening', category: 'Psychiatry' }
  ];
  
  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} procedure records...\n`);
  
  const existing = await prisma.procedure.findMany({ 
    select: { name: true, id: true } 
  });
  const existingNames = new Set(existing.map(e => e.name.toLowerCase()));
  
  let created = 0;
  let skipped = 0;
  let failed = 0;
  
  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }
    
    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateProcedure(item);
    
    if (!data) {
      failed++;
      continue;
    }
    
    try {
      // Remove relation fields before creating
      const { ProcedureConditionLink, Condition, ...createData } = data as any;
      
      await prisma.procedure.create({
        data: {
          id: crypto.randomUUID(),
          ...createData,
          updatedAt: new Date()
        }
      });
      
      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }
    
    await new Promise(resolve => setTimeout(resolve, 800));
  }
  
  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);
  
  const total = await prisma.procedure.count();
  console.log(`   Total in database: ${total}`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
