/**
 * VitalSignRange Generator
 * Auto-generated by create-generator.ts
 *
 * Generates comprehensive vitalSignRange records with AI assistance
 */

import { PrismaClient } from '@prisma/client';
import { GoogleGenerativeAI } from '@google/generative-ai';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

interface VitalSignRangeData {
  vitalSign: string;
  displayName: string;
  category: string;
  normalRange: string;
  ranges: any;
  units: string;
  elevation: any;
  depression: any;
  emergencyValues: any;
  associatedConditions: any;
  clinicalPearls: string[];
  commonMistakes: string[];
  testQuestionTips: string[];
}

const PROMPT_TEMPLATE = `You are a medical education expert creating content for PA students.

Generate comprehensive data for: "{{ITEM_NAME}}"
Category: {{CATEGORY}}

Create detailed, accurate content with this JSON structure:

{
  "vitalSign": "value",
  "displayName": "value",
  "category": "value",
  "normalRange": "value",
  "ranges": "value",
  "units": "value",
  "elevation": "value",
  "depression": "value",
  "emergencyValues": "value",
  "associatedConditions": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"]
}

CRITICAL JSON RULES:
- Return ONLY valid JSON with NO markdown formatting
- Use straight apostrophes (') never curly quotes
- Write "greater than" not ">" symbol
- NO special characters: ≥ ≤ × ÷ → ∞
- NO double quotes inside string values
- NO null values - use empty arrays [] or "Not applicable"
- Remove ALL trailing commas
- All text fields should have meaningful medical content

Return the JSON now:`;

async function generateVitalSignRange(
  item: { name: string; category: string },
  retryCount = 0
): Promise<VitalSignRangeData | null> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

  let prompt = PROMPT_TEMPLATE.replace('{{ITEM_NAME}}', item.name).replace(
    '{{CATEGORY}}',
    item.category
  );

  // Simplified retry prompt
  if (retryCount > 0) {
    prompt = `Generate valid JSON for vitalSignRange: "${item.name}"
    
Return this structure with NO markdown:
{
  "vitalSign": "value",
  "displayName": "value",
  "category": "value",
  "normalRange": "value",
  "ranges": "value",
  "units": "value",
  "elevation": "value",
  "depression": "value",
  "emergencyValues": "value",
  "associatedConditions": "value",
  "clinicalPearls": ["item1", "item2"],
  "commonMistakes": ["item1", "item2"],
  "testQuestionTips": ["item1", "item2"]
}

Rules: Use apostrophes not quotes, spell out symbols, no null values`;
  }

  try {
    const result = await model.generateContent(prompt);
    let jsonStr = result.response.text().trim();

    // Clean up response
    jsonStr = jsonStr
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/, '')
      .replace(/```\s*$/, '')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n');

    const firstBrace = jsonStr.indexOf('{');
    const lastBrace = jsonStr.lastIndexOf('}');
    if (firstBrace === -1 || lastBrace === -1) {
      throw new Error('No JSON found');
    }
    jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);

    // Fix common issues
    jsonStr = jsonStr
      .replace(/≥/g, ' greater than or equal to ')
      .replace(/≤/g, ' less than or equal to ')
      .replace(/>/g, ' greater than ')
      .replace(/</g, ' less than ')
      .replace(/['']/g, "'")
      .replace(/[""]/g, '"')
      .replace(/,(\s*[}\]])/g, '$1');

    let parsed: VitalSignRangeData;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (parseError) {
      console.error(`  ⚠️  JSON parse error: ${parseError}`);

      // Try fixing string values
      const fixed = jsonStr.replace(/"([^"]+)"\s*:\s*"([^"]*)"/g, (match, key, value) => {
        if (value.includes('"')) {
          return `"${key}": "${value.replace(/"/g, "'")}"`;
        }
        return match;
      });

      try {
        parsed = JSON.parse(fixed);
        console.log(`  ℹ️  JSON fixed automatically`);
      } catch {
        if (retryCount === 0) {
          console.log(`  🔄 Retrying with simplified prompt...`);
          await new Promise((resolve) => setTimeout(resolve, 1000));
          return generateVitalSignRange(item, 1);
        }
        throw parseError;
      }
    }

    return parsed;
  } catch (error) {
    console.error(`  ❌ Error: ${error}`);
    if (retryCount === 0) {
      console.log(`  🔄 Retrying...`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return generateVitalSignRange(item, 1);
    }
    return null;
  }
}

async function removeDuplicates() {
  console.log('\n🔍 Checking for duplicates...');
  const all = await prisma.vitalSignRange.findMany({
    select: { id: true, vitalSign: true, createdAt: true },
  });

  const toDelete: string[] = [];
  const seen = new Map<string, (typeof all)[0]>();

  for (const item of all) {
    const key = item.vitalSign.toLowerCase().trim();
    const existing = seen.get(key);

    if (existing) {
      if (item.createdAt > existing.createdAt) {
        toDelete.push(item.id);
        console.log(`  🗑️  Duplicate: "${item.vitalSign}"`);
      } else {
        toDelete.push(existing.id);
        seen.set(key, item);
        console.log(`  🗑️  Duplicate: "${existing.vitalSign}"`);
      }
    } else {
      seen.set(key, item);
    }
  }

  if (toDelete.length > 0) {
    await prisma.vitalSignRange.deleteMany({ where: { id: { in: toDelete } } });
    console.log(`  ✅ Removed ${toDelete.length} duplicate(s)`);
  } else {
    console.log(`  ✅ No duplicates found`);
  }
}

async function main() {
  console.log('🏥 VitalSignRange Generator');
  console.log('='.repeat(60));

  await removeDuplicates();

  const ITEMS_TO_GENERATE = [
    // Core Vital Signs
    { name: 'Heart Rate', category: 'Cardiovascular' },
    { name: 'Blood Pressure - Systolic', category: 'Cardiovascular' },
    { name: 'Blood Pressure - Diastolic', category: 'Cardiovascular' },
    { name: 'Mean Arterial Pressure', category: 'Cardiovascular' },
    { name: 'Pulse Pressure', category: 'Cardiovascular' },
    { name: 'Respiratory Rate', category: 'Pulmonary' },
    { name: 'Temperature - Oral', category: 'General' },
    { name: 'Temperature - Rectal', category: 'General' },
    { name: 'Temperature - Axillary', category: 'General' },
    { name: 'Temperature - Tympanic', category: 'General' },
    { name: 'Oxygen Saturation (SpO2)', category: 'Pulmonary' },

    // Advanced Cardiovascular
    { name: 'Central Venous Pressure', category: 'Cardiovascular' },
    { name: 'Jugular Venous Pressure', category: 'Cardiovascular' },
    { name: 'Cardiac Output', category: 'Cardiovascular' },
    { name: 'Cardiac Index', category: 'Cardiovascular' },
    { name: 'Systemic Vascular Resistance', category: 'Cardiovascular' },
    { name: 'Pulmonary Artery Pressure', category: 'Cardiovascular' },
    { name: 'Pulmonary Capillary Wedge Pressure', category: 'Cardiovascular' },

    // Respiratory
    { name: 'Peak Expiratory Flow Rate', category: 'Pulmonary' },
    { name: 'FEV1', category: 'Pulmonary' },
    { name: 'FVC', category: 'Pulmonary' },
    { name: 'FEV1/FVC Ratio', category: 'Pulmonary' },
    { name: 'Tidal Volume', category: 'Pulmonary' },
    { name: 'Minute Ventilation', category: 'Pulmonary' },
    { name: 'End-Tidal CO2', category: 'Pulmonary' },

    // Neurological
    { name: 'Glasgow Coma Scale', category: 'Neurological' },
    { name: 'Pupil Size', category: 'Neurological' },
    { name: 'Intracranial Pressure', category: 'Neurological' },
    { name: 'Cerebral Perfusion Pressure', category: 'Neurological' },

    // Pediatric-Specific
    { name: 'Heart Rate - Newborn', category: 'Pediatric' },
    { name: 'Heart Rate - Infant', category: 'Pediatric' },
    { name: 'Heart Rate - Child', category: 'Pediatric' },
    { name: 'Respiratory Rate - Newborn', category: 'Pediatric' },
    { name: 'Respiratory Rate - Infant', category: 'Pediatric' },
    { name: 'Respiratory Rate - Child', category: 'Pediatric' },
    { name: 'Blood Pressure - Pediatric', category: 'Pediatric' },
    { name: 'Capillary Refill Time', category: 'Pediatric' },
    { name: 'APGAR Score', category: 'Pediatric' },

    // Pregnancy-Specific
    { name: 'Fetal Heart Rate', category: 'Obstetric' },
    { name: 'Uterine Contraction Frequency', category: 'Obstetric' },
    { name: 'Bishop Score', category: 'Obstetric' },

    // Metabolic
    { name: 'Blood Glucose', category: 'Metabolic' },
    { name: 'Body Mass Index', category: 'Metabolic' },
    { name: 'Waist Circumference', category: 'Metabolic' },

    // Pain
    { name: 'Pain Scale (0-10)', category: 'Pain' },
    { name: 'Wong-Baker FACES Scale', category: 'Pain' },

    // Orthostatic
    { name: 'Orthostatic Blood Pressure', category: 'Cardiovascular' },
    { name: 'Orthostatic Heart Rate', category: 'Cardiovascular' },
  ];

  console.log(`\nGenerating ${ITEMS_TO_GENERATE.length} vitalSignRange records...\n`);

  const existing = await prisma.vitalSignRange.findMany({
    select: { vitalSign: true, id: true },
  });
  const existingNames = new Set(existing.map((e) => e.vitalSign.toLowerCase()));

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of ITEMS_TO_GENERATE) {
    if (existingNames.has(item.name.toLowerCase())) {
      console.log(`  ⏭️  Skipped: ${item.name}`);
      skipped++;
      continue;
    }

    console.log(`  🔄 Creating: ${item.name}...`);
    const data = await generateVitalSignRange(item);

    if (!data) {
      failed++;
      continue;
    }

    try {
      await prisma.vitalSignRange.create({
        data: {
          id: crypto.randomUUID(),
          ...data,
          updatedAt: new Date(),
        },
      });

      existingNames.add(item.name.toLowerCase());
      created++;
      console.log(`  ✅ Created: ${item.name}`);
    } catch (error) {
      console.error(`  ❌ Failed to save: ${error}`);
      failed++;
    }

    await new Promise((resolve) => setTimeout(resolve, 800));
  }

  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Failed: ${failed}`);

  const total = await prisma.vitalSignRange.count();
  console.log(`   Total in database: ${total}`);

  await prisma.$disconnect();
}

main().catch(console.error);
