/**
 * OSCE Suggestion Service
 * 
 * Suggests relevant OSCE/patient encounter cases based on clinical content
 * generated by the Hybrid Content Engine.
 */

import { DEFAULT_OSCE_CONFIG } from '@/config/osce-settings';
import type { OSCEConfiguration } from '@/types';

/**
 * Options for OSCE case suggestion
 */
export interface OSCESuggestionOptions {
  system?: string;
  difficulty?: string;
  conditionId?: string;
  enableVoiceMode?: boolean;
  culturalCompetency?: boolean;
  resourceLimited?: boolean;
}

/**
 * Suggested OSCE case
 */
export interface OSCESuggestion {
  caseId: string;
  chiefComplaint: string;
  system: string;
  difficulty: string;
  relevanceScore: number;
  culturalCompetency?: boolean;
  voiceModeSupported?: boolean;
}

/**
 * Suggest an OSCE case based on clinical content and user configuration.
 * 
 * @param prisma - Prisma client
 * @param options - Suggestion options
 * @returns Suggested OSCE case or null if none found
 */
export async function suggestOSCECase(
  prisma: any,
  options: OSCESuggestionOptions = {}
): Promise<OSCESuggestion | null> {
  const {
    system,
    difficulty = 'medium',
    conditionId,
    enableVoiceMode = DEFAULT_OSCE_CONFIG.enableVoiceMode,
    culturalCompetency = DEFAULT_OSCE_CONFIG.culturalCompetency,
    resourceLimited = DEFAULT_OSCE_CONFIG.resourceLimited,
  } = options;

  // Build where clause for Prisma query
  const where: any = {};
  if (system) {
    // We need to map system to conditionId or use chiefComplaint/diagnosis.
    // For now, we'll rely on conditionId if provided.
    // If conditionId is not provided, we can try to match by system using the
    // inferSystemFromCase logic (which is not trivial). As a fallback, we'll
    // query all cases and filter later.
  }
  if (conditionId) {
    where.conditionId = conditionId;
  }

  try {
    // Fetch up to 10 candidate cases (random order for variety)
    const candidates = await prisma.patientEncounterCase.findMany({
      where,
      take: 10,
      select: {
        id: true,
        chiefComplaint: true,
        correctDiagnosis: true,
        conditionId: true,
        // Add any fields that indicate cultural competency or voice support
      },
    });

    if (candidates.length === 0) {
      return null;
    }

    // Score each candidate based on relevance
    const scored = candidates.map((candidate: any) => {
      let score = 0.0;

      // System match (if system provided)
      if (system) {
        // Infer system from chiefComplaint or diagnosis (simplistic)
        const candidateSystem = inferSystemFromCase(candidate.chiefComplaint, candidate.correctDiagnosis);
        if (candidateSystem.toLowerCase().includes(system.toLowerCase())) {
          score += 2.0;
        }
      }

      // Difficulty match (hardcoded mapping)
      // In a real implementation, we would have difficulty stored on the case.
      // For now, we'll assume difficulty is not stored; ignore.

      // Cultural competency preference
      if (culturalCompetency) {
        // Check if this case is tagged as cultural competency scenario
        const isCultural = isCulturalCompetencyCase(candidate);
        if (isCultural) score += 1.5;
      }

      // Voice mode preference (if enabled)
      if (enableVoiceMode) {
        // Cases with structured dialogue might be better for voice.
        // For simplicity, we'll assume all cases support voice.
        score += 0.5;
      }

      // Resource‑limited setting (if enabled, prefer cases that work with limited resources)
      if (resourceLimited) {
        // We could filter out cases that require advanced imaging, but for now skip.
      }

      return {
        candidate,
        score,
      };
    });

    // Pick the highest‑scoring candidate
    type ScoredCandidate = { candidate: any; score: number };
    const best = scored.reduce((prev: ScoredCandidate, curr: ScoredCandidate) =>
      curr.score > prev.score ? curr : prev
    );
    if (best.score < 0.1) {
      // No meaningful match; return null to avoid low‑quality suggestions
      return null;
    }

    const caseData = best.candidate;
    return {
      caseId: caseData.id,
      chiefComplaint: caseData.chiefComplaint,
      system: inferSystemFromCase(caseData.chiefComplaint, caseData.correctDiagnosis),
      difficulty: 'medium', // placeholder
      relevanceScore: best.score,
      culturalCompetency: culturalCompetency,
      voiceModeSupported: enableVoiceMode,
    };
  } catch (error) {
    console.warn('[OSCESuggestion] Failed to query OSCE cases:', error);
    return null;
  }
}

/**
 * Infer organ system from chief complaint and diagnosis.
 * Simplified implementation; in production this would use NLP or a mapping table.
 */
function inferSystemFromCase(chiefComplaint: string, diagnosis: string): string {
  const text = (chiefComplaint + ' ' + diagnosis).toLowerCase();
  if (text.includes('chest pain') || text.includes('heart') || text.includes('cardiac') || text.includes('mi')) {
    return 'Cardiovascular';
  }
  if (text.includes('shortness of breath') || text.includes('copd') || text.includes('asthma') || text.includes('pneumonia')) {
    return 'Pulmonary';
  }
  if (text.includes('abdominal pain') || text.includes('gi') || text.includes('liver') || text.includes('gall')) {
    return 'Gastrointestinal';
  }
  if (text.includes('joint') || text.includes('fracture') || text.includes('arthritis') || text.includes('muscle')) {
    return 'Musculoskeletal';
  }
  if (text.includes('headache') || text.includes('stroke') || text.includes('neuro')) {
    return 'Neurological';
  }
  if (text.includes('kidney') || text.includes('renal') || text.includes('uti')) {
    return 'Renal';
  }
  return 'General';
}

/**
 * Determine if a case is a cultural competency scenario.
 * Could be based on tags, chief complaint, or a dedicated flag.
 */
function isCulturalCompetencyCase(caseData: any): boolean {
  // For now, check if chief complaint contains keywords related to cultural scenarios
  const cc = caseData.chiefComplaint.toLowerCase();
  return (
    cc.includes('religious') ||
    cc.includes('cultural') ||
    cc.includes('belief') ||
    cc.includes('ethnic') ||
    cc.includes('transgender') ||
    cc.includes('immigrant')
  );
}