export const clinicalConsoleDemoData = {
  student: {
    fallbackName: 'PA-S',
    role: 'PA-S clinical year',
    goal: 'PANCE + Emergency Medicine EOR readiness',
  },
  todayPrescription: {
    focus: 'Cardiology readiness',
    task: 'Review diuretics in acute decompensated heart failure',
    durationLabel: '24 min prescription',
    reason: 'Missed loop diuretic adverse-effect questions twice this week.',
    followUp: '12 targeted questions + 8 flashcards',
  },
  readinessSnapshot: {
    panceReadiness: '68%',
    eorReadiness: '72%',
    retention: '77%',
  },
  reviewQueue: {
    flashcardsDue: 246,
    retention: '77%',
    questionAccuracy: '64%',
    weakTopicCount: 7,
    nextFocus: 'Diuretics in acute decompensated heart failure',
    queueWindow: '24 minute queue',
    reviewMix: [
      {
        label: 'Loop diuretic adverse effects',
        detail: 'Cardiology and renal crossover, missed twice this week',
        count: 8,
      },
      {
        label: 'Hyponatremia triage',
        detail: 'Electrolyte interpretation and treatment threshold recall',
        count: 6,
      },
      {
        label: 'COPD exacerbation antibiotics',
        detail: 'Guideline recall after missed first-line therapy items',
        count: 5,
      },
    ],
    guardrails: [
      'Review only due and weak-area items before starting a new block.',
      'Use confidence notes after misses so analytics can rank the next intervention.',
      'Return to Practice when the review queue is under 20 items.',
    ],
  },
  studyPathPreview: {
    cadence: '6 day route',
    totalStudyTime: '5.6h',
    retentionLift: '+8.4%',
    fatigueRisk: 'Moderate',
    coverage: 'Cardiology / Pulm / Renal',
    rationale:
      'Prioritizes repeated miss patterns before opening new blueprint territory. Review work stays earlier in the week, then clinical cases test transfer under timing pressure.',
    sessions: [
      {
        day: 'Day 1',
        label: 'Cardiology repair block',
        duration: '54 min',
        action: 'Review + questions',
        topics: [
          'Loop diuretic adverse effects',
          'Acute decompensated HF management',
          'Hypokalemia risk checks',
        ],
      },
      {
        day: 'Day 2',
        label: 'Renal/electrolyte calibration',
        duration: '42 min',
        action: 'Calibrate',
        topics: [
          'Hyponatremia triage',
          'Serum osmolality interpretation',
          'Volume status clues',
        ],
      },
      {
        day: 'Day 4',
        label: 'Pulmonary transfer drill',
        duration: '48 min',
        action: 'Clinical cases',
        topics: [
          'COPD exacerbation antibiotics',
          'Asthma severity thresholds',
          'Pneumonia disposition',
        ],
      },
      {
        day: 'Day 6',
        label: 'Mixed readiness check',
        duration: '72 min',
        action: 'Timed block',
        topics: [
          'Cardio-pulm mixed set',
          'Missed-item flashcards',
          'Confidence note review',
        ],
      },
    ],
    guardrails: [
      'Keep new content behind due review work until retention clears 80%.',
      'Move hard clinical cases earlier in the day when timing accuracy is stronger.',
      'Stop after two consecutive low-confidence misses and repair the concept first.',
    ],
  },
  knowledgePreview: {
    conditions: [
      {
        title: 'Acute decompensated heart failure',
        label: 'Condition script',
        detail: 'Dyspnea, volume overload, BNP support, pulmonary edema pattern, and loop diuretic response.',
        bullets: [
          'Check oxygenation, volume status, renal function, and potassium before escalating therapy.',
          'Repair miss patterns around diuretic adverse effects and post-treatment electrolyte drift.',
          'Return to a timed cardiology block after the illness script is stable.',
        ],
      },
      {
        title: 'Hyponatremia triage',
        label: 'Lab-linked diagnosis',
        detail: 'Serum osmolality, urine osmolality, volume exam, and neurologic severity guide next step.',
        bullets: [
          'Separate hypotonic from pseudo-hyponatremia before choosing treatment.',
          'Use symptom severity and chronicity to avoid overcorrection traps.',
          'Pair with renal and endocrine practice stems for transfer.',
        ],
      },
      {
        title: 'COPD exacerbation',
        label: 'Pulmonary repair',
        detail: 'Sputum change, oxygen target, bronchodilator timing, steroid course, and antibiotic threshold.',
        bullets: [
          'Anchor antibiotic choice to increased dyspnea, sputum volume, and sputum purulence.',
          'Watch oxygen targets in chronic CO2 retainers.',
          'Review disposition cues before mixed pulmonary cases.',
        ],
      },
    ],
    pharmacopeia: [
      {
        title: 'Loop diuretics',
        label: 'Class effect',
        detail: 'High-yield repair for edema syndromes, hypokalemia, ototoxicity, and sulfonamide caution.',
        bullets: [
          'Tie adverse effects to the nephron site of action.',
          'Track potassium and renal response after aggressive diuresis.',
          'Contrast with thiazides for calcium and stone-prevention questions.',
        ],
      },
      {
        title: 'Beta blockers in heart failure',
        label: 'Therapeutic anchor',
        detail: 'Board-safe use favors stable chronic HFrEF, not acute decompensation initiation.',
        bullets: [
          'Know evidence-based agents: carvedilol, metoprolol succinate, bisoprolol.',
          'Avoid starting during unstable volume overload.',
          'Use contraindication clues before selecting rate control.',
        ],
      },
      {
        title: 'Systemic corticosteroids',
        label: 'Pulmonary bridge',
        detail: 'COPD and asthma exacerbation stems often test duration, hyperglycemia risk, and infection context.',
        bullets: [
          'Separate controller therapy from acute rescue treatment.',
          'Anticipate glucose and mood adverse effects.',
          'Pair with antibiotic criteria to avoid overtreatment.',
        ],
      },
    ],
    labs: [
      {
        title: 'Serum sodium',
        label: 'Range + pattern',
        detail: 'Interpret with osmolality, urine sodium, volume status, and neurologic symptoms.',
        bullets: [
          'Do not choose treatment before classifying tonicity.',
          'Severe symptoms change urgency and monitoring.',
          'Overcorrection risk is itself a tested complication.',
        ],
      },
      {
        title: 'BNP / NT-proBNP',
        label: 'Cardiology signal',
        detail: 'Supports heart-failure probability but must be interpreted with age, renal function, and obesity.',
        bullets: [
          'Use with exam and imaging, not as a standalone diagnosis.',
          'Renal dysfunction can elevate values.',
          'Obesity may blunt expected elevation.',
        ],
      },
      {
        title: 'ABG in COPD',
        label: 'Respiratory status',
        detail: 'pH and CO2 retention separate compensated chronic disease from acute ventilatory failure.',
        bullets: [
          'Look for acidemia when deciding escalation.',
          'Compare bicarbonate compensation to timing.',
          'Connect gas results to oxygen target and disposition.',
        ],
      },
    ],
    reference: [
      {
        title: 'Chest X-ray patterns',
        label: 'Imaging map',
        detail: 'Pulmonary edema, focal consolidation, pneumothorax, and pleural effusion patterns for first-pass triage.',
        bullets: [
          'Map radiographic pattern to the likely next clinical step.',
          'Avoid overcalling imaging without matching vitals and exam.',
          'Pair classic signs with disposition decisions.',
        ],
      },
      {
        title: 'ECG ischemia review',
        label: 'Procedure/imaging bridge',
        detail: 'ST elevation territory, reciprocal change, rhythm stability, and cath-lab threshold cues.',
        bullets: [
          'Localize artery territory from lead grouping.',
          'Use hemodynamic stability before medication selection.',
          'Contrast pericarditis and early repolarization patterns.',
        ],
      },
      {
        title: 'Focused MSK maneuvers',
        label: 'Exam framework',
        detail: 'Special tests need pre-test suspicion, sensitivity/specificity context, and next-imaging logic.',
        bullets: [
          'Know which maneuver confirms versus screens.',
          'Do not skip neurovascular exam in injury stems.',
          'Connect positive tests to conservative care or imaging.',
        ],
      },
    ],
  },
  clinicalProfilePreview: {
    overall: {
      accuracy: 0.68,
      totalQuestions: 420,
      avgTimeMs: 82000,
    },
    systemBreakdown: [
      { system: 'Cardio', total: 86, correct: 54, accuracy: 0.63, avgTimeMs: 91000 },
      { system: 'Pulm', total: 72, correct: 49, accuracy: 0.68, avgTimeMs: 78000 },
      { system: 'Renal', total: 58, correct: 36, accuracy: 0.62, avgTimeMs: 96000 },
      { system: 'GI', total: 64, correct: 47, accuracy: 0.73, avgTimeMs: 76000 },
      { system: 'MSK', total: 52, correct: 39, accuracy: 0.75, avgTimeMs: 69000 },
      { system: 'Infectious', total: 48, correct: 31, accuracy: 0.65, avgTimeMs: 87000 },
    ],
    strengths: ['MSK imaging choices', 'GI first-line management', 'Focused stem triage'],
    weaknesses: ['Cardiology medication effects', 'Renal volume status', 'Pulmonary disposition'],
    patterns: {
      rushedSystems: ['GI', 'MSK'],
      overthinkingSystems: ['Renal', 'Cardio'],
    },
    diagnosisBias: [
      { condition: 'Heart failure exacerbation', count: 7 },
      { condition: 'Pulmonary embolism', count: 5 },
      { condition: 'SIADH', count: 4 },
      { condition: 'Community-acquired pneumonia', count: 4 },
    ],
    studyPatterns: {
      peakHours: [8, 10, 19],
      avgSessionLength: 41,
    },
  },
  gapAnalysisPreview: {
    userTotalAttempts: 420,
    overallPercentile: 63,
    systems: [
      {
        name: 'Cardiovascular',
        accuracy: 62,
        cohortAverage: 69,
        cohortP90: 84,
        cohortDelta: -7,
        topPerformerGap: 22,
        yieldScore: 96,
        status: 'critical',
        isInsufficientData: false,
      },
      {
        name: 'Renal',
        accuracy: 61,
        cohortAverage: 67,
        cohortP90: 81,
        cohortDelta: -6,
        topPerformerGap: 20,
        yieldScore: 88,
        status: 'weakness',
        isInsufficientData: false,
      },
      {
        name: 'Pulmonary',
        accuracy: 66,
        cohortAverage: 70,
        cohortP90: 83,
        cohortDelta: -4,
        topPerformerGap: 17,
        yieldScore: 81,
        status: 'weakness',
        isInsufficientData: false,
      },
      {
        name: 'Infectious Disease',
        accuracy: 69,
        cohortAverage: 68,
        cohortP90: 82,
        cohortDelta: 1,
        topPerformerGap: 13,
        yieldScore: 66,
        status: 'average',
        isInsufficientData: false,
      },
      {
        name: 'Gastrointestinal',
        accuracy: 74,
        cohortAverage: 70,
        cohortP90: 84,
        cohortDelta: 4,
        topPerformerGap: 10,
        yieldScore: 52,
        status: 'strength',
        isInsufficientData: false,
      },
      {
        name: 'Musculoskeletal',
        accuracy: 77,
        cohortAverage: 72,
        cohortP90: 85,
        cohortDelta: 5,
        topPerformerGap: 8,
        yieldScore: 45,
        status: 'strength',
        isInsufficientData: false,
      },
    ],
  },
};
