/**
 * Trello Integration Service
 *
 * Allows users to export their study plan to Trello boards.
 * Creates a Kanban-style board with lists for each study phase.
 */

export interface TrelloCard {
  name: string;
  desc?: string;
  due?: string; // ISO 8601 format
  labels?: string[];
  pos?: number; // Position in list
}

export interface TrelloList {
  name: string;
  cards: TrelloCard[];
  pos?: number;
}

export interface TrelloBoardExport {
  name: string;
  desc?: string;
  lists: TrelloList[];
  labels?: Array<{ name: string; color: string }>;
}

/**
 * Generate Trello board structure from study plan
 */
export function generateStudyBoard(examDate: Date, weeklyPlan: any[]): TrelloBoardExport {
  const lists: TrelloList[] = [];

  // List 1: Exam Overview
  lists.push({
    name: '🎯 Exam Overview',
    pos: 0,
    cards: [
      {
        name: 'PANCE Exam Date',
        desc: `Your PANCE exam is scheduled for ${examDate.toLocaleDateString('en-US', {
          weekday: 'long',
          month: 'long',
          day: 'numeric',
          year: 'numeric',
        })}\n\nGood luck with your preparation!`,
        due: examDate.toISOString(),
        labels: ['red'],
        pos: 0,
      },
      {
        name: 'Study Plan Summary',
        desc: `**Total Weeks:** ${weeklyPlan.length}\n\n**Topics to Cover:**\n${weeklyPlan.map((w) => `• Week ${w.weekNumber}: ${w.topics.join(', ')}`).join('\n')}\n\n**Strategy:**\n- Daily study sessions (2 hours)\n- Practice questions (1 hour)\n- Weekly review sessions\n- Final 2 weeks: intensive review`,
        pos: 1,
      },
    ],
  });

  // List 2: To Do (Upcoming weeks)
  const upcomingWeeks = weeklyPlan.filter((w) => new Date(w.startDate) > new Date());
  lists.push({
    name: '📚 To Do',
    pos: 1,
    cards: upcomingWeeks.slice(0, 4).map((week, idx) => ({
      name: `${week.weekLabel}: ${week.topics.join(', ')}`,
      desc: `**Focus Areas:**\n${week.topics.map((t) => `• ${t}`).join('\n')}\n\n**Timeline:**\n• Start: ${new Date(week.startDate).toLocaleDateString()}\n• End: ${new Date(week.endDate).toLocaleDateString()}\n\n**Description:**\n${week.description}`,
      due: new Date(week.endDate).toISOString(),
      labels: ['blue'],
      pos: idx,
    })),
  });

  // List 3: In Progress (Current week)
  const currentWeek = weeklyPlan.find((w) => {
    const now = new Date();
    return new Date(w.startDate) <= now && new Date(w.endDate) >= now;
  });

  lists.push({
    name: '⚡ In Progress',
    pos: 2,
    cards: currentWeek
      ? [
          {
            name: `${currentWeek.weekLabel}: ${currentWeek.topics.join(', ')}`,
            desc: `**Currently Studying:**\n${currentWeek.topics.map((t) => `• ${t}`).join('\n')}\n\n**This Week's Goals:**\n☐ Complete 100+ practice questions\n☐ Review weak areas\n☐ Study 2 hours daily\n☐ Weekend comprehensive review\n\n**Notes:**\nAdd your notes and progress here!`,
            due: new Date(currentWeek.endDate).toISOString(),
            labels: ['yellow'],
            pos: 0,
          },
        ]
      : [],
  });

  // List 4: Weak Areas to Review
  lists.push({
    name: '🔴 Weak Areas',
    pos: 3,
    cards: [
      {
        name: 'Track Your Weak Topics Here',
        desc: `**Instructions:**\nAs you identify topics you struggle with, add them as cards to this list.\n\n**For each weak area, note:**\n• What specific concepts are challenging\n• Which questions you missed\n• Resources to review\n• Target date for re-testing\n\n**Example:**\n"Cardiology - Heart Failure"\n• Confused systolic vs. diastolic\n• Review NYHA classification\n• Re-do practice questions on Friday`,
        pos: 0,
      },
    ],
  });

  // List 5: Completed
  const completedWeeks = weeklyPlan.filter((w) => new Date(w.endDate) < new Date());
  lists.push({
    name: '✅ Completed',
    pos: 4,
    cards: completedWeeks.map((week, idx) => ({
      name: `${week.weekLabel}: ${week.topics.join(', ')}`,
      desc: `**Completed!**\n\n${week.topics.map((t) => `✓ ${t}`).join('\n')}`,
      pos: idx,
      labels: ['green'],
    })),
  });

  // List 6: Resources & References
  lists.push({
    name: '📖 Resources',
    pos: 5,
    cards: [
      {
        name: 'Recommended Study Resources',
        desc: `**PANCE Resources:**\n• PANCE Prep Pearls\n• Rosh Review\n• PACKRAT Practice Exams\n• UpToDate\n• PANaCEa Question Bank\n\n**Free Resources:**\n• Medscape\n• PubMed\n• CDC Guidelines\n• USPSTF Recommendations\n\n**Study Techniques:**\n• Spaced repetition\n• Active recall\n• Practice questions\n• Peer teaching`,
        pos: 0,
      },
    ],
  });

  return {
    name: 'PANCE Study Plan',
    desc: 'My personalized PANCE study schedule generated by PANaCEa',
    lists,
    labels: [
      { name: 'Urgent', color: 'red' },
      { name: 'Study', color: 'blue' },
      { name: 'In Progress', color: 'yellow' },
      { name: 'Completed', color: 'green' },
      { name: 'Review', color: 'orange' },
      { name: 'Practice', color: 'purple' },
    ],
  };
}

/**
 * Generate JSON export for Trello import
 */
export function generateTrelloJSON(board: TrelloBoardExport): string {
  // Trello JSON format for import
  const trelloBoard = {
    name: board.name,
    desc: board.desc,
    prefs: {
      permissionLevel: 'private',
      voting: 'disabled',
      comments: 'members',
      invitations: 'members',
      selfJoin: true,
      cardCovers: true,
      background: 'blue',
    },
    lists: board.lists.map((list, listIdx) => ({
      name: list.name,
      closed: false,
      pos: list.pos ?? listIdx,
      cards: list.cards.map((card, cardIdx) => ({
        name: card.name,
        desc: card.desc || '',
        due: card.due || null,
        closed: false,
        pos: card.pos ?? cardIdx,
        labels: card.labels || [],
      })),
    })),
    labels: board.labels || [],
  };

  return JSON.stringify(trelloBoard, null, 2);
}

/**
 * Download Trello JSON file
 */
export function downloadTrelloJSON(
  board: TrelloBoardExport,
  filename: string = 'panacea-study-board.json'
) {
  const json = generateTrelloJSON(board);
  const blob = new Blob([json], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate Trello board creation URL (opens Trello with pre-filled data)
 */
export function getTrelloBoardUrl(boardName: string): string {
  const encodedName = encodeURIComponent(boardName);
  return `https://trello.com/b/new?name=${encodedName}`;
}

/**
 * Instructions for Trello import
 */
export const TRELLO_IMPORT_INSTRUCTIONS = `
## How to Create Your Study Board in Trello:

### Method 1: Manual Setup (Recommended)
1. Go to Trello.com and create a new board called "PANCE Study Plan"
2. Download the JSON file above
3. Follow the structure to manually create lists and cards
4. Copy the descriptions from the JSON into each card

### Method 2: Power-Up Import (If Available)
1. Download the JSON file above
2. In Trello, create a new board
3. Go to Show Menu → Power-Ups
4. Search for and enable a JSON import Power-Up
5. Import the downloaded JSON file

### Method 3: API Integration (Advanced)
If you're comfortable with APIs, you can use Trello's REST API to automatically create the board:
1. Get your Trello API key and token from https://trello.com/power-ups/admin
2. Use the Trello API to create the board programmatically
3. Reference: https://developer.atlassian.com/cloud/trello/rest/

### Board Structure:
- **🎯 Exam Overview**: Key dates and overall plan
- **📚 To Do**: Upcoming study weeks
- **⚡ In Progress**: Current week's focus
- **🔴 Weak Areas**: Topics needing more attention
- **✅ Completed**: Finished study modules
- **📖 Resources**: Study materials and references

### Tips:
- Move cards from "To Do" to "In Progress" as you start each week
- Add checklists to break down study sessions
- Use labels to categorize by organ system
- Set due dates for weekly milestones
- Add comments to track your progress
`.trim();
