/**
 * Module 3: Digital Sim Lab System Type Definitions
 *
 * Procedural simulation system using:
 * - bring_any_idea_to_life for workflow animations
 * - robotics_franka_pick_and_place concepts for instrument handling
 * - Sterile field tracking
 * - Procedural logic validation
 *
 * @module digital-sim-lab-system
 */

// ============================================================================
// PROCEDURAL WORKFLOW
// ============================================================================

/**
 * Clinical procedure categories.
 */
export type ProcedureCategory =
  | 'vascular_access' // IV, Central line, Arterial line
  | 'airway_management' // Intubation, Cricothyrotomy
  | 'chest_procedures' // Chest tube, Needle decompression
  | 'wound_care' // Suturing, Stapling, Dressing
  | 'diagnostic' // Lumbar puncture, Paracentesis, Arthrocentesis
  | 'cardiac' // CPR, Defibrillation, Cardioversion
  | 'orthopedic' // Splinting, Reduction
  | 'emergency'; // Tourniquet, Packing, Emergent procedures

/**
 * Individual procedural step.
 */
export interface ProceduralStep {
  /** Step number */
  stepNumber: number;

  /** Step name */
  name: string;

  /** Description */
  description: string;

  /** Detailed instructions */
  instructions: string;

  /** Visual aids */
  media: {
    /** Step animation URL (generated by bring_any_idea_to_life) */
    animationUrl?: string;

    /** Static image URLs */
    imageUrls?: string[];

    /** Landmark diagram */
    landmarkDiagramUrl?: string;
  };

  /** Critical actions for this step */
  criticalActions: string[];

  /** Common mistakes */
  commonMistakes: string[];

  /** Safety considerations */
  safetyConsiderations: string[];

  /** Time estimate (seconds) */
  timeEstimate: number;

  /** Is this step optional */
  isOptional: boolean;

  /** Dependencies (must complete these steps first) */
  dependencies: number[];
}

/**
 * Complete procedural workflow.
 */
export interface ProceduralWorkflow {
  /** Procedure ID */
  id: string;

  /** Procedure name */
  name: string;

  /** Category */
  category: ProcedureCategory;

  /** Description */
  description: string;

  /** Indications */
  indications: string[];

  /** Contraindications */
  contraindications: string[];

  /** Steps */
  steps: ProceduralStep[];

  /** Required equipment */
  requiredEquipment: EquipmentItem[];

  /** Complications */
  complications: string[];

  /** Total estimated time */
  totalTimeEstimate: number;

  /** Difficulty level */
  difficulty: 'beginner' | 'intermediate' | 'advanced';

  /** PANCE relevance */
  panceRelevance: number;
}

// ============================================================================
// EQUIPMENT & STERILE FIELD
// ============================================================================

/**
 * Equipment item.
 */
export interface EquipmentItem {
  /** Item ID */
  id: string;

  /** Item name */
  name: string;

  /** Category */
  category: 'instrument' | 'supply' | 'medication' | 'protective_equipment';

  /** Image URL */
  imageUrl: string;

  /** 3D model URL (if available) */
  modelUrl?: string;

  /** Is sterile */
  isSterile: boolean;

  /** Quantity required */
  quantity: number;

  /** Description */
  description: string;

  /** Common substitutes */
  substitutes?: string[];
}

/**
 * Sterile field configuration.
 */
export interface SterileField {
  /** Field ID */
  id: string;

  /** Field type */
  type: 'full_drape' | 'partial_drape' | 'no_drape';

  /** Safe zone coordinates (normalized 0-1) */
  safeZone: {
    type: 'rectangle' | 'circle' | 'polygon';
    bounds: Array<{ x: number; y: number }>;
  };

  /** Border zone (transition area) */
  borderZone?: {
    width: number; // Pixels
    warningEnabled: boolean;
  };

  /** Contamination tracking */
  contaminationTracking: {
    /** Is tracking enabled */
    enabled: boolean;

    /** Contamination events */
    events: Array<{
      timestamp: string;
      position: { x: number; y: number };
      severity: 'minor' | 'major';
      recovered: boolean;
    }>;
  };

  /** Visual feedback */
  visualFeedback: {
    /** Highlight safe zone */
    highlightSafeZone: boolean;

    /** Safe zone color */
    safeZoneColor: string;

    /** Contamination indicator color */
    contaminationColor: string;

    /** Glow effect on hover */
    glowEffect: boolean;
  };
}

/**
 * Equipment tray (pre-procedure setup).
 */
export interface EquipmentTray {
  /** Tray ID */
  id: string;

  /** Procedure ID */
  procedureId: string;

  /** Required items */
  requiredItems: EquipmentItem[];

  /** Student-selected items */
  selectedItems: string[]; // Equipment IDs

  /** Missing items */
  missingItems: string[];

  /** Unnecessary items (selected but not needed) */
  unnecessaryItems: string[];

  /** Tray completion status */
  isComplete: boolean;

  /** Penalty for missing items */
  missingItemPenalty: number;

  /** Penalty for unnecessary items */
  unnecessaryItemPenalty: number;
}

// ============================================================================
// SURGICAL GEOMETRY & INSTRUMENT HANDLING
// ============================================================================

/**
 * Instrument grip type.
 */
export type InstrumentGrip =
  | 'pen_grip' // Scalpel, suture holder
  | 'palm_grip' // Retractor
  | 'pinch_grip' // Forceps, pickups
  | 'ring_finger_grip' // Scissors, hemostats
  | 'two_handed'; // Needle driver

/**
 * Instrument handling parameters.
 */
export interface InstrumentHandling {
  /** Instrument ID */
  instrumentId: string;

  /** Correct grip type */
  correctGrip: InstrumentGrip;

  /** Approach angle (degrees from perpendicular) */
  approachAngle: {
    ideal: number;
    acceptable: { min: number; max: number };
  };

  /** Entry depth (for needles/blades) */
  entryDepth?: {
    ideal: number; // mm
    acceptable: { min: number; max: number };
  };

  /** Force range */
  forceRange?: {
    min: number; // Newtons
    max: number;
  };

  /** Movement path */
  movementPath?: {
    type: 'linear' | 'arc' | 'circular' | 'freeform';
    waypoints: Array<{ x: number; y: number; z: number }>;
  };
}

/**
 * Procedural geometry validation.
 */
export interface ProceduralGeometry {
  /** Procedure step ID */
  stepId: string;

  /** Target anatomy */
  targetAnatomy: {
    /** Anatomical structure ID */
    structureId: string;

    /** 3D model URL */
    modelUrl?: string;

    /** Target coordinates */
    targetPoint: { x: number; y: number; z: number };

    /** Safe entry zone */
    safeZone: {
      radius: number; // mm
      avoidanceZones?: Array<{
        name: string; // e.g., "Subclavian artery"
        center: { x: number; y: number; z: number };
        radius: number;
      }>;
    };
  };

  /** Student's approach */
  studentApproach?: {
    entryPoint: { x: number; y: number; z: number };
    angle: number;
    depth: number;
  };

  /** Validation result */
  validation?: {
    isCorrect: boolean;
    distanceFromIdeal: number; // mm
    angleDeviation: number; // degrees
    hitAvoidanceZone: boolean;
    feedback: string;
  };
}

// ============================================================================
// LANDMARK IDENTIFICATION
// ============================================================================

/**
 * Anatomical landmark for procedures.
 */
export interface AnatomicalLandmark {
  /** Landmark ID */
  id: string;

  /** Landmark name */
  name: string;

  /** Description */
  description: string;

  /** Image showing landmark */
  imageUrl: string;

  /** 3D model (if available) */
  modelUrl?: string;

  /** Coordinates on image/model (normalized 0-1) */
  coordinates: { x: number; y: number; z?: number };

  /** Palpation technique */
  palpationTechnique?: string;

  /** Visual identification tips */
  visualTips: string[];

  /** Common errors */
  commonErrors: string[];
}

/**
 * Landmark identification quiz.
 */
export interface LandmarkIdentificationQuiz {
  /** Quiz ID */
  id: string;

  /** Procedure */
  procedureId: string;

  /** Landmarks to identify */
  landmarks: AnatomicalLandmark[];

  /** Base image */
  baseImageUrl: string;

  /** Student clicks */
  studentClicks: Array<{
    landmarkId: string;
    position: { x: number; y: number };
    timestamp: string;
  }>;

  /** Scoring */
  scoring: {
    maxDistanceForCredit: number; // Normalized
    pointsPerLandmark: number;
  };

  /** Feedback */
  feedback?: string;
}

// ============================================================================
// PROCEDURE SIMULATION
// ============================================================================

/**
 * Procedure simulation session.
 */
export interface ProcedureSimulation {
  /** Session ID */
  id: string;

  /** User ID */
  userId: string;

  /** Workflow */
  workflow: ProceduralWorkflow;

  /** Current step */
  currentStep: number;

  /** Step completion status */
  stepCompletionStatus: Record<
    number,
    {
      completed: boolean;
      timeSpent: number;
      criticalActionsPerformed: string[];
      mistakes: string[];
      score: number;
    }
  >;

  /** Equipment tray */
  equipmentTray: EquipmentTray;

  /** Sterile field */
  sterileField: SterileField;

  /** Geometry validations */
  geometryValidations: ProceduralGeometry[];

  /** Overall score */
  score: {
    preparationScore: number;
    techniqueScore: number;
    safetyScore: number;
    timeScore: number;
    overallScore: number;
  };

  /** Start time */
  startTime: string;

  /** End time */
  endTime?: string;

  /** Status */
  status: 'in_progress' | 'completed' | 'abandoned';
}

/**
 * Procedure simulation feedback.
 */
export interface ProcedureFeedback {
  /** Session ID */
  sessionId: string;

  /** Overall assessment */
  overallAssessment: string;

  /** Strengths */
  strengths: string[];

  /** Areas for improvement */
  areasForImprovement: string[];

  /** Critical errors */
  criticalErrors: string[];

  /** Teaching points */
  teachingPoints: string[];

  /** Next steps */
  nextSteps: string[];

  /** Recommended practice procedures */
  recommendedPractice: string[];
}

// ============================================================================
// ANIMATION GENERATION (BRING_ANY_IDEA_TO_LIFE)
// ============================================================================

/**
 * Animation generation request.
 */
export interface AnimationGenerationRequest {
  /** Procedure step */
  step: ProceduralStep;

  /** Animation style */
  style: 'realistic' | 'schematic' | 'hybrid';

  /** Duration (seconds) */
  duration: number;

  /** View angle */
  viewAngle: 'first_person' | 'third_person' | 'overhead' | 'lateral';

  /** Annotation overlay */
  annotations: {
    enabled: boolean;
    labels?: string[];
    arrows?: boolean;
  };

  /** Speed control */
  speedControl: {
    normalSpeed: number; // 1.0 = real-time
    slowMotionSegments?: Array<{
      startTime: number;
      endTime: number;
      speed: number;
    }>;
  };
}

/**
 * Animation generation response.
 */
export interface AnimationGenerationResponse {
  /** Animation ID */
  id: string;

  /** Video URL */
  videoUrl: string;

  /** Thumbnail URL */
  thumbnailUrl: string;

  /** Duration */
  duration: number;

  /** Generation status */
  status: 'completed' | 'failed';

  /** Error message (if failed) */
  error?: string;
}

// ============================================================================
// EXAMPLE CONFIGURATIONS
// ============================================================================

/**
 * Example: Central line placement workflow.
 */
export const EXAMPLE_CENTRAL_LINE_WORKFLOW: ProceduralWorkflow = {
  id: 'procedure-central-line-001',
  name: 'Internal Jugular Central Venous Catheter Placement',
  category: 'vascular_access',
  description: 'Ultrasound-guided central line placement via internal jugular vein',
  indications: [
    'Need for central venous access',
    'Large-volume resuscitation',
    'Vasopressor administration',
    'Central venous pressure monitoring',
  ],
  contraindications: [
    'Infection at insertion site',
    'Severe coagulopathy (relative)',
    'Anatomical distortion',
  ],
  steps: [
    {
      stepNumber: 1,
      name: 'Positioning',
      description: 'Position patient in Trendelenburg with head turned away',
      instructions:
        'Place patient supine in 15-30° Trendelenburg. Turn head 30° away from insertion site.',
      media: {},
      criticalActions: ['Confirm patient positioning', 'Ensure airway access'],
      commonMistakes: ['Excessive head rotation', 'Inadequate Trendelenburg'],
      safetyConsiderations: ['Monitor airway', 'Prevent aspiration'],
      timeEstimate: 60,
      isOptional: false,
      dependencies: [],
    },
    {
      stepNumber: 2,
      name: 'Landmark Identification',
      description: 'Identify the carotid artery and internal jugular vein',
      instructions:
        'Palpate carotid pulse. Use ultrasound to identify IJV lateral to carotid artery.',
      media: {
        landmarkDiagramUrl: 'https://cdn.panacea.app/landmarks/ijv-landmarks.png',
      },
      criticalActions: ['Confirm vein compressibility', 'Confirm artery pulsatility'],
      commonMistakes: ['Confusing artery for vein', 'Inadequate ultrasound technique'],
      safetyConsiderations: ['Avoid carotid puncture', 'Ensure anatomic clarity'],
      timeEstimate: 120,
      isOptional: false,
      dependencies: [1],
    },
    // Additional steps omitted for brevity
  ],
  requiredEquipment: [
    {
      id: 'eq-central-line-kit',
      name: 'Central Line Kit',
      category: 'supply',
      imageUrl: 'https://cdn.panacea.app/equipment/central-line-kit.jpg',
      isSterile: true,
      quantity: 1,
      description: 'Pre-packaged sterile central line kit with catheter, guidewire, dilator',
    },
    {
      id: 'eq-ultrasound',
      name: 'Ultrasound with Linear Probe',
      category: 'instrument',
      imageUrl: 'https://cdn.panacea.app/equipment/ultrasound.jpg',
      isSterile: false,
      quantity: 1,
      description: 'High-frequency linear probe for vascular access',
    },
    {
      id: 'eq-sterile-gown',
      name: 'Sterile Gown',
      category: 'protective_equipment',
      imageUrl: 'https://cdn.panacea.app/equipment/sterile-gown.jpg',
      isSterile: true,
      quantity: 1,
      description: 'Full-body sterile surgical gown',
    },
  ],
  complications: [
    'Arterial puncture',
    'Pneumothorax',
    'Hemothorax',
    'Air embolism',
    'Catheter-related infection',
  ],
  totalTimeEstimate: 900, // 15 minutes
  difficulty: 'advanced',
  panceRelevance: 85,
};

/**
 * Example: Sterile field for central line.
 */
export const EXAMPLE_STERILE_FIELD: SterileField = {
  id: 'sterile-field-central-line',
  type: 'full_drape',
  safeZone: {
    type: 'rectangle',
    bounds: [
      { x: 0.2, y: 0.15 },
      { x: 0.8, y: 0.15 },
      { x: 0.8, y: 0.85 },
      { x: 0.2, y: 0.85 },
    ],
  },
  borderZone: {
    width: 20,
    warningEnabled: true,
  },
  contaminationTracking: {
    enabled: true,
    events: [],
  },
  visualFeedback: {
    highlightSafeZone: true,
    safeZoneColor: '#00ff0033',
    contaminationColor: '#ff000099',
    glowEffect: true,
  },
};
