/**
 * Patient A/V State Machine Type Definitions
 *
 * Defines the event-driven architecture for synchronizing real-time voice
 * interaction (native_audio_function_call_sandbox) with dynamic video loops
 * (veo_cameos) in Module 1: The Living Patient Encounter.
 *
 * @module patient-av-state-machine
 */

// ============================================================================
// CLINICAL TRIGGERS
// ============================================================================

/**
 * Clinical trigger categories that drive state transitions.
 * These are derived from PatientEncounterSession.physicalFindings and vitals.
 */
export type ClinicalTriggerType =
  | 'respiratory' // O2 sat, respiratory rate, breath sounds
  | 'cardiovascular' // HR, BP, cardiac findings
  | 'neurological' // Mental status, GCS, focal deficits
  | 'pain' // Pain scale, location, character
  | 'metabolic' // Temperature, glucose, consciousness
  | 'trauma' // Physical injury, bleeding
  | 'psychological' // Anxiety, agitation, confusion
  | 'environmental'; // Room, setting, time-of-day

/**
 * Clinical severity levels that modulate AV presentation.
 */
export type ClinicalSeverity = 'stable' | 'mild' | 'moderate' | 'severe' | 'critical';

/**
 * A clinical trigger that can cause a state transition.
 */
export interface ClinicalTrigger {
  /** Unique trigger identifier (e.g., "hypoxia_severe", "pain_chest") */
  id: string;

  /** Trigger category */
  type: ClinicalTriggerType;

  /** Severity level */
  severity: ClinicalSeverity;

  /** Human-readable description */
  description: string;

  /** Condition expression evaluated against vitals/physicalFindings JSON */
  condition: ClinicalConditionExpression;

  /** Priority (1-10, higher = more urgent) for competing triggers */
  priority: number;

  /** Timestamp when trigger was activated (ISO 8601) */
  activatedAt?: string;
}

/**
 * Expression tree for evaluating clinical conditions.
 * Examples:
 * - { field: "vitals.o2", operator: "lt", value: 88 }
 * - { operator: "and", conditions: [...] }
 */
export type ClinicalConditionExpression =
  | {
      field: string; // JSON path (e.g., "vitals.o2", "physicalFindings.lungSounds")
      operator: 'eq' | 'neq' | 'lt' | 'lte' | 'gt' | 'gte' | 'contains' | 'in';
      value: string | number | boolean | string[];
    }
  | {
      operator: 'and' | 'or' | 'not';
      conditions: ClinicalConditionExpression[];
    };

// ============================================================================
// AUDIO-VISUAL STATES
// ============================================================================

/**
 * Voice modulation settings for Gemini native_audio_function_call_sandbox.
 */
export interface VoiceModulation {
  /** Voice library ID from Gemini (e.g., "Kore", "Puck", "Aoede") */
  voiceId: string;

  /** Speech rate multiplier (0.5 - 2.0) */
  rate: number;

  /** Pitch shift in semitones (-12 to +12) */
  pitch: number;

  /** Volume multiplier (0.0 - 1.0) */
  volume: number;

  /** Tone descriptors for AI prompt (e.g., "breathless", "agitated", "weak") */
  toneDescriptors: string[];

  /** Whether to apply vocal strain/distortion effects */
  applyVocalStrain: boolean;

  /** Background sounds (e.g., "wheezing", "coughing", "monitor_beeps") */
  backgroundSounds?: string[];
}

/**
 * Video state for veo_cameos integration.
 */
export interface VideoState {
  /** Video loop ID (matches veo_cameos generation) */
  videoId: string;

  /** Video prompt used for generation */
  prompt: string;

  /** Physical presentation (e.g., "Levine sign", "tripod position", "writhing") */
  physicalPresentation: string;

  /** Environment/setting (e.g., "ED", "clinic", "home") */
  environment: 'emergency_department' | 'clinic' | 'home' | 'ambulance';

  /** Loop duration in seconds (typically 3-7s for seamless loops) */
  duration: number;

  /** Transition type when entering this state */
  transitionType: 'immediate' | 'crossfade' | 'medical_scan';

  /** Transition duration in ms */
  transitionDuration: number;

  /** Video URL (once generated by veo_cameos) */
  videoUrl?: string;

  /** Generation status */
  status: 'pending' | 'generating' | 'ready' | 'error';
}

/**
 * Combined audio-visual state definition.
 */
export interface AVState {
  /** Unique state identifier (e.g., "stable_baseline", "hypoxia_severe") */
  id: string;

  /** Human-readable state name */
  name: string;

  /** Clinical context for this state */
  clinicalContext: string;

  /** Voice modulation settings */
  voice: VoiceModulation;

  /** Video presentation */
  video: VideoState;

  /** System prompt override for AI patient in this state */
  systemPromptOverride?: string;

  /** Auto-transition rules (if any) */
  autoTransitions?: StateTransitionRule[];
}

// ============================================================================
// STATE MACHINE DEFINITION
// ============================================================================

/**
 * Transition rule that defines when and how to move between states.
 */
export interface StateTransitionRule {
  /** Target state ID */
  toState: string;

  /** Clinical triggers that activate this transition */
  triggers: ClinicalTrigger[];

  /** Cooldown in seconds before this transition can fire again */
  cooldown?: number;

  /** Whether this transition is reversible (can auto-revert) */
  reversible: boolean;

  /** Reversion condition (if reversible) */
  reversionCondition?: ClinicalConditionExpression;

  /** Optional student action requirement (e.g., "administer_oxygen") */
  requiresStudentAction?: string;
}

/**
 * Complete state machine definition for a patient encounter.
 */
export interface PatientAVStateMachine {
  /** Unique machine ID (typically matches caseId) */
  id: string;

  /** Version for schema evolution */
  version: string;

  /** Initial state ID */
  initialState: string;

  /** All possible states */
  states: Record<string, AVState>;

  /** Global transition rules (apply from any state) */
  globalTransitions: StateTransitionRule[];

  /** State-specific transitions */
  stateTransitions: Record<string, StateTransitionRule[]>;

  /** Metadata */
  metadata: {
    caseId: string;
    patientName: string;
    chiefComplaint: string;
    createdAt: string;
    updatedAt: string;
  };
}

// ============================================================================
// RUNTIME STATE & EVENTS
// ============================================================================

/**
 * Current runtime state of the A/V engine.
 */
export interface AVEngineState {
  /** Current state ID */
  currentState: string;

  /** State history (state ID + timestamp) */
  stateHistory: Array<{ stateId: string; timestamp: string; trigger?: string }>;

  /** Active clinical triggers */
  activeTriggers: ClinicalTrigger[];

  /** Current vitals snapshot */
  currentVitals: {
    hr: number;
    bp: string;
    temp: number;
    rr: number;
    o2: number;
    [key: string]: string | number;
  };

  /** Current physical findings snapshot */
  currentPhysicalFindings: Record<string, unknown>;

  /** Student actions performed (for transition requirements) */
  studentActions: Array<{ action: string; timestamp: string }>;

  /** Last transition timestamp */
  lastTransitionAt: string;
}

/**
 * Event types for the A/V state machine.
 */
export type AVEventType =
  | 'STATE_ENTER'
  | 'STATE_EXIT'
  | 'TRIGGER_ACTIVATED'
  | 'TRIGGER_DEACTIVATED'
  | 'TRANSITION_REQUESTED'
  | 'TRANSITION_COMPLETED'
  | 'TRANSITION_FAILED'
  | 'VITALS_UPDATED'
  | 'PHYSICAL_FINDINGS_UPDATED'
  | 'STUDENT_ACTION'
  | 'VIDEO_GENERATED'
  | 'VIDEO_ERROR'
  | 'VOICE_MODULATION_UPDATED';

/**
 * Base event structure.
 */
export interface AVEvent {
  type: AVEventType;
  timestamp: string;
  sessionId: string;
  payload: unknown;
}

/**
 * State transition event.
 */
export interface StateTransitionEvent extends AVEvent {
  type: 'TRANSITION_COMPLETED';
  payload: {
    fromState: string;
    toState: string;
    trigger?: ClinicalTrigger;
    duration: number;
  };
}

/**
 * Trigger activation event.
 */
export interface TriggerActivationEvent extends AVEvent {
  type: 'TRIGGER_ACTIVATED';
  payload: {
    trigger: ClinicalTrigger;
    vitalsSnapshot: Record<string, unknown>;
  };
}

/**
 * Vitals update event.
 */
export interface VitalsUpdateEvent extends AVEvent {
  type: 'VITALS_UPDATED';
  payload: {
    vitals: Record<string, string | number>;
    changedFields: string[];
    triggersEvaluated: ClinicalTrigger[];
  };
}

// ============================================================================
// WEBSOCKET PROTOCOL
// ============================================================================

/**
 * WebSocket message types for A/V synchronization.
 */
export type AVWebSocketMessageType =
  | 'av_state_sync' // Server → Client: Full state sync
  | 'av_state_transition' // Server → Client: State changed
  | 'av_trigger_activated' // Server → Client: Trigger activated
  | 'av_vitals_update' // Client → Server: Vitals changed
  | 'av_student_action' // Client → Server: Student performed action
  | 'av_video_ready' // Server → Client: Video URL available
  | 'audio' // Bidirectional: Audio chunks (existing)
  | 'transcript' // Server → Client: Transcript segment (existing)
  | 'barge_in' // Client → Server: Interrupt (existing)
  | 'tts_start' // Server → Client: AI started speaking (existing)
  | 'tts_end'; // Server → Client: AI stopped speaking (existing)

/**
 * WebSocket message structure.
 */
export interface AVWebSocketMessage {
  type: AVWebSocketMessageType;
  timestamp: string;
  payload: unknown;
}

/**
 * State sync message (server → client).
 */
export interface AVStateSyncMessage extends AVWebSocketMessage {
  type: 'av_state_sync';
  payload: {
    currentState: AVState;
    engineState: AVEngineState;
    availableActions: string[];
  };
}

/**
 * State transition message (server → client).
 */
export interface AVStateTransitionMessage extends AVWebSocketMessage {
  type: 'av_state_transition';
  payload: {
    fromState: string;
    toState: string;
    newStateDefinition: AVState;
    trigger?: ClinicalTrigger;
    transitionAnimation: {
      type: 'immediate' | 'crossfade' | 'medical_scan';
      duration: number;
    };
  };
}

/**
 * Vitals update message (client → server).
 */
export interface AVVitalsUpdateMessage extends AVWebSocketMessage {
  type: 'av_vitals_update';
  payload: {
    vitals: Record<string, string | number>;
    physicalFindings?: Record<string, unknown>;
  };
}

/**
 * Student action message (client → server).
 */
export interface AVStudentActionMessage extends AVWebSocketMessage {
  type: 'av_student_action';
  payload: {
    action: string;
    parameters?: Record<string, unknown>;
  };
}

// ============================================================================
// EXAMPLE STATE MACHINE CONFIGURATIONS
// ============================================================================

/**
 * Pre-defined clinical triggers library.
 */
export const CLINICAL_TRIGGERS_LIBRARY: Record<string, ClinicalTrigger> = {
  hypoxia_severe: {
    id: 'hypoxia_severe',
    type: 'respiratory',
    severity: 'severe',
    description: 'Severe hypoxia (O2 sat < 88%)',
    condition: {
      field: 'vitals.o2',
      operator: 'lt',
      value: 88,
    },
    priority: 9,
  },
  hypoxia_moderate: {
    id: 'hypoxia_moderate',
    type: 'respiratory',
    severity: 'moderate',
    description: 'Moderate hypoxia (O2 sat 88-92%)',
    condition: {
      operator: 'and',
      conditions: [
        { field: 'vitals.o2', operator: 'gte', value: 88 },
        { field: 'vitals.o2', operator: 'lte', value: 92 },
      ],
    },
    priority: 7,
  },
  tachycardia: {
    id: 'tachycardia',
    type: 'cardiovascular',
    severity: 'moderate',
    description: 'Tachycardia (HR > 100)',
    condition: {
      field: 'vitals.hr',
      operator: 'gt',
      value: 100,
    },
    priority: 5,
  },
  pain_severe_chest: {
    id: 'pain_severe_chest',
    type: 'pain',
    severity: 'severe',
    description: 'Severe chest pain',
    condition: {
      operator: 'and',
      conditions: [
        { field: 'physicalFindings.painLocation', operator: 'eq', value: 'chest' },
        { field: 'physicalFindings.painScale', operator: 'gte', value: 7 },
      ],
    },
    priority: 8,
  },
  agitation: {
    id: 'agitation',
    type: 'psychological',
    severity: 'moderate',
    description: 'Patient agitated or anxious',
    condition: {
      field: 'physicalFindings.mentalStatus',
      operator: 'in',
      value: ['agitated', 'anxious', 'panicked'],
    },
    priority: 6,
  },
  fever_high: {
    id: 'fever_high',
    type: 'metabolic',
    severity: 'moderate',
    description: 'High fever (temp > 102°F)',
    condition: {
      field: 'vitals.temp',
      operator: 'gt',
      value: 102,
    },
    priority: 6,
  },
};

/**
 * Example: COPD exacerbation state machine.
 */
export const EXAMPLE_COPD_STATE_MACHINE: PatientAVStateMachine = {
  id: 'copd-exacerbation-001',
  version: '1.0.0',
  initialState: 'mild_distress',
  metadata: {
    caseId: 'case-copd-001',
    patientName: 'John Smith',
    chiefComplaint: 'Shortness of breath',
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  states: {
    mild_distress: {
      id: 'mild_distress',
      name: 'Mild Respiratory Distress',
      clinicalContext: 'Patient is breathing rapidly but speaking in full sentences',
      voice: {
        voiceId: 'Kore',
        rate: 1.0,
        pitch: 0,
        volume: 0.8,
        toneDescriptors: ['slightly breathless', 'concerned'],
        applyVocalStrain: false,
        backgroundSounds: ['occasional_wheeze'],
      },
      video: {
        videoId: 'copd-mild-001',
        prompt:
          '60yo male in ED, sitting upright, mild dyspnea, nasal cannula, pursed lip breathing',
        physicalPresentation: 'Pursed-lip breathing',
        environment: 'emergency_department',
        duration: 5,
        transitionType: 'immediate',
        transitionDuration: 0,
        status: 'ready',
      },
    },
    severe_hypoxia: {
      id: 'severe_hypoxia',
      name: 'Severe Hypoxia - Decompensating',
      clinicalContext:
        'Patient is severely hypoxic, speaking in 2-3 word sentences, accessory muscle use',
      voice: {
        voiceId: 'Kore',
        rate: 0.7,
        pitch: 2,
        volume: 0.6,
        toneDescriptors: ['gasping', 'panicked', 'breathless'],
        applyVocalStrain: true,
        backgroundSounds: ['labored_breathing', 'wheezing', 'monitor_alarm'],
      },
      video: {
        videoId: 'copd-severe-001',
        prompt:
          '60yo male in ED, severe dyspnea, tripod position, accessory muscle use, high-flow oxygen, monitor alarming',
        physicalPresentation: 'Tripod position, accessory muscle use',
        environment: 'emergency_department',
        duration: 5,
        transitionType: 'medical_scan',
        transitionDuration: 1000,
        status: 'ready',
      },
      systemPromptOverride:
        'You are extremely short of breath. You can only speak 2-3 words at a time before gasping. You are scared and struggling to breathe. Your answers must be fragmented.',
      autoTransitions: [
        {
          toState: 'stabilized',
          triggers: [
            {
              id: 'oxygen_therapy_effective',
              type: 'respiratory',
              severity: 'mild',
              description: 'O2 sat improved after oxygen therapy',
              condition: {
                operator: 'and',
                conditions: [
                  { field: 'vitals.o2', operator: 'gte', value: 92 },
                  { field: 'studentActions', operator: 'contains', value: 'administer_oxygen' },
                ],
              },
              priority: 8,
            },
          ],
          cooldown: 30,
          reversible: true,
          reversionCondition: {
            field: 'vitals.o2',
            operator: 'lt',
            value: 90,
          },
          requiresStudentAction: 'administer_oxygen',
        },
      ],
    },
    stabilized: {
      id: 'stabilized',
      name: 'Stabilized Post-Intervention',
      clinicalContext: 'Patient is breathing better after oxygen therapy, speaking full sentences',
      voice: {
        voiceId: 'Kore',
        rate: 0.9,
        pitch: 0,
        volume: 0.9,
        toneDescriptors: ['relieved', 'tired', 'grateful'],
        applyVocalStrain: false,
        backgroundSounds: ['steady_breathing', 'monitor_normal'],
      },
      video: {
        videoId: 'copd-stable-001',
        prompt:
          '60yo male in ED, breathing easier, relaxed posture, high-flow oxygen, relieved expression',
        physicalPresentation: 'Relaxed posture, improved breathing',
        environment: 'emergency_department',
        duration: 5,
        transitionType: 'crossfade',
        transitionDuration: 2000,
        status: 'ready',
      },
    },
  },
  globalTransitions: [
    {
      toState: 'severe_hypoxia',
      triggers: [CLINICAL_TRIGGERS_LIBRARY.hypoxia_severe],
      cooldown: 0,
      reversible: true,
      reversionCondition: {
        field: 'vitals.o2',
        operator: 'gte',
        value: 92,
      },
    },
  ],
  stateTransitions: {},
};
