/**
 * TrustBadge.tsx
 * Sprint 10 Task 3: Trust Badges for Question Source
 * 
 * Displays a badge indicating whether a question is:
 * - Verified Content (from database cache) - Shield icon
 * - AI Generated (live from Gemini fallback) - Sparkle icon
 */

import React from 'react';
import { motion } from 'framer-motion';
import { Shield, Sparkles, CheckCircle2 } from 'lucide-react';

// Accept string to be flexible with Question type's source field
export type QuestionSource = 'database' | 'ai_fallback' | 'pool' | string | undefined;

interface TrustBadgeProps {
  source: QuestionSource;
  showLabel?: boolean;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

const sizeClasses = {
  sm: {
    icon: 'w-3.5 h-3.5',
    text: 'text-xs',
    padding: 'px-2 py-0.5',
    gap: 'gap-1',
  },
  md: {
    icon: 'w-4 h-4',
    text: 'text-sm',
    padding: 'px-2.5 py-1',
    gap: 'gap-1.5',
  },
  lg: {
    icon: 'w-5 h-5',
    text: 'text-base',
    padding: 'px-3 py-1.5',
    gap: 'gap-2',
  },
};

export const TrustBadge: React.FC<TrustBadgeProps> = ({
  source,
  showLabel = true,
  size = 'sm',
  className = '',
}) => {
  const sizes = sizeClasses[size];

  // Treat 'database' and 'pool' as verified sources (from curated question bank)
  if (source === 'database' || source === 'pool') {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.2, ease: 'easeOut' }}
        className={`
          inline-flex items-center ${sizes.gap} ${sizes.padding}
          bg-emerald-50 dark:bg-emerald-900/30
          text-emerald-700 dark:text-emerald-400
          border border-emerald-200 dark:border-emerald-700/50
          rounded-full font-medium
          ${className}
        `}
        title="This question has been reviewed and verified for accuracy"
        aria-label="Verified Content"
      >
        <Shield className={sizes.icon} aria-hidden="true" />
        {showLabel && <span className={sizes.text}>Verified</span>}
      </motion.div>
    );
  }

  // AI-generated fallback questions
  if (source === 'ai_fallback' || source === 'ai' || source === 'generated') {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.2, ease: 'easeOut' }}
        className={`
          inline-flex items-center ${sizes.gap} ${sizes.padding}
          bg-violet-50 dark:bg-violet-900/30
          text-violet-700 dark:text-violet-400
          border border-violet-200 dark:border-violet-700/50
          rounded-full font-medium
          ${className}
        `}
        title="This question was generated by AI - content may vary"
        aria-label="AI Generated Content"
      >
        <Sparkles className={sizes.icon} aria-hidden="true" />
        {showLabel && <span className={sizes.text}>AI Generated</span>}
      </motion.div>
    );
  }

  // Unknown or undefined source - show subtle indicator
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.2, ease: 'easeOut' }}
      className={`
        inline-flex items-center ${sizes.gap} ${sizes.padding}
        bg-slate-100 dark:bg-slate-800
        text-slate-500 dark:text-slate-400
        border border-slate-200 dark:border-slate-700
        rounded-full font-medium
        ${className}
      `}
      title="Question source unknown"
      aria-label="Unknown Source"
    >
      <CheckCircle2 className={sizes.icon} aria-hidden="true" />
      {showLabel && <span className={sizes.text}>Standard</span>}
    </motion.div>
  );
};

/**
 * Compact version for inline use (icon only with tooltip)
 */
export const TrustBadgeIcon: React.FC<{
  source: QuestionSource;
  className?: string;
}> = ({ source, className = '' }) => {
  return <TrustBadge source={source} showLabel={false} size="sm" className={className} />;
};

export default TrustBadge;
