/**
 * Clinical Research Agent — Supervisor-Researcher Graph
 *
 * Adapts the supervisor-researcher multi-agent pattern from Open Deep Research
 * (github.com/langchain-ai/open_deep_research) for evidence-based medicine
 * literature review. The supervisor decomposes a clinical question into
 * research subtasks, dispatches them to researcher sub-agents, and synthesizes
 * findings into a structured evidence summary.
 *
 * Architecture (inspired by Open Deep Research's multi_agent.py):
 * - Supervisor: decomposes question → dispatches to researchers → synthesizes
 * - Researcher: searches literature → extracts findings → grades evidence
 * - Synthesizer: merges findings → resolves conflicts → formats output
 *
 * Phases: plan → research → synthesize → grade → complete
 *
 * State is held in LangGraph `Annotation.Root` with append-only reducers
 * for findings and evidence grades. AI calls delegate to `routeTask` /
 * `routeStructured` from `lib/langchain/router`.
 *
 * @module lib/agents/graphs/clinical-research
 */

import { z } from 'zod';
import {
  StateGraph,
  Annotation,
  START,
  END,
} from '@langchain/langgraph';

import { routeTask, routeStructured } from '@/lib/langchain/router';
import type { AIEnvKeys } from '@/lib/langchain/models';

// ─── Types ──────────────────────────────────────────────────────────────────

export type ResearchPhase =
  | 'planning'
  | 'researching'
  | 'synthesizing'
  | 'grading'
  | 'complete'
  | 'failed';

export interface ResearchFinding {
  /** Source citation */
  source: string;
  /** Key finding */
  finding: string;
  /** Evidence level (1a–5) */
  evidenceLevel: string;
  /** Relevance score 0–1 */
  relevance: number;
  /** Publication year */
  year: number;
}

export interface EvidenceGrade {
  /** Finding being graded */
  finding: string;
  /** GRADE rating (High, Moderate, Low, Very Low) */
  grade: 'High' | 'Moderate' | 'Low' | 'Very Low';
  /** Rationale for the grade */
  rationale: string;
}

export interface ResearchSubtask {
  /** Subtask description */
  query: string;
  /** Search domain (pubmed, guidelines, trials) */
  domain: 'pubmed' | 'guidelines' | 'trials' | 'general';
  /** Priority 1–5 */
  priority: number;
}

export interface ClinicalResearchInput {
  env: AIEnvKeys;
  /** Clinical question (PICO format recommended) */
  question: string;
  /** Optional: patient population */
  population?: string;
  /** Optional: intervention */
  intervention?: string;
  /** Optional: comparison */
  comparison?: string;
  /** Optional: outcome */
  outcome?: string;
  /** Maximum research subtasks */
  maxSubtasks?: number;
  /** Maximum findings per subtask */
  maxFindingsPerSubtask?: number;
}

// ─── State Schema ───────────────────────────────────────────────────────────

export const ClinicalResearchState = Annotation.Root({
  /** Clinical question */
  question: Annotation<string>,
  /** PICO elements */
  population: Annotation<string>,
  intervention: Annotation<string>,
  comparison: Annotation<string>,
  outcome: Annotation<string>,
  /** Research subtasks generated by supervisor */
  subtasks: Annotation<ResearchSubtask[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),
  /** Current subtask index */
  currentSubtaskIndex: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 0,
  }),
  /** Research findings */
  findings: Annotation<ResearchFinding[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),
  /** Evidence grades */
  evidenceGrades: Annotation<EvidenceGrade[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),
  /** Synthesized summary */
  summary: Annotation<string>({
    reducer: (_prev, next) => next,
    default: () => '',
  }),
  /** Clinical recommendations */
  recommendations: Annotation<string[]>({
    reducer: (_prev, next) => next,
    default: () => [],
  }),
  /** Confidence in the synthesis 0–1 */
  confidence: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 0,
  }),
  /** Current phase */
  phase: Annotation<ResearchPhase>({
    reducer: (_prev, next) => next,
    default: () => 'planning',
  }),
  /** Maximum subtasks */
  maxSubtasks: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 5,
  }),
  /** Maximum findings per subtask */
  maxFindingsPerSubtask: Annotation<number>({
    reducer: (_prev, next) => next,
    default: () => 3,
  }),
  /** Error message if failed */
  error: Annotation<string | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),
  /** Env keys for AI calls */
  env: Annotation<AIEnvKeys | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),
});

export type CRState = typeof ClinicalResearchState.State;
export type CRUpdate = Partial<CRState>;

// ─── Helpers ────────────────────────────────────────────────────────────────

function resolveEnv(state: CRState): AIEnvKeys {
  if (state.env) return state.env;
  throw new Error('ClinicalResearchAgent: state.env is not set.');
}

function buildPICOQuestion(state: CRState): string {
  const parts: string[] = [];
  if (state.population) parts.push(`Population: ${state.population}`);
  if (state.intervention) parts.push(`Intervention: ${state.intervention}`);
  if (state.comparison) parts.push(`Comparison: ${state.comparison}`);
  if (state.outcome) parts.push(`Outcome: ${state.outcome}`);
  return parts.length > 0
    ? `${state.question}\n\nPICO:\n${parts.join('\n')}`
    : state.question;
}

// ─── Node: Plan (Supervisor decomposes question) ────────────────────────────

const ResearchSubtaskSchema = z.object({
  subtasks: z.array(z.object({
    query: z.string().describe('Specific search query for this subtask'),
    domain: z.enum(['pubmed', 'guidelines', 'trials', 'general']).describe('Search domain'),
    priority: z.number().min(1).max(5).describe('Priority 1 (highest) to 5 (lowest)'),
  })).describe('Research subtasks to investigate'),
});

async function planNode(state: CRState): Promise<CRUpdate> {
  const env = resolveEnv(state);
  const picoQuestion = buildPICOQuestion(state);

  try {
    const result = await routeStructured(
      'clinical-reasoning',
      env,
      {
        systemPrompt: `You are a clinical research supervisor. Decompose the following clinical question into focused research subtasks.

For each subtask, specify:
- A specific search query
- The best search domain (pubmed for primary literature, guidelines for clinical practice guidelines, trials for clinical trials, general for broad searches)
- Priority (1=highest, 5=lowest)

Limit to ${state.maxSubtasks} subtasks. Prioritize by clinical impact and evidence availability.

Output valid JSON matching the schema.`,
        userPrompt: picoQuestion,
      },
      ResearchSubtaskSchema,
      { runName: 'clinical-research.plan', temperature: 0.3 },
    );

    const subtasks = result.output.subtasks
      .sort((a, b) => a.priority - b.priority)
      .slice(0, state.maxSubtasks);

    return {
      subtasks,
      currentSubtaskIndex: 0,
      phase: subtasks.length > 0 ? 'researching' : 'complete',
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { phase: 'failed', error: `Planning failed: ${message}` };
  }
}

// ─── Node: Research (Researcher searches literature) ────────────────────────

const ResearchFindingsSchema = z.object({
  findings: z.array(z.object({
    source: z.string().describe('Full citation or source description'),
    finding: z.string().describe('Key clinical finding'),
    evidenceLevel: z.string().describe('Evidence level (1a, 1b, 2a, 2b, 3a, 3b, 4, 5)'),
    relevance: z.number().min(0).max(1).describe('Relevance to the clinical question (0-1)'),
    year: z.number().describe('Publication year'),
  })).describe('Research findings from literature search'),
});

async function researchNode(state: CRState): Promise<CRUpdate> {
  const env = resolveEnv(state);
  const subtask = state.subtasks[state.currentSubtaskIndex];
  if (!subtask) {
    return { phase: 'synthesizing' };
  }

  try {
    const result = await routeStructured(
      'clinical-reasoning',
      env,
      {
        systemPrompt: `You are a clinical literature researcher. Search for evidence related to the following research subtask.

Domain: ${subtask.domain}
Priority: ${subtask.priority}/5

For each finding, provide:
- A proper source citation
- The key clinical finding (be specific and quantitative when possible)
- Evidence level using Oxford CEBM levels (1a–5)
- Relevance score (0–1) to the original clinical question
- Publication year

Limit to ${state.maxFindingsPerSubtask} findings. Prioritize higher-level evidence (systematic reviews > RCTs > observational studies).

Original clinical question: ${state.question}`,
        userPrompt: subtask.query,
      },
      ResearchFindingsSchema,
      { runName: 'clinical-research.research', temperature: 0.3 },
    );

    const findings = result.output.findings.slice(0, state.maxFindingsPerSubtask);
    const nextIndex = state.currentSubtaskIndex + 1;
    const nextPhase = nextIndex >= state.subtasks.length ? 'synthesizing' : 'researching';

    return {
      findings,
      currentSubtaskIndex: nextIndex,
      phase: nextPhase,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    // Continue to next subtask on individual research failure
    const nextIndex = state.currentSubtaskIndex + 1;
    const nextPhase = nextIndex >= state.subtasks.length ? 'synthesizing' : 'researching';
    return {
      currentSubtaskIndex: nextIndex,
      phase: nextPhase,
    };
  }
}

// ─── Node: Synthesize (Synthesizer merges findings) ─────────────────────────

const SynthesisSchema = z.object({
  summary: z.string().describe('Synthesized evidence summary (2-4 paragraphs)'),
  recommendations: z.array(z.string()).describe('Clinical recommendations based on evidence'),
  confidence: z.number().min(0).max(1).describe('Overall confidence in the synthesis (0-1)'),
});

async function synthesizeNode(state: CRState): Promise<CRUpdate> {
  const env = resolveEnv(state);

  if (state.findings.length === 0) {
    return {
      summary: 'No research findings were collected. The clinical question could not be answered with available evidence.',
      recommendations: ['Consider reformulating the clinical question using PICO format.'],
      confidence: 0,
      phase: 'complete',
    };
  }

  const findingsText = state.findings
    .map((f, i) => `${i + 1}. [${f.evidenceLevel}] ${f.finding} (${f.source}, ${f.year}) — Relevance: ${f.relevance}`)
    .join('\n');

  try {
    const result = await routeStructured(
      'clinical-reasoning',
      env,
      {
        systemPrompt: `You are a clinical evidence synthesizer. Synthesize the following research findings into a structured evidence summary.

Clinical Question: ${state.question}
${state.population ? `Population: ${state.population}` : ''}
${state.intervention ? `Intervention: ${state.intervention}` : ''}

Research Findings:
${findingsText}

Provide:
1. A 2-4 paragraph evidence summary that synthesizes the findings
2. 3-5 actionable clinical recommendations based on the evidence
3. A confidence score (0-1) reflecting the strength and consistency of the evidence

Be honest about evidence limitations. Do not overstate findings from low-quality evidence.`,
        userPrompt: 'Synthesize the findings now.',
      },
      SynthesisSchema,
      { runName: 'clinical-research.synthesize', temperature: 0.3 },
    );

    return {
      summary: result.output.summary,
      recommendations: result.output.recommendations,
      confidence: result.output.confidence,
      phase: 'grading',
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { phase: 'failed', error: `Synthesis failed: ${message}` };
  }
}

// ─── Node: Grade (Evidence grader assesses quality) ─────────────────────────

const EvidenceGradeSchema = z.object({
  grades: z.array(z.object({
    finding: z.string().describe('The finding being graded'),
    grade: z.enum(['High', 'Moderate', 'Low', 'Very Low']).describe('GRADE rating'),
    rationale: z.string().describe('Rationale for the GRADE rating'),
  })).describe('Evidence grades for each finding'),
});

async function gradeNode(state: CRState): Promise<CRUpdate> {
  const env = resolveEnv(state);

  if (state.findings.length === 0) {
    return { phase: 'complete' };
  }

  const findingsForGrading = state.findings
    .map((f, i) => `${i + 1}. ${f.finding} [Evidence Level: ${f.evidenceLevel}]`)
    .join('\n');

  try {
    const result = await routeStructured(
      'clinical-reasoning',
      env,
      {
        systemPrompt: `You are a clinical evidence grader using the GRADE framework. Grade each finding below.

GRADE Criteria:
- High: Further research is very unlikely to change confidence
- Moderate: Further research is likely to impact confidence
- Low: Further research is very likely to impact confidence
- Very Low: Any estimate of effect is very uncertain

Consider: risk of bias, inconsistency, indirectness, imprecision, publication bias.

Findings to grade:
${findingsForGrading}

For each finding, provide the GRADE rating and a brief rationale.`,
        userPrompt: 'Grade the evidence now.',
      },
      EvidenceGradeSchema,
      { runName: 'clinical-research.grade', temperature: 0.2 },
    );

    return {
      evidenceGrades: result.output.grades,
      phase: 'complete',
    };
  } catch (err) {
    // Grading failure is non-fatal — complete without grades
    return { phase: 'complete' };
  }
}

// ─── Conditional Edge Router ────────────────────────────────────────────────

function routeAfterPlan(state: CRState): string {
  if (state.phase === 'researching') return 'research';
  if (state.phase === 'complete') return 'synthesize';
  return '__end__';
}

function routeAfterResearch(state: CRState): string {
  if (state.phase === 'researching') return 'research';
  if (state.phase === 'synthesizing') return 'synthesize';
  return '__end__';
}

// ─── Graph Build ────────────────────────────────────────────────────────────

const clinicalResearchGraph = new StateGraph(ClinicalResearchState)
  .addNode('plan', planNode)
  .addNode('research', researchNode)
  .addNode('synthesize', synthesizeNode)
  .addNode('grade', gradeNode)
  .addEdge(START, 'plan')
  .addConditionalEdges('plan', routeAfterPlan, [
    'research',
    'synthesize',
    '__end__',
  ])
  .addConditionalEdges('research', routeAfterResearch, [
    'research',
    'synthesize',
    '__end__',
  ])
  .addEdge('synthesize', 'grade')
  .addEdge('grade', END);

export const compiledClinicalResearchGraph = clinicalResearchGraph.compile();

// ─── Graph Runner ───────────────────────────────────────────────────────────

export interface ClinicalResearchResult {
  question: string;
  summary: string;
  recommendations: string[];
  confidence: number;
  findings: ResearchFinding[];
  evidenceGrades: EvidenceGrade[];
  subtaskCount: number;
  phase: 'complete' | 'failed';
  error?: string;
}

/**
 * Run the clinical research agent.
 *
 * @example
 * ```ts
 * const result = await runClinicalResearch({
 *   env: cloudflareEnv,
 *   question: 'In adults with type 2 diabetes, does SGLT2 inhibitor therapy reduce cardiovascular mortality compared to standard care?',
 *   population: 'Adults with type 2 diabetes',
 *   intervention: 'SGLT2 inhibitor therapy',
 *   comparison: 'Standard care',
 *   outcome: 'Cardiovascular mortality',
 * });
 * ```
 */
export async function runClinicalResearch(
  input: ClinicalResearchInput,
): Promise<ClinicalResearchResult> {
  const initialState: Partial<CRState> = {
    question: input.question,
    population: input.population ?? '',
    intervention: input.intervention ?? '',
    comparison: input.comparison ?? '',
    outcome: input.outcome ?? '',
    subtasks: [],
    currentSubtaskIndex: 0,
    findings: [],
    evidenceGrades: [],
    summary: '',
    recommendations: [],
    confidence: 0,
    phase: 'planning',
    maxSubtasks: input.maxSubtasks ?? 5,
    maxFindingsPerSubtask: input.maxFindingsPerSubtask ?? 3,
    error: null,
    env: input.env,
  };

  try {
    const result = await compiledClinicalResearchGraph.invoke(initialState, {
      runName: 'clinical-research-agent',
      tags: ['research', 'evidence-based-medicine', 'clinical'],
      metadata: {
        question: input.question.slice(0, 200),
        population: input.population,
        intervention: input.intervention,
      },
      recursionLimit: 50,
    });

    return {
      question: result.question,
      summary: result.summary,
      recommendations: result.recommendations,
      confidence: result.confidence,
      findings: result.findings,
      evidenceGrades: result.evidenceGrades,
      subtaskCount: result.subtasks.length,
      phase: result.phase === 'failed' ? 'failed' : 'complete',
      error: result.error ?? undefined,
    };
  } catch (error) {
    return {
      question: input.question,
      summary: '',
      recommendations: [],
      confidence: 0,
      findings: [],
      evidenceGrades: [],
      subtaskCount: 0,
      phase: 'failed',
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
