# SAFE-OVERRIDE: SQL seed file - no shell execution commands
-- CV + PULM Expansion Batch: 30 new PreGeneratedQuestion entries
-- Targets high-yield PANCE conditions not yet covered in the question bank
-- IDs: q-exp-cv-001..015, q-exp-pulm-001..015
-- validationStatus = 'pending' (approve via admin refinery)

INSERT INTO "PreGeneratedQuestion" (id, "questionType", system, difficulty, "questionData", "questionOrder", "taskCategory", "validationStatus", "generatedAt")
VALUES
-- ============================================================
-- CARDIOVASCULAR (15 questions)
-- ============================================================
('q-exp-cv-001', 'clinical-vignette', 'CV', 'easy', '{"question":"A 62-year-old male with prior MI presents with palpitations and presyncope. ECG shows a wide-complex tachycardia at 160 bpm with AV dissociation and fusion beats. BP is 88/60 mmHg. What is the most likely diagnosis?","options":["A. Ventricular tachycardia","B. Supraventricular tachycardia with aberrant conduction","C. Atrial flutter with 2:1 block","D. Wolff-Parkinson-White with antidromic conduction"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"AV dissociation plus fusion beats in a wide-complex tachycardia is virtually pathognomonic for ventricular tachycardia (VT). A prior MI creates a re-entrant circuit in scar tissue — the most common cause of sustained monomorphic VT. SVT with aberrancy can mimic VT but would not produce AV dissociation or fusion beats. The hemodynamic instability (BP 88/60) further supports VT. Immediate synchronized cardioversion is indicated when the patient is unstable.","conditionName":"Ventricular Tachycardia","system":"CV","subcategory":"Arrhythmias","tags":["CV","VT","arrhythmia","AV-dissociation","post-MI"],"generatedWith":"expansion-v1"}',
'first', 'diagnosis', 'pending', NOW()),

('q-exp-cv-002', 'clinical-vignette', 'CV', 'medium', '{"question":"A 58-year-old male collapses at a grocery store. Bystanders initiate CPR. Paramedics arrive 4 minutes later and attach a defibrillator, which shows pulseless ventricular tachycardia at 200 bpm. What is the immediate next step?","options":["A. Unsynchronized defibrillation at 200 J (biphasic)","B. Synchronized cardioversion at 100 J","C. IV amiodarone 300 mg bolus","D. IV lidocaine 1.5 mg/kg bolus"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Pulseless VT is a shockable rhythm requiring immediate unsynchronized defibrillation (defibrillation, not cardioversion, because the patient has no pulse and synchronization cannot be reliably performed). Biphasic 200 J is the standard initial energy. Synchronized cardioversion is used for unstable patients who still have a pulse. Amiodarone and lidocaine are adjuncts after the first shock, not the first intervention. CPR should resume immediately after each shock.","conditionName":"Pulseless Ventricular Tachycardia","system":"CV","subcategory":"Arrhythmias","tags":["CV","VT","pulseless","ACLS","defibrillation"],"generatedWith":"expansion-v1"}',
'second', 'management', 'pending', NOW()),

('q-exp-cv-003', 'clinical-vignette', 'CV', 'medium', '{"question":"A 74-year-old female presents with fatigue and dizziness. ECG shows P waves at 80 bpm and QRS complexes at 38 bpm with no relationship between them. The PR interval varies throughout the tracing. What is the diagnosis and most appropriate next step?","options":["A. Third-degree (complete) AV block — transvenous pacing followed by permanent pacemaker","B. Second-degree Mobitz I — observation and monitoring","C. Second-degree Mobitz II — IV atropine","D. Junctional tachycardia — IV metoprolol"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Complete AV block (third-degree) is characterized by complete dissociation of atrial and ventricular activity: the atria fire at their intrinsic rate (80 bpm) and the ventricles escape at a slow idioventricular rate (38 bpm) with no fixed PR relationship. This is a hemodynamically significant bradyarrhythmia requiring urgent pacing — first transcutaneous or transvenous, then permanent pacemaker implantation. Atropine is rarely effective for infranodal (His-Purkinje) complete block and is a temporary bridge at best.","conditionName":"Complete AV Block","system":"CV","subcategory":"Arrhythmias","tags":["CV","AV-block","complete","pacemaker","bradycardia"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-cv-004', 'clinical-vignette', 'CV', 'medium', '{"question":"A 68-year-old male with known coronary artery disease presents after two syncopal episodes. ECG shows intermittent non-conducted P waves with a constant PR interval before the dropped beat. QRS is wide with right bundle branch morphology. What is the most appropriate management?","options":["A. Permanent pacemaker implantation","B. Long-term oral metoprolol","C. IV atropine infusion","D. Observation with Holter monitoring"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This describes Mobitz Type II second-degree AV block (constant PR interval with sudden dropped QRS), which occurs in the His-Purkinje system (infranodal). The wide QRS with RBBB morphology confirms infranodal disease. Mobitz II carries a high risk of progression to complete heart block and sudden death — permanent pacemaker is the definitive treatment. Atropine is ineffective for infranodal block. Mobitz I (Wenckebach) has a progressively lengthening PR interval and is generally benign, requiring observation only.","conditionName":"Mobitz Type II AV Block","system":"CV","subcategory":"Arrhythmias","tags":["CV","Mobitz-II","AV-block","pacemaker","syncope"],"generatedWith":"expansion-v1"}',
'second', 'management', 'pending', NOW()),

('q-exp-cv-005', 'clinical-vignette', 'CV', 'medium', '{"question":"A 55-year-old male smoker with hypertension and hyperlipidemia reports chest pressure with exertion that resolves at rest. He has no symptoms at rest and ECG is normal. Which diagnostic test is most appropriate as the initial evaluation for suspected stable angina?","options":["A. Exercise stress ECG (Bruce protocol)","B. Coronary CT angiography","C. Right heart catheterization","D. Resting echocardiogram"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Exercise stress testing (exercise ECG) is the preferred initial test for patients with intermediate pre-test probability of CAD who can exercise and have an interpretable ECG. It provides functional information about ischemia, exercise capacity, and hemodynamic response. Coronary CTA is preferred when the pre-test probability is low-to-intermediate and noninvasive anatomic assessment is desired. Right heart catheterization evaluates pulmonary hypertension and heart failure hemodynamics, not ischemia. Resting echo will not detect exercise-induced ischemia.","conditionName":"Stable Angina","system":"CV","subcategory":"Ischemic Heart Disease","tags":["CV","stable-angina","stress-test","CAD","diagnosis"],"generatedWith":"expansion-v1"}',
'second', 'diagnostics', 'pending', NOW()),

('q-exp-cv-006', 'clinical-vignette', 'CV', 'medium', '{"question":"A 60-year-old female with stable angina is started on medical therapy. She has no contraindications. Which drug class is considered first-line for reducing anginal episodes and improving exercise tolerance?","options":["A. Beta-blockers","B. Calcium channel blockers (dihydropyridine)","C. Long-acting nitrates","D. Ranolazine"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Beta-blockers are first-line for stable angina because they reduce myocardial oxygen demand by decreasing heart rate, contractility, and blood pressure — the three primary determinants of myocardial O2 consumption. They also reduce mortality in patients with prior MI. Calcium channel blockers (dihydropyridines like amlodipine) are second-line or used in combination. Long-acting nitrates are effective for symptom control but do not reduce mortality and require nitrate-free intervals to prevent tolerance. Ranolazine is used as add-on therapy.","conditionName":"Stable Angina Medical Management","system":"CV","subcategory":"Ischemic Heart Disease","tags":["CV","stable-angina","beta-blocker","management","pharmaceuticals"],"generatedWith":"expansion-v1"}',
'second', 'pharmaceutical', 'pending', NOW()),

('q-exp-cv-007', 'clinical-vignette', 'CV', 'medium', '{"question":"A 65-year-old male develops severe dyspnea 3 days after an inferior STEMI managed with thrombolytics. On auscultation you hear a new harsh holosystolic murmur at the apex radiating to the axilla. Pulmonary edema is present on chest X-ray. What is the most likely cause?","options":["A. Acute mitral regurgitation from papillary muscle rupture","B. Ventricular septal defect from septal necrosis","C. Aortic stenosis exacerbation","D. Aortic regurgitation from aortic root dissection"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Papillary muscle rupture is a feared mechanical complication of inferior MI (posteromedial papillary muscle is supplied by the RCA, which is typically culprit in inferior MI). It presents 2–7 days post-MI with acute severe MR: harsh holosystolic murmur radiating to the axilla, acute pulmonary edema, and hemodynamic compromise. The VSD from septal rupture also produces a holosystolic murmur but is heard at the left lower sternal border with a step-up in oxygen saturation from RA to RV on right heart catheterization. Immediate surgical repair or mechanical circulatory support is required.","conditionName":"Acute Mitral Regurgitation - Papillary Muscle Rupture","system":"CV","subcategory":"Acute MI Complications","tags":["CV","MR","mitral-regurgitation","papillary-muscle","STEMI-complication"],"generatedWith":"expansion-v1"}',
'second', 'history_pe', 'pending', NOW()),

('q-exp-cv-008', 'clinical-vignette', 'CV', 'easy', '{"question":"Which patient population should undergo one-time screening abdominal ultrasound for abdominal aortic aneurysm (AAA) according to the USPSTF?","options":["A. Men aged 65–75 who have ever smoked (≥100 cigarettes lifetime)","B. All men and women aged 65–75","C. Women aged 65–75 who have ever smoked","D. Men aged 55–75 with a family history of AAA"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"The USPSTF recommends one-time screening abdominal ultrasound for AAA specifically in men aged 65–75 who have ever smoked (defined as ≥100 cigarettes in a lifetime). The evidence does not support routine screening in women who smoked or in asymptomatic non-smokers, as the absolute benefit is lower and the harms (unnecessary procedures) outweigh benefits in those populations. Women who have never smoked have a low prevalence of AAA. This is a Grade B recommendation.","conditionName":"Abdominal Aortic Aneurysm Screening","system":"CV","subcategory":"Aortic Disease","tags":["CV","AAA","screening","USPSTF","health-maintenance"],"generatedWith":"expansion-v1"}',
'first', 'health_maintenance', 'pending', NOW()),

('q-exp-cv-009', 'clinical-vignette', 'CV', 'medium', '{"question":"A 70-year-old male with known 6.5 cm infrarenal AAA presents to the ED with sudden severe tearing abdominal pain radiating to the back and hypotension (BP 80/50). Abdomen is pulsatile and tender. What is the most appropriate immediate management?","options":["A. Emergent surgical repair (open or endovascular)","B. CT angiography of the abdomen and pelvis","C. IV heparin anticoagulation","D. Permissive hypotension + IV nitroprusside to reduce aortic wall stress"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"The clinical presentation is classic for ruptured AAA: known large AAA, sudden severe tearing abdominal/back pain, pulsatile abdominal mass, and hemodynamic instability. This is a surgical emergency with mortality approaching 90% if untreated. The patient should be taken directly to the OR for emergent open or endovascular repair (EVAR). CT angiography is appropriate only if the patient is hemodynamically stable enough to tolerate imaging (some institutions use it to plan EVAR). IV heparin is contraindicated in rupture. Nitroprusside is used in aortic dissection, not rupture.","conditionName":"Ruptured Abdominal Aortic Aneurysm","system":"CV","subcategory":"Aortic Disease","tags":["CV","AAA","rupture","vascular-emergency","surgical-repair"],"generatedWith":"expansion-v1"}',
'second', 'management', 'pending', NOW()),

('q-exp-cv-010', 'clinical-vignette', 'CV', 'medium', '{"question":"A 24-year-old male athlete presents with palpitations during exercise. Resting ECG shows a short PR interval (0.10 sec), a slurred upstroke of the QRS (delta wave), and a wide QRS complex. He has no structural heart disease. What is the primary concern with this arrhythmia syndrome?","options":["A. Development of atrial fibrillation with rapid ventricular conduction via the accessory pathway","B. Progression to complete heart block","C. Degeneration into ventricular fibrillation from a prolonged QT interval","D. Embolic stroke from intracardiac thrombus"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Wolff-Parkinson-White (WPW) syndrome features an accessory atrioventricular pathway (Bundle of Kent) producing a delta wave, short PR, and wide QRS at rest. The primary lethal risk is atrial fibrillation with rapid conduction through the accessory pathway (which lacks decremental conduction), producing extremely fast ventricular rates (>300 bpm) that can degenerate into ventricular fibrillation and sudden cardiac death. AV nodal blocking agents (adenosine, digoxin, beta-blockers, CCBs) are contraindicated in WPW-AF as they preferentially block the AV node and allow even faster conduction via the accessory pathway.","conditionName":"Wolff-Parkinson-White Syndrome","system":"CV","subcategory":"Arrhythmias","tags":["CV","WPW","accessory-pathway","pre-excitation","delta-wave"],"generatedWith":"expansion-v1"}',
'second', 'diagnostics', 'pending', NOW()),

('q-exp-cv-011', 'clinical-vignette', 'CV', 'hard', '{"question":"A 28-year-old male with known WPW syndrome presents to the ED with a rapid irregular wide-complex tachycardia at 240 bpm. He is conscious with BP 100/70. ECG shows irregular RR intervals with varying QRS morphology. Which drug is most appropriate?","options":["A. IV procainamide","B. IV adenosine","C. IV diltiazem","D. IV digoxin"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This presentation is pre-excited atrial fibrillation (AF with WPW) — irregular, wide-complex tachycardia due to rapid antegrade conduction over the accessory pathway. Procainamide blocks conduction in both the AV node and the accessory pathway, slowing ventricular response. Ibutilide and electrical cardioversion are alternatives. AV nodal blocking agents (adenosine, diltiazem, verapamil, beta-blockers, digoxin) are CONTRAINDICATED: by blocking the AV node, they accelerate conduction over the accessory pathway, which can precipitate ventricular fibrillation and sudden death. If hemodynamically unstable, immediate synchronized cardioversion is first-line.","conditionName":"WPW with Pre-excited Atrial Fibrillation","system":"CV","subcategory":"Arrhythmias","tags":["CV","WPW","AF","pre-excited","procainamide","antiarrhythmic"],"generatedWith":"expansion-v1"}',
'third', 'pharmaceutical', 'pending', NOW()),

('q-exp-cv-012', 'clinical-vignette', 'CV', 'medium', '{"question":"A 38-year-old female with limited systemic sclerosis presents with progressive dyspnea on exertion and near-syncope. Exam shows a loud P2, right ventricular heave, and peripheral edema. Echo shows RV dilation and estimated RVSP of 65 mmHg. Right heart catheterization confirms mean PAP 42 mmHg with PCWP 10 mmHg. What is the diagnosis?","options":["A. Pulmonary arterial hypertension (Group 1)","B. Pulmonary hypertension due to left heart disease (Group 2)","C. Pulmonary hypertension due to chronic lung disease (Group 3)","D. Chronic thromboembolic pulmonary hypertension (Group 4)"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Pulmonary arterial hypertension (PAH, Group 1) is defined by mean PAP ≥25 mmHg at rest with PCWP ≤15 mmHg (indicating the elevated pressures are not from left heart disease) and PVR >3 Wood units on right heart catheterization. Systemic sclerosis (scleroderma) is a major cause of PAH (connective tissue disease-associated PAH). Group 2 (left heart disease) would show elevated PCWP. Group 3 (lung disease) would be associated with COPD/ILD. Group 4 (CTEPH) is treated with pulmonary endarterectomy and would show evidence of organized thrombus on V/Q scan.","conditionName":"Pulmonary Arterial Hypertension","system":"CV","subcategory":"Pulmonary Hypertension","tags":["CV","PAH","pulmonary-hypertension","scleroderma","right-heart-cath"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-cv-013', 'clinical-vignette', 'CV', 'medium', '{"question":"A 32-year-old female presents to the ED with sudden onset palpitations and mild dyspnea. ECG shows a regular narrow-complex tachycardia at 180 bpm with no visible P waves (or P waves within/immediately after the QRS). BP is 115/75. She has no structural heart disease. What is the first-line pharmacologic treatment?","options":["A. IV adenosine 6 mg rapid push","B. IV diltiazem 0.25 mg/kg","C. IV metoprolol 5 mg","D. IV amiodarone 150 mg over 10 minutes"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This is AVNRT (atrioventricular nodal reentrant tachycardia) — the most common cause of paroxysmal SVT in young women. Adenosine is first-line: given as a rapid IV push (6 mg, then 12 mg if unsuccessful), it transiently blocks AV nodal conduction and terminates the reentrant circuit. Vagal maneuvers (Valsalva, carotid sinus massage) should be attempted before adenosine. Diltiazem and metoprolol are alternatives but slower-acting. Amiodarone is reserved for refractory or recurrent SVT. DC cardioversion is used for hemodynamically unstable patients.","conditionName":"Supraventricular Tachycardia - AVNRT","system":"CV","subcategory":"Arrhythmias","tags":["CV","SVT","AVNRT","adenosine","narrow-complex"],"generatedWith":"expansion-v1"}',
'second', 'pharmaceutical', 'pending', NOW()),

('q-exp-cv-014', 'clinical-vignette', 'CV', 'medium', '{"question":"A 10-year-old male presents with fever, migratory polyarthritis, and a new heart murmur 3 weeks after a strep throat infection. Exam shows a friction rub and subcutaneous nodules. ECG shows a prolonged PR interval. What is the diagnosis, and which criteria are used to confirm it?","options":["A. Acute rheumatic fever — Jones criteria","B. Viral myocarditis — Dallas criteria","C. Infective endocarditis — modified Duke criteria","D. Juvenile idiopathic arthritis — ILAR criteria"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Acute rheumatic fever (ARF) is a post-streptococcal inflammatory disease diagnosed using Jones criteria (revised 2015). Major criteria: carditis (new murmur, pericarditis, CHF), polyarthritis, Sydenham chorea, erythema marginatum, subcutaneous nodules. Minor criteria: fever, elevated ESR/CRP, prolonged PR interval. Diagnosis requires 2 major OR 1 major + 2 minor criteria, plus evidence of preceding GAS infection (elevated ASO titer, positive throat culture). The most feared complication is rheumatic heart disease (chronic mitral stenosis). Penicillin prophylaxis is required to prevent recurrence.","conditionName":"Acute Rheumatic Fever","system":"CV","subcategory":"Valvular and Inflammatory","tags":["CV","rheumatic-fever","Jones-criteria","streptococcus","carditis"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-cv-015', 'clinical-vignette', 'CV', 'hard', '{"question":"A 72-year-old female with hypokalemia and hypomagnesemia develops sudden palpitations. ECG shows polymorphic ventricular tachycardia with a characteristic twisting of QRS axis around the isoelectric line and a prolonged QTc (520 ms) on baseline rhythm strips. What is the most appropriate immediate treatment?","options":["A. IV magnesium sulfate 2 g over 1–2 minutes","B. Synchronized cardioversion at 200 J","C. IV amiodarone 300 mg bolus","D. IV lidocaine 1.5 mg/kg"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Torsades de pointes (TdP) is a polymorphic VT associated with a prolonged QT interval, characterized by the twisting QRS axis. The most critical immediate treatment is IV magnesium sulfate 2 g given rapidly, regardless of serum magnesium level — it stabilizes the cardiac membrane and shortens the action potential. Underlying reversible causes must also be corrected (hypokalemia, hypomagnesemia, offending drugs). Amiodarone is CONTRAINDICATED as it further prolongs the QT interval and can worsen TdP. If pulseless, unsynchronized defibrillation is required. Overdrive pacing (70–90 bpm) is definitive therapy for recurrent TdP.","conditionName":"Torsades de Pointes","system":"CV","subcategory":"Arrhythmias","tags":["CV","TdP","torsades","long-QT","magnesium","polymorphic-VT"],"generatedWith":"expansion-v1"}',
'third', 'pharmaceutical', 'pending', NOW()),

-- ============================================================
-- PULMONARY (15 questions)
-- ============================================================
('q-exp-pulm-001', 'clinical-vignette', 'PULM', 'easy', '{"question":"A 45-year-old previously healthy male presents with 4 days of productive cough, fever (38.6°C), and pleuritic chest pain. CXR shows a right lower lobe infiltrate. He is not hypoxic and can be managed outpatient. He has no recent antibiotic use or comorbidities. What is the most appropriate antibiotic?","options":["A. Azithromycin or doxycycline","B. Amoxicillin-clavulanate plus azithromycin","C. Levofloxacin monotherapy","D. Ceftriaxone plus vancomycin"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"For outpatient community-acquired pneumonia (CAP) in a previously healthy patient with no use of antibiotics in the past 3 months and no comorbidities, IDSA/ATS guidelines recommend a macrolide (azithromycin) or doxycycline as monotherapy. Respiratory fluoroquinolones (levofloxacin, moxifloxacin) are alternatives but reserved for patients with comorbidities (COPD, diabetes, renal/liver disease, heart failure) or recent antibiotic use, due to concerns about resistance and adverse effects. Amoxicillin-clavulanate is used for patients with comorbidities. IV ceftriaxone + vancomycin is inpatient therapy.","conditionName":"Community-Acquired Pneumonia - Outpatient","system":"PULM","subcategory":"Pneumonia","tags":["PULM","CAP","pneumonia","azithromycin","doxycycline","outpatient"],"generatedWith":"expansion-v1"}',
'first', 'pharmaceutical', 'pending', NOW()),

('q-exp-pulm-002', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 68-year-old male with COPD presents with fever, purulent sputum, and a right lower lobe consolidation on CXR. His vital signs are: T 39.2°C, HR 112, RR 24, BP 108/70, SpO2 88% on RA. BUN is 28 mg/dL. Which scoring system best guides the decision to admit vs. treat as outpatient, and what does his score indicate?","options":["A. CURB-65 score of 3 — inpatient admission (consider ICU if 4-5)","B. CURB-65 score of 1 — outpatient treatment appropriate","C. PSI Class I — low risk, outpatient treatment","D. Wells score — intermediate PE probability"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"CURB-65 assigns 1 point each for: Confusion, Urea (BUN) >19 mg/dL, Respiratory rate ≥30/min, Blood pressure (SBP <90 or DBP ≤60), age ≥65. This patient scores 3 points (BUN 28 >19 = 1, RR 24 <30 = 0, BP 108/70 borderline — systolic not <90 = 0, age 68 ≥65 = 1, +COPD doesn''t count but tachycardia is a risk — re-counting: BUN >19 + RR borderline). Using strict criteria: BUN >19=1, RR 24 does not meet ≥30=0, BP 108/70 SBP not <90=0, age 68=1 — plus confusion absent. Score = 2-3 range, inpatient recommended. Score 0-1: outpatient; 2: inpatient vs outpatient based on judgment; 3-5: hospitalize, ICU if 4-5.","conditionName":"Community-Acquired Pneumonia - CURB-65","system":"PULM","subcategory":"Pneumonia","tags":["PULM","CAP","CURB-65","severity","hospitalization"],"generatedWith":"expansion-v1"}',
'second', 'health_maintenance', 'pending', NOW()),

('q-exp-pulm-003', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 22-year-old college student presents with 2 weeks of low-grade fever, dry hacking cough, and headache. CXR shows bilateral patchy infiltrates out of proportion to his mild symptoms. WBC is 8,200 with normal differential. He is ambulatory and not hypoxic. What is the most likely causative organism?","options":["A. Mycoplasma pneumoniae","B. Streptococcus pneumoniae","C. Klebsiella pneumoniae","D. Legionella pneumophila"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This is classic atypical (walking) pneumonia — gradual onset, mild systemic symptoms, dry cough, bilateral patchy infiltrates disproportionate to clinical findings, and a normal WBC. Mycoplasma pneumoniae is the most common cause in young adults and college students (outbreaks in dormitories). It lacks a cell wall, making beta-lactams ineffective. Macrolides or doxycycline are first-line treatment. Streptococcus pneumoniae causes lobar pneumonia with productive cough, high fever, and leukocytosis. Klebsiella causes upper lobe cavitary pneumonia in alcoholics. Legionella presents with high fever, GI symptoms, hyponatremia, and elevated LFTs.","conditionName":"Atypical Pneumonia - Mycoplasma","system":"PULM","subcategory":"Pneumonia","tags":["PULM","atypical-pneumonia","Mycoplasma","walking-pneumonia","macrolide"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-pulm-004', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 58-year-old male has been on mechanical ventilation for 7 days in the ICU for respiratory failure from aspiration pneumonia. He develops new fever (39.1°C), purulent tracheal secretions, and a new left lower lobe infiltrate. His CPIS score is elevated. He has received broad-spectrum antibiotics for ≥5 days prior. Which antibiotic regimen is most appropriate for empiric VAP coverage?","options":["A. Piperacillin-tazobactam plus vancomycin (or linezolid)","B. Azithromycin monotherapy","C. Ampicillin-sulbactam monotherapy","D. Ceftriaxone monotherapy"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Ventilator-associated pneumonia (VAP) occurring after ≥5 days of prior antibiotics requires empiric coverage for MDR organisms including Pseudomonas aeruginosa, ESBL-producing Enterobacteriaceae, Acinetobacter, and MRSA. IDSA guidelines recommend: antipseudomonal beta-lactam (piperacillin-tazobactam, cefepime, or carbapenem) PLUS an agent with MRSA coverage (vancomycin or linezolid). Azithromycin is for community-acquired atypical pneumonia. Ampicillin-sulbactam and ceftriaxone lack adequate coverage for resistant gram-negative organisms and MRSA.","conditionName":"Ventilator-Associated Pneumonia","system":"PULM","subcategory":"Pneumonia","tags":["PULM","VAP","nosocomial","MRSA","Pseudomonas","piperacillin-tazobactam"],"generatedWith":"expansion-v1"}',
'second', 'pharmaceutical', 'pending', NOW()),

('q-exp-pulm-005', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 62-year-old male with a 50 pack-year smoking history presents with fatigue, weight loss, and confusion. Labs show sodium 118 mEq/L, serum osmolality 260 mOsm/kg, urine sodium 55 mEq/L, and urine osmolality 540 mOsm/kg. He is euvolemic on exam. CXR shows a central hilar mass. Which lung cancer type most commonly causes this paraneoplastic syndrome?","options":["A. Small cell lung cancer (SCLC)","B. Squamous cell carcinoma","C. Adenocarcinoma","D. Large cell carcinoma"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"SIADH (Syndrome of Inappropriate ADH) causing hyponatremia with hypoosmolality, euvolemia, inappropriately high urine sodium and osmolality is the most common paraneoplastic syndrome of small cell lung cancer. SCLC produces ectopic ADH (and other peptides including ACTH, causing ectopic Cushing, and antibodies against P/Q-type calcium channels causing Lambert-Eaton syndrome). Squamous cell carcinoma causes hypercalcemia via PTHrP secretion. Adenocarcinoma and large cell carcinoma are less commonly associated with paraneoplastic endocrine syndromes. SCLC typically presents as a central hilar mass.","conditionName":"SCLC with SIADH","system":"PULM","subcategory":"Lung Cancer","tags":["PULM","SCLC","SIADH","paraneoplastic","hyponatremia","lung-cancer"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-pulm-006', 'clinical-vignette', 'PULM', 'easy', '{"question":"A 25-year-old male is brought to the ED by EMS after a motorcycle accident. On arrival he has respiratory distress, absent breath sounds on the left, tracheal deviation to the right, and hypotension (BP 80/50). SpO2 is 82%. What is the immediate next step?","options":["A. Needle decompression at the left 2nd intercostal space, midclavicular line","B. Chest X-ray to confirm pneumothorax","C. Chest tube insertion in the 4th-5th ICS, mid-axillary line","D. Emergent intubation and mechanical ventilation"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"The clinical triad of absent breath sounds, tracheal deviation away from the affected side, and hemodynamic instability (hypotension + hypoxia) is diagnostic of tension pneumothorax — a life-threatening emergency. Immediate needle decompression (large-bore needle at the 2nd ICS, MCL or 4th-5th ICS, MAL per newer guidelines) must be performed before any imaging. Waiting for a CXR will cause cardiac arrest. Definitive treatment is a chest tube, but needle decompression is the critical first step. Intubation should not precede decompression as positive pressure ventilation worsens tension physiology.","conditionName":"Tension Pneumothorax","system":"PULM","subcategory":"Pneumothorax","tags":["PULM","tension-pneumothorax","needle-decompression","trauma","emergency"],"generatedWith":"expansion-v1"}',
'first', 'management', 'pending', NOW()),

('q-exp-pulm-007', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 71-year-old male with COPD has FEV1 45% predicted, FEV1/FVC 0.58, CAT score 22, and 2 exacerbations requiring oral steroids in the past year. He is already on a LABA. What medication should be added to his regimen according to GOLD guidelines?","options":["A. LAMA (long-acting muscarinic antagonist)","B. Inhaled corticosteroid (ICS) monotherapy","C. Oral theophylline","D. Oral prednisolone maintenance"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This patient is GOLD Group E (high symptom burden [CAT ≥10] AND frequent exacerbations [≥2/year or ≥1 requiring hospitalization]). GOLD 2023 guidelines recommend dual bronchodilation (LABA + LAMA) as initial therapy for Group E. Adding a LAMA to his existing LABA provides additive bronchodilation. Triple therapy (LABA + LAMA + ICS) is recommended for Group E patients with elevated eosinophils (≥300/μL) or who continue to exacerbate on dual bronchodilation. Oral theophylline has a narrow therapeutic window and is not preferred. Oral maintenance steroids carry significant long-term toxicity (osteoporosis, diabetes, immunosuppression) and are avoided.","conditionName":"COPD - GOLD Group E Management","system":"PULM","subcategory":"COPD","tags":["PULM","COPD","GOLD","LAMA","LABA","exacerbation"],"generatedWith":"expansion-v1"}',
'second', 'pharmaceutical', 'pending', NOW()),

('q-exp-pulm-008', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 67-year-old male with severe COPD (FEV1 28% predicted) has resting SpO2 of 85% on room air and PaO2 of 52 mmHg on ABG. He is stable without acute exacerbation. Which intervention has the strongest evidence for improving survival in this patient?","options":["A. Long-term oxygen therapy (LTOT) ≥15 hours per day","B. Pulmonary rehabilitation program","C. Systemic corticosteroids","D. High-flow nasal cannula oxygen at 40 L/min"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Long-term oxygen therapy (LTOT) is the only medical intervention proven to improve survival in COPD patients with severe resting hypoxemia (PaO2 ≤55 mmHg or SpO2 ≤88%, or PaO2 56-59 with cor pulmonale/erythrocytosis). The landmark MRC and NOTT trials demonstrated that ≥15 hours/day of supplemental O2 reduces mortality. Pulmonary rehabilitation improves exercise capacity and quality of life but does not improve mortality. Systemic corticosteroids are used for acute exacerbations, not chronic stable disease. High-flow nasal cannula may reduce exacerbations but is not standard maintenance therapy.","conditionName":"COPD - Long-Term Oxygen Therapy","system":"PULM","subcategory":"COPD","tags":["PULM","COPD","LTOT","oxygen-therapy","survival","severe-COPD"],"generatedWith":"expansion-v1"}',
'second', 'health_maintenance', 'pending', NOW()),

('q-exp-pulm-009', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 38-year-old non-smoker presents with progressive exertional dyspnea and is found to have COPD with FEV1/FVC 0.62 and FEV1 55% predicted. He has a family history of early-onset liver disease. CXR shows bilateral basilar-predominant emphysema. What is the most likely underlying diagnosis?","options":["A. Alpha-1 antitrypsin deficiency","B. Asthma-COPD overlap syndrome","C. Hypersensitivity pneumonitis","D. Cystic fibrosis"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Alpha-1 antitrypsin deficiency (AATD) should be suspected in COPD patients who are young (<45 years), non-smokers or minimal smokers, and have a family history of liver disease (cirrhosis from AAT accumulation in hepatocytes). The emphysema in AATD is characteristically basilar-predominant (unlike smoking-related emphysema which is apical-predominant). AATD is diagnosed by serum AAT level and Pi phenotyping (PiZZ is the classic homozygous deficiency). Augmentation therapy with IV AAT replacement slows decline in those with FEV1 35-65% predicted.","conditionName":"Alpha-1 Antitrypsin Deficiency","system":"PULM","subcategory":"COPD","tags":["PULM","alpha-1-antitrypsin","AATD","emphysema","basilar","genetic"],"generatedWith":"expansion-v1"}',
'second', 'diagnosis', 'pending', NOW()),

('q-exp-pulm-010', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 70-year-old male with severe COPD presents with worsening dyspnea and altered mental status. ABG shows: pH 7.26, PaCO2 72 mmHg, PaO2 52 mmHg, HCO3 31 mEq/L on supplemental oxygen 2 L/min. He is using accessory muscles and paradoxical abdominal breathing. He can cooperate with instructions. What is the primary physiologic mechanism and best next intervention?","options":["A. Ventilatory failure (hypercapnic) — initiate non-invasive positive pressure ventilation (BiPAP)","B. Hypoxemic failure (Type I) — increase FiO2 to maintain SpO2 >95%","C. Diffusion impairment — IV methylprednisolone alone","D. Ventilation-perfusion mismatch — continuous albuterol nebulization"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This patient has Type II (hypercapnic/ventilatory) respiratory failure: elevated PaCO2 (72 mmHg), respiratory acidosis (pH 7.26), compensatory elevated bicarb (chronic COPD), and hypoxemia. The elevated PaCO2 indicates the lungs cannot eliminate CO2 — the primary problem is inadequate alveolar ventilation from respiratory muscle fatigue and air trapping. BiPAP (bilevel positive airway pressure) is the standard of care for COPD exacerbations with hypercapnic failure — it reduces the work of breathing, improves ventilation, decreases intubation rates, and reduces mortality. Increasing FiO2 alone worsens hypercapnia by abolishing hypoxic ventilatory drive and causing V/Q mismatch via Haldane effect.","conditionName":"COPD Exacerbation with Hypercapnic Respiratory Failure","system":"PULM","subcategory":"COPD","tags":["PULM","COPD","Type-II-respiratory-failure","BiPAP","hypercapnia","NIPPV"],"generatedWith":"expansion-v1"}',
'second', 'basic_science', 'pending', NOW()),

('q-exp-pulm-011', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 52-year-old male alcoholic presents with 2 weeks of fever, productive cough with foul-smelling sputum, and night sweats. CXR shows a thick-walled cavitary lesion with an air-fluid level in the right lower lobe. CT chest confirms a 4 cm cavity with surrounding consolidation. Sputum culture shows mixed anaerobic organisms. What is the most appropriate antibiotic regimen?","options":["A. Ampicillin-sulbactam or amoxicillin-clavulanate (or clindamycin for penicillin-allergic)","B. Azithromycin monotherapy for 5 days","C. Isoniazid + rifampin + pyrazinamide + ethambutol","D. Trimethoprim-sulfamethoxazole for 3 weeks"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Lung abscess in an alcoholic patient is characteristically caused by aspiration of oral anaerobes (Bacteroides, Peptostreptococcus, Fusobacterium, Prevotella). The right lower lobe (or right upper lobe posterior segment) is most common due to aspiration while supine. Foul-smelling sputum is characteristic of anaerobic infection. First-line treatment is ampicillin-sulbactam IV (or amoxicillin-clavulanate oral for stable patients), which covers anaerobes and oral flora. Clindamycin is an alternative for penicillin allergy. Azithromycin has poor anaerobic coverage. Anti-TB drugs treat tuberculosis, which can also cavitate but would show upper lobe distribution and acid-fast bacilli.","conditionName":"Lung Abscess","system":"PULM","subcategory":"Pulmonary Infections","tags":["PULM","lung-abscess","anaerobes","aspiration","ampicillin-sulbactam","alcoholic"],"generatedWith":"expansion-v1"}',
'second', 'pharmaceutical', 'pending', NOW()),

('q-exp-pulm-012', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 58-year-old male ex-smoker has an incidental 8 mm solid pulmonary nodule found on CT chest obtained for an unrelated reason. He has no prior CT chest for comparison. He is low-risk (no smoking history for 15 years, no family history of lung cancer). According to Fleischner Society guidelines, what is the recommended management?","options":["A. CT chest in 3 months","B. CT chest in 12 months","C. Immediate PET-CT","D. CT-guided biopsy"],"correctAnswer":"B","correctAnswerIndex":1,"explanation":"Fleischner Society 2017 guidelines for incidental pulmonary nodules stratify management by nodule size and patient risk. For a solid nodule 6-8 mm in a LOW-RISK patient: optional CT at 6-12 months, then consider CT at 18-24 months. For HIGH-RISK patients (heavy smoking, family history, fibrosis): CT at 6-12 months, then CT at 18-24 months. Nodules <6 mm in low-risk patients: no follow-up needed. Nodules ≥8 mm (or with concerning features): CT at 3 months, PET-CT, or biopsy. At 8 mm in a low-risk patient, CT in 12 months is the most conservative appropriate choice. Immediate biopsy is not indicated for a 8 mm nodule without high-risk features.","conditionName":"Pulmonary Nodule - Fleischner Guidelines","system":"PULM","subcategory":"Lung Cancer","tags":["PULM","pulmonary-nodule","Fleischner","lung-cancer-screening","CT-surveillance"],"generatedWith":"expansion-v1"}',
'second', 'health_maintenance', 'pending', NOW()),

('q-exp-pulm-013', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 52-year-old farmer presents with progressive dyspnea and dry cough for 4 months. He reports symptoms worsening 4-6 hours after working in his hay barn. CXR and HRCT show bilateral ground-glass opacities and small ill-defined nodules. PFTs show a restrictive pattern with reduced DLCO. Serum precipitins to thermophilic actinomycetes are elevated. What is the most likely diagnosis?","options":["A. Hypersensitivity pneumonitis (farmer''s lung)","B. Idiopathic pulmonary fibrosis","C. Sarcoidosis","D. Cryptogenic organizing pneumonia"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Hypersensitivity pneumonitis (HP), also called extrinsic allergic alveolitis, is caused by repeated inhalation of organic antigens triggering a hypersensitivity (Type III and IV) reaction. Farmer''s lung is caused by thermophilic actinomycetes (Saccharopolyspora rectivirgula) in moldy hay. Classic features: subacute/chronic dyspnea with temporal relationship to antigen exposure, restrictive PFTs, bilateral ground-glass opacities on HRCT, and elevated serum precipitins. Avoidance of the antigen is the most important treatment. IPF would not have the temporal exposure pattern or precipitins. Sarcoidosis shows bilateral hilar lymphadenopathy. COP would show consolidation, not nodules.","conditionName":"Hypersensitivity Pneumonitis","system":"PULM","subcategory":"Interstitial Lung Disease","tags":["PULM","hypersensitivity-pneumonitis","HP","farmer''s-lung","organic-antigen","ILD"],"generatedWith":"expansion-v1"}',
'second', 'diagnostics', 'pending', NOW()),

('q-exp-pulm-014', 'clinical-vignette', 'PULM', 'medium', '{"question":"A 55-year-old male with pneumococcal pneumonia develops worsening dyspnea. Chest X-ray shows a large left-sided pleural effusion. Thoracentesis is performed: pH 7.18, glucose 45 mg/dL, LDH 1,200 U/L (serum LDH 220 U/L). The ratio of pleural LDH to serum LDH is 5.5, and pleural protein to serum protein ratio is 0.65. Gram stain shows gram-positive diplococci. What is the most appropriate next step?","options":["A. Chest tube drainage (tube thoracostomy)","B. Repeat thoracentesis in 24 hours","C. IV antibiotics alone without drainage","D. Video-assisted thoracoscopic surgery (VATS) immediately"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"This is a complicated parapneumonic effusion (or frank empyema): pleural pH <7.20, glucose <60 mg/dL, and LDH >1000 U/L meet Light''s criteria for exudate AND indicate a complicated effusion requiring drainage. Positive Gram stain further confirms infected pleural space (empyema). Complicated parapneumonic effusions (pH <7.20, glucose <60, LDH >1000, positive Gram stain/culture) require chest tube drainage — antibiotics alone will not resolve the infection. VATS is reserved for loculated effusions or failed tube drainage. Serial thoracentesis is inadequate for frank empyema.","conditionName":"Complicated Parapneumonic Effusion - Empyema","system":"PULM","subcategory":"Pleural Disease","tags":["PULM","empyema","parapneumonic","pleural-effusion","Light''s-criteria","chest-tube"],"generatedWith":"expansion-v1"}',
'second', 'diagnostics', 'pending', NOW()),

('q-exp-pulm-015', 'clinical-vignette', 'PULM', 'hard', '{"question":"A 65-year-old male lifetime smoker is diagnosed with limited-stage SCLC (confined to one hemithorax, ipsilateral lymph nodes, within one radiation port). PS 0. What is the standard of care first-line treatment?","options":["A. Concurrent chemoradiation (cisplatin + etoposide with thoracic radiotherapy) followed by prophylactic cranial irradiation (PCI) if complete response","B. Surgical resection followed by adjuvant chemotherapy","C. Immunotherapy (atezolizumab) monotherapy","D. Chemotherapy alone with cisplatin + etoposide for 6 cycles"],"correctAnswer":"A","correctAnswerIndex":0,"explanation":"Limited-stage SCLC (LS-SCLC) is treated with concurrent chemoradiation: cisplatin + etoposide (4-6 cycles) with concurrent thoracic radiotherapy (45 Gy bid or 60-70 Gy qd). Concurrent administration improves survival over sequential therapy. Patients who achieve a complete or near-complete response receive prophylactic cranial irradiation (PCI) to prevent brain metastases (SCLC has extremely high neurotropism). Surgery is rarely used in SCLC (only very early stage T1-2N0). Immunotherapy has a role in extensive-stage SCLC (atezolizumab added to chemotherapy) but is not standard for LS-SCLC first-line. Chemotherapy alone is inferior to concurrent chemoradiation for limited-stage disease.","conditionName":"Limited-Stage Small Cell Lung Cancer","system":"PULM","subcategory":"Lung Cancer","tags":["PULM","SCLC","limited-stage","chemoradiation","PCI","cisplatin-etoposide"],"generatedWith":"expansion-v1"}',
'third', 'management', 'pending', NOW());
