#!/usr/bin/env npx tsx

/**
 * Batch CLI for Targeted RAG Library Enrichment
 *
 * Reads the priority list generated by audit.ts and processes each missing field
 * using the enrichment engine.
 *
 * Usage:
 *   npx tsx scripts/library-enrichment/library-enrichment.ts [--limit N] [--resume] [--dry-run]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { enrichRecord } from './enrichment-engine';
import { MissingFieldRecord } from './enrichment-engine';
import { disconnect } from '../_shared/db';

interface Options {
  limit: number; // max records to process
  resume: boolean; // skip already processed fields based on log
  dryRun: boolean; // simulate without calling API or updating DB
  logFile: string;
  priorityFile: string;
}

const DEFAULT_OPTIONS: Options = {
  limit: Infinity,
  resume: true,
  dryRun: false,
  logFile: resolve(process.cwd(), 'data/library-enrichment-log.json'),
  priorityFile: resolve(process.cwd(), 'data/library-enrichment-priority.json'),
};

function parseArgs(): Options {
  const args = process.argv.slice(2);
  const options: Options = { ...DEFAULT_OPTIONS };

  for (const arg of args) {
    if (arg.startsWith('--limit=')) {
      const val = parseInt(arg.split('=')[1], 10);
      if (!isNaN(val)) options.limit = val;
    } else if (arg === '--no-resume') {
      options.resume = false;
    } else if (arg === '--dry-run') {
      options.dryRun = true;
    } else if (arg.startsWith('--log=')) {
      options.logFile = resolve(process.cwd(), arg.split('=')[1]);
    } else if (arg.startsWith('--priority=')) {
      options.priorityFile = resolve(process.cwd(), arg.split('=')[1]);
    } else if (arg === '--help' || arg === '-h') {
      printHelp();
      process.exit(0);
    }
  }
  return options;
}

function printHelp() {
  console.log(`
Targeted RAG Library Enrichment CLI

Usage:
  npx tsx scripts/library-enrichment/library-enrichment.ts [options]

Options:
  --limit=N          Process at most N records (default: all)
  --no-resume        Ignore existing log and process all fields again
  --dry-run          Simulate enrichment (no API calls, no DB updates)
  --log=PATH         Path to enrichment log JSON (default: data/library-enrichment-log.json)
  --priority=PATH    Path to priority list JSON (default: data/library-enrichment-priority.json)
  --help, -h         Show this help
`);
}

/**
 * Load existing log and compute which (entity, field) pairs have already been processed.
 */
function getProcessedSet(logPath: string): Set<string> {
  if (!existsSync(logPath)) return new Set();
  try {
    const content = readFileSync(logPath, 'utf-8');
    const logs = JSON.parse(content) as any[];
    const set = new Set<string>();
    for (const log of logs) {
      if (log.status === 'success' || log.status === 'failure') {
        // Consider a field processed if we have attempted it (success or failure)
        const key = `${log.entityId}:${log.missingField}`;
        set.add(key);
      }
    }
    return set;
  } catch {
    return new Set();
  }
}

/**
 * Load priority list.
 */
function loadPriorityList(path: string): MissingFieldRecord[] {
  if (!existsSync(path)) {
    console.error(`❌ Priority file not found: ${path}`);
    console.error('   Run audit script first: npx tsx scripts/library-enrichment/audit.ts');
    process.exit(1);
  }
  const content = readFileSync(path, 'utf-8');
  const data = JSON.parse(content);
  return data.priorityList || [];
}

async function main() {
  const options = parseArgs();
  console.log('🚀 Targeted RAG Library Enrichment Batch');
  console.log(`   Limit: ${options.limit === Infinity ? 'unlimited' : options.limit}`);
  console.log(`   Resume: ${options.resume}`);
  console.log(`   Dry run: ${options.dryRun}`);
  console.log(`   Priority file: ${options.priorityFile}`);
  console.log(`   Log file: ${options.logFile}\n`);

  const priorityList = loadPriorityList(options.priorityFile);
  console.log(`📋 Loaded ${priorityList.length} records with missing fields.`);

  if (priorityList.length === 0) {
    console.log('No records to enrich.');
    return;
  }

  const processedSet = options.resume ? getProcessedSet(options.logFile) : new Set<string>();
  console.log(`   ${processedSet.size} field(s) already processed (will be skipped).`);

  let processedCount = 0;
  let successCount = 0;
  let failureCount = 0;
  let skippedCount = 0;

  for (const record of priorityList) {
    if (processedCount >= options.limit) {
      console.log(`\n⚠️  Reached limit of ${options.limit} records. Stopping.`);
      break;
    }

    console.log(`\n📝 Record ${processedCount + 1}/${Math.min(priorityList.length, options.limit)}`);
    console.log(`   ${record.entityType}: ${record.name} (${record.system || 'no system'})`);
    console.log(`   Missing fields: ${record.missingFields.join(', ')}`);

    // Filter out fields already processed (if resuming)
    const fieldsToProcess = record.missingFields.filter(field => {
      const key = `${record.id}:${field}`;
      return !processedSet.has(key);
    });

    if (fieldsToProcess.length === 0) {
      console.log(`   ⏭️ All missing fields already processed, skipping record.`);
      skippedCount++;
      continue;
    }

    console.log(`   Will process: ${fieldsToProcess.join(', ')}`);

    if (options.dryRun) {
      console.log(`   🧪 Dry run – would enrich ${fieldsToProcess.length} field(s).`);
      processedCount++;
      continue;
    }

    // Create a temporary record with only fields to process
    const tempRecord = { ...record, missingFields: fieldsToProcess };

    try {
      const logs = await enrichRecord(tempRecord);
      for (const log of logs) {
        if (log.status === 'success') successCount++;
        else if (log.status === 'failure') failureCount++;
        else if (log.status === 'skipped') skippedCount++;
      }
      processedCount++;
    } catch (error: any) {
      console.error(`   ❌ Unexpected error processing record: ${error.message}`);
      failureCount++;
      // Continue with next record
    }

    // Rate limiting between records (5 seconds)
    await new Promise(resolve => setTimeout(resolve, 5000));
  }

  console.log('\n═══════════════════════════════════════════');
  console.log('📊 Batch Complete');
  console.log(`   Processed records: ${processedCount}`);
  console.log(`   Successfully enriched fields: ${successCount}`);
  console.log(`   Failed fields: ${failureCount}`);
  console.log(`   Skipped fields: ${skippedCount}`);
  console.log(`   Log file: ${options.logFile}`);
  console.log('═══════════════════════════════════════════\n');
}

main()
  .catch(error => {
    console.error('❌ Batch failed:', error);
    process.exit(1);
  })
  .finally(() => disconnect());