/**
 * Agent Health Report Script
 *
 * Runs the production agent tools directly against the database
 * and produces a structured markdown report. Bypasses Gemini —
 * calls tool.execute() directly with the live Prisma client.
 *
 * Usage: npx tsx scripts/agent-health-report.ts
 */

import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

// Load .env
function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  try {
    const content = readFileSync(join(process.cwd(), '.env'), 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq === -1) continue;
      env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    }
  } catch { /* ignore */ }
  return env;
}

const envVars = loadEnv();

// Dynamic imports for tools
async function run() {
  const directUrl = envVars.DIRECT_DATABASE_URL || envVars.DATABASE_URL;
  if (!directUrl) {
    console.error('DATABASE_URL not found in .env');
    process.exit(1);
  }

  const pool = new Pool({ connectionString: directUrl });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter } as any);
  const ctx = { prisma, userId: 'health-report-script', env: {} };

  const [
    { blueprintCoverageCheckTool },
    { contentHealthAuditTool },
    { databaseIntegrityCheckTool },
    { fsrsCalibrationStatusTool },
  ] = await Promise.all([
    import('../lib/services/agents/tools/blueprintCoverageCheck'),
    import('../lib/services/agents/tools/contentHealthAudit'),
    import('../lib/services/agents/tools/databaseIntegrityCheck'),
    import('../lib/services/agents/tools/fsrsCalibrationStatus'),
  ]);

  const report: string[] = [];
  report.push(`# PANaCEa Health Report — ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`);
  report.push('');
  report.push('> Auto-generated by agent-health-report.ts');
  report.push('');

  // ─── 1. Blueprint Coverage ──────────────────────────────────────────
  console.log('Running: blueprint_coverage_check...');
  const started = Date.now();
  let coverageResult;
  try {
    coverageResult = await blueprintCoverageCheckTool.execute({}, ctx);
    const elapsed = ((Date.now() - started) / 1000).toFixed(1);

    report.push('## 1. NCCPA Blueprint Coverage');
    report.push('');
    report.push(`**Total pool:** ${coverageResult.totalPoolSize} active questions | **Checked at:** ${coverageResult.timestamp}`);
    report.push('');
    report.push('| System | Weight | Target | Actual | Coverage | Deficit | Status |');
    report.push('|--------|--------|--------|--------|----------|---------|--------|');

    for (const s of coverageResult.systems) {
      const statusEmoji = s.status === 'critical' ? '🔴' : s.status === 'under' ? '🟡' : s.status === 'on_target' ? '🟢' : '🔵';
      report.push(`| ${s.system} | ${(s.blueprintWeight * 100).toFixed(0)}% | ${s.targetQuestions} | ${s.actualQuestions} | ${(s.coverageRatio * 100).toFixed(0)}% | ${s.deficit > 0 ? '-' + s.deficit : '+' + Math.abs(s.deficit)} | ${statusEmoji} ${s.status} |`);
    }

    const critical = coverageResult.systems.filter((s: any) => s.status === 'critical').length;
    const under = coverageResult.systems.filter((s: any) => s.status === 'under').length;
    report.push('');
    report.push(`**Summary:** ${critical} critical, ${under} under-represented systems. Elapsed: ${elapsed}s`);
  } catch (err) {
    report.push('## 1. NCCPA Blueprint Coverage');
    report.push('');
    report.push(`❌ Error: ${err instanceof Error ? err.message : String(err)}`);
  }
  report.push('');

  // ─── 2. Content Health ──────────────────────────────────────────────
  console.log('Running: content_health_audit...');
  const started2 = Date.now();
  try {
    const healthResult = await contentHealthAuditTool.execute({ limit: 10 }, ctx);
    const elapsed = ((Date.now() - started2) / 1000).toFixed(1);

    report.push('## 2. Content Health');
    report.push('');
    report.push(`**Total active questions:** ${healthResult.totalQuestions}`);
    report.push(`**Below threshold (<0.5):** ${healthResult.belowThreshold} (${healthResult.belowThresholdPercent}%)`);
    report.push(`**Flagged:** ${healthResult.flaggedCount}`);
    report.push(`**Needs review:** ${healthResult.needsReviewCount}`);
    report.push(`**Average health score:** ${healthResult.averageHealthScore}`);
    report.push('');

    if (healthResult.worstOffenders.length > 0) {
      report.push('### Worst Offenders');
      report.push('');
      report.push('| System | Health Score | Question Preview |');
      report.push('|--------|-------------|-----------------|');
      for (const q of healthResult.worstOffenders) {
        report.push(`| ${q.system} | ${q.healthScore} | ${q.questionPreview.slice(0, 80)}... |`);
      }
    }

    if (Object.keys(healthResult.bySystem).length > 0) {
      report.push('');
      report.push('### By System');
      report.push('');
      report.push('| System | Count | Avg Score |');
      report.push('|--------|-------|-----------|');
      for (const [sys, data] of Object.entries(healthResult.bySystem)) {
        const d = data as { count: number; avgScore: number };
        report.push(`| ${sys} | ${d.count} | ${d.avgScore} |`);
      }
    }
    report.push(`\n**Elapsed:** ${elapsed}s`);
  } catch (err) {
    report.push('## 2. Content Health');
    report.push('');
    report.push(`❌ Error: ${err instanceof Error ? err.message : String(err)}`);
  }
  report.push('');

  // ─── 3. Database Integrity ──────────────────────────────────────────
  console.log('Running: database_integrity_check...');
  const started3 = Date.now();
  try {
    const dbResult = await databaseIntegrityCheckTool.execute({ checkType: 'orphans' }, ctx);
    const elapsed = ((Date.now() - started3) / 1000).toFixed(1);

    report.push('## 3. Database Integrity');
    report.push('');
    report.push(`**Status:** ${dbResult.overallStatus === 'healthy' ? '🟢' : dbResult.overallStatus === 'warning' ? '🟡' : '🔴'} ${dbResult.overallStatus}`);
    report.push(`**Total orphans:** ${dbResult.totalOrphans}`);
    report.push(`**Checked at:** ${dbResult.checkedAt}`);
    report.push('');
    report.push('| Table | FK Column | References | Orphans | Status |');
    report.push('|-------|-----------|-----------|---------|--------|');

    for (const d of dbResult.orphanDetails) {
      const statusEmoji = d.severity === 'ok' ? '🟢' : d.severity === 'warning' ? '🟡' : '🔴';
      const count = d.orphanCount === -1 ? 'error' : String(d.orphanCount);
      report.push(`| ${d.table} | ${d.fkColumn} | ${d.references} | ${count} | ${statusEmoji} ${d.severity} |`);
    }
    report.push(`\n**Elapsed:** ${elapsed}s`);
  } catch (err) {
    report.push('## 3. Database Integrity');
    report.push('');
    report.push(`❌ Error: ${err instanceof Error ? err.message : String(err)}`);
  }
  report.push('');

  // ─── 4. FSRS Calibration ────────────────────────────────────────────
  console.log('Running: fsrs_calibration_status...');
  const started4 = Date.now();
  try {
    const fsrsResult = await fsrsCalibrationStatusTool.execute({}, ctx);
    const elapsed = ((Date.now() - started4) / 1000).toFixed(1);

    report.push('## 4. FSRS Calibration');
    report.push('');
    const statusEmoji = fsrsResult.status === 'healthy' ? '🟢' : fsrsResult.status === 'warning' ? '🟡' : '🔴';
    report.push(`**Status:** ${statusEmoji} ${fsrsResult.status}`);
    report.push(`**Active cards:** ${fsrsResult.totalActiveCards}`);
    report.push(`**Overdue:** ${fsrsResult.overdueCount} (${fsrsResult.overduePercent}%)`);
    report.push(`**Ease hell:** ${fsrsResult.easeHellCount} (${fsrsResult.easeHellPercent}%)`);
    report.push(`**Avg difficulty:** ${fsrsResult.averageDifficulty}`);
    report.push(`**Avg stability:** ${fsrsResult.averageStability}`);
    report.push(`**7-day backlog:** ${fsrsResult.reviewBacklog7d}`);

    if (fsrsResult.issues.length > 0) {
      report.push('');
      report.push('### Issues');
      for (const issue of fsrsResult.issues) {
        report.push(`- ⚠️ ${issue}`);
      }
    }
    report.push(`\n**Elapsed:** ${elapsed}s`);
  } catch (err) {
    report.push('## 4. FSRS Calibration');
    report.push('');
    report.push(`❌ Error: ${err instanceof Error ? err.message : String(err)}`);
  }

  // ─── Write report ────────────────────────────────────────────────────
  const outputPath = join(process.cwd(), 'docs/reports/agent-health-report.md');
  writeFileSync(outputPath, report.join('\n'));
  console.log(`\n✅ Report written to: ${outputPath}`);
  console.log(report.join('\n'));

  await prisma.$disconnect();
}

run().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
