/**
 * Seed OSCE Patient Encounter Cases
 * Run: npx ts-node scripts/seed-osce-cases.ts
 */

import { prisma, disconnect } from './_shared/db.js';

const osceCases = [
  {
    id: 'osce-chest-pain-mi',
    patientName: 'John Mitchell',
    chiefComplaint: 'Crushing chest pain for 2 hours',
    age: 58,
    sex: 'male',
    vitalSigns: {
      bp: '160/95',
      hr: 98,
      rr: 22,
      temp: '98.6°F',
      spo2: '96%',
    },
    historyData: {
      hpi: 'Substernal crushing chest pain radiating to left arm for 2 hours. Associated with diaphoresis and nausea. Worse with exertion, no relief with rest.',
      pmh: ['HTN', 'Hyperlipidemia', 'Type 2 DM'],
      psh: 'Appendectomy age 25',
      medications: ['Lisinopril 10mg', 'Metformin 500mg BID', 'Atorvastatin 20mg'],
      allergies: 'NKDA',
      social: 'Smokes 1 PPD x 30 years, drinks socially',
      family: 'Father MI at 55, mother HTN',
    },
    physicalExamData: {
      general: 'Anxious, diaphoretic male in moderate distress',
      cardiovascular: 'Tachycardic, S1/S2 regular, no murmurs/gallops',
      pulmonary: 'Clear to auscultation bilaterally',
      abdomen: 'Soft, non-tender',
    },
    labData: {
      troponin: '0.85 ng/mL (elevated)',
      bnp: '450 pg/mL',
      ecg: 'ST elevation in leads V1-V4',
    },
    essentialQuestions: [
      'When did the pain start?',
      'Does the pain radiate anywhere?',
      'Have you had any sweating or nausea?',
      'Do you have a history of heart problems?',
      'Have you taken any medications for this?',
    ],
    helpfulQuestions: [
      'What were you doing when it started?',
      'Is this the worst chest pain of your life?',
      'Any family history of heart disease?',
    ],
    unnecessaryQuestions: [
      'What did you eat for breakfast?',
      'Do you have any pets?',
      'What is your occupation?',
    ],
    correctDiagnosis: 'ST-Elevation Myocardial Infarction (STEMI)',
    differentialDiagnoses: [
      'Unstable Angina',
      'Aortic Dissection',
      'Pulmonary Embolism',
      'Pericarditis',
    ],
    idealWorkup: ['Troponin', 'ECG', 'CXR', 'BMP', 'CBC'],
    teachingPoints: [
      'STEMI requires emergent PCI within 90 minutes',
      'Classic presentation: substernal crushing pain with radiation, diaphoresis',
      'Time is muscle - door-to-balloon time critical',
    ],
  },
  {
    id: 'osce-appendicitis',
    patientName: 'Sarah Chen',
    chiefComplaint: 'Right lower abdominal pain for 12 hours',
    age: 24,
    sex: 'female',
    vitalSigns: {
      bp: '118/72',
      hr: 102,
      rr: 18,
      temp: '101.2°F',
      spo2: '99%',
    },
    historyData: {
      hpi: 'Pain started periumbilically, now localized to RLQ. Associated with nausea, 1 episode of vomiting. No appetite. Pain worse with movement.',
      pmh: 'None',
      psh: 'None',
      medications: 'Oral contraceptives',
      allergies: 'Penicillin (rash)',
      social: 'Non-smoker, occasional alcohol',
      family: 'Mother with Crohn disease',
    },
    physicalExamData: {
      general: 'Young woman lying still, appears uncomfortable',
      abdomen:
        'RLQ tenderness, positive McBurney point, guarding, positive Rovsing sign, positive psoas sign',
      cardiovascular: 'Regular rate and rhythm',
      pulmonary: 'Clear bilaterally',
    },
    labData: {
      wbc: '14,500/μL with left shift',
      hcg: 'Negative',
      ua: 'Normal',
    },
    essentialQuestions: [
      'Where exactly is the pain?',
      'Has the location of pain changed?',
      'Any nausea or vomiting?',
      'When was your last menstrual period?',
      'Could you be pregnant?',
    ],
    helpfulQuestions: [
      'Does coughing or walking make it worse?',
      'Have you had any fever?',
      'Any changes in bowel habits?',
    ],
    unnecessaryQuestions: [
      'Do you have any dental problems?',
      'What is your favorite food?',
      'Do you exercise regularly?',
    ],
    correctDiagnosis: 'Acute Appendicitis',
    differentialDiagnoses: ['Ovarian Cyst', 'Ectopic Pregnancy', 'Mesenteric Adenitis', 'PID'],
    idealWorkup: ['CBC', 'CMP', 'UA', 'Pregnancy test', 'CT abdomen/pelvis'],
    teachingPoints: [
      'Classic migration of pain from periumbilical to RLQ',
      'McBurney point tenderness is hallmark finding',
      'Always rule out pregnancy in women of childbearing age',
    ],
  },
  {
    id: 'osce-pneumonia',
    patientName: 'Robert Williams',
    chiefComplaint: 'Cough and fever for 5 days',
    age: 72,
    sex: 'male',
    vitalSigns: {
      bp: '105/68',
      hr: 108,
      rr: 26,
      temp: '102.8°F',
      spo2: '89%',
    },
    historyData: {
      hpi: 'Productive cough with yellow-green sputum x 5 days. Associated fever, chills, pleuritic chest pain. Worsening shortness of breath.',
      pmh: ['COPD', 'CHF', 'Type 2 DM'],
      psh: 'CABG 2018',
      medications: ['Albuterol inhaler', 'Furosemide 40mg', 'Metformin 1000mg BID'],
      allergies: 'Sulfa drugs',
      social: 'Former smoker (quit 5 years ago), 40 pack-years',
      family: 'Non-contributory',
    },
    physicalExamData: {
      general: 'Elderly male in respiratory distress',
      pulmonary: 'Decreased breath sounds RLL, crackles, dullness to percussion',
      cardiovascular: 'Tachycardic, regular rhythm',
      extremities: 'No edema',
    },
    labData: {
      wbc: '18,200/μL',
      procalcitonin: '2.4 ng/mL',
      cxr: 'RLL consolidation with air bronchograms',
    },
    essentialQuestions: [
      'Describe your cough - is it productive?',
      'What color is the sputum?',
      'How long have you had the fever?',
      'Are you short of breath?',
      'Do you have any chest pain with breathing?',
    ],
    helpfulQuestions: [
      'Have you been around anyone sick?',
      'Are your symptoms getting worse?',
      'Have you been vaccinated for pneumonia?',
    ],
    unnecessaryQuestions: [
      'Do you have any skin rashes?',
      'Any problems with your vision?',
      'Do you have any joint pain?',
    ],
    correctDiagnosis: 'Community-Acquired Pneumonia',
    differentialDiagnoses: [
      'COPD Exacerbation',
      'CHF Exacerbation',
      'Pulmonary Embolism',
      'Lung Cancer',
    ],
    idealWorkup: ['CXR', 'CBC', 'BMP', 'Procalcitonin', 'Blood cultures', 'Sputum culture'],
    teachingPoints: [
      'CURB-65 score guides disposition (Confusion, Uremia, RR, BP, age 65+)',
      'Elderly may present atypically without fever',
      'S. pneumoniae most common cause in community-acquired pneumonia',
    ],
  },
  {
    id: 'osce-dvt-pe',
    patientName: 'Maria Gonzalez',
    chiefComplaint: 'Unilateral leg swelling for 3 days',
    age: 34,
    sex: 'female',
    vitalSigns: {
      bp: '128/82',
      hr: 96,
      rr: 20,
      temp: '99.0°F',
      spo2: '94%',
    },
    historyData: {
      hpi: 'Sudden onset of left leg swelling 3 days after long international flight (8 hours). Associated with left calf pain and tenderness. No chest pain currently, but denies dyspnea. Recently noticed mild shortness of breath with exertion.',
      pmh: ['Migraine with aura'],
      psh: 'None',
      medications: ['Ethinyl estradiol/norethindrone (OCP)'],
      allergies: 'NKDA',
      social: 'Non-smoker, drinks 2-3 glasses wine per week',
      family: 'Mother with DVT post-surgery age 55',
    },
    physicalExamData: {
      general: 'Well-appearing Latina female, no distress',
      extremities: 'Left calf warm, erythematous, 2 cm diameter increase compared to right; positive Homan sign left',
      cardiovascular: 'Tachycardic (96), regular, no murmurs',
      pulmonary: 'Clear bilaterally, no wheezes or crackles',
      abdomen: 'Soft, non-tender',
    },
    labData: {
      dDimer: '1.8 μg/mL (elevated)',
      doppler: 'Compression ultrasound shows non-compressible left popliteal vein with echogenic material consistent with thrombus',
      ctPa: 'Bilateral pulmonary artery filling defects in segmental branches',
      cbc: 'WBC 9,200/μL, Hgb 13.2 g/dL, Plt 245,000/μL',
    },
    essentialQuestions: [
      'When did the swelling start?',
      'Did you have any recent long flights or immobilization?',
      'Any chest pain or shortness of breath?',
      'Are you on birth control pills?',
      'Any family history of blood clots?',
    ],
    helpfulQuestions: [
      'Any recent surgery or trauma?',
      'Do you have pain or redness in the leg?',
      'Any previous episodes of leg swelling?',
    ],
    unnecessaryQuestions: [
      'What is your favorite type of cuisine?',
      'Do you have any pets at home?',
      'How many hours per day do you work at a desk?',
    ],
    correctDiagnosis: 'Deep Vein Thrombosis with Pulmonary Embolism',
    differentialDiagnoses: ['Cellulitis', 'Baker cyst rupture', 'Superficial thrombophlebitis', 'Lymphedema'],
    idealWorkup: ['D-dimer', 'Compression Doppler ultrasound', 'CT pulmonary angiography', 'CBC', 'BMP', 'Coagulation studies'],
    teachingPoints: [
      'Oral contraceptives increase VTE risk 3-4 fold, especially with migraine with aura',
      'Virchow triad: stasis (immobility), endothelial injury (OCPs), hypercoagulability',
      'D-dimer sensitive but non-specific; compression ultrasound is gold standard for DVT; CT-PA for PE confirmation',
    ],
  },
  {
    id: 'osce-dka',
    patientName: 'Marcus Johnson',
    chiefComplaint: 'Nausea, vomiting, and abdominal pain for 2 days',
    age: 19,
    sex: 'male',
    vitalSigns: {
      bp: '95/60',
      hr: 118,
      rr: 28,
      temp: '98.2°F',
      spo2: '98%',
    },
    historyData: {
      hpi: 'Type 1 diabetic known for 8 years presents with 2 days of progressive nausea, vomiting, and diffuse abdominal pain. Reports polyuria and polydipsia x 48 hours. Ran out of insulin 3 days ago. Denies chest pain, denies focal pain. Progressive malaise and fatigue.',
      pmh: ['Type 1 Diabetes Mellitus x 8 years'],
      psh: 'None',
      medications: ['Insulin aspart (ran out)', 'Insulin glargine (ran out)'],
      allergies: 'NKDA',
      social: 'Non-smoker, lives with family, college student, recently experiencing financial stress',
      family: 'Father with Type 2 DM, mother with autoimmune thyroiditis',
    },
    physicalExamData: {
      general: 'Ill-appearing young male, lethargic',
      heent: 'Dry mucous membranes, fruity breath odor',
      pulmonary: 'Kussmaul respirations (deep, regular, RR 28)',
      cardiovascular: 'Tachycardic, regular, no murmurs, orthostatic vitals (up 20 mmHg systolic drop)',
      abdomen: 'Diffuse tenderness, soft, no rebound/guarding, normal bowel sounds',
    },
    labData: {
      glucose: '485 mg/dL',
      ph: '7.12',
      hco3: '8 mEq/L',
      anionGap: '28 (elevated)',
      ketonesSerum: 'Positive, beta-hydroxybutyrate 6.2 mmol/L',
      ketonesUrine: 'Large',
      cbc: 'WBC 14,200/μL with left shift, Hgb 15.1 g/dL (hemoconcentration)',
      bmp: 'K 6.2 mEq/L (pseudohyperkalemia from cellular shift), Na 128 mEq/L, Cl 104 mEq/L, BUN 32 mg/dL, Cr 1.8 mg/dL',
    },
    essentialQuestions: [
      'Do you have diabetes?',
      'Have you been taking your insulin?',
      'When did this nausea and vomiting start?',
      'Any abdominal pain?',
      'Are you urinating more than usual?',
    ],
    helpfulQuestions: [
      'Have you noticed your breath smelling fruity?',
      'Any recent infections or illness?',
      'Any recent stress or changes in routine?',
    ],
    unnecessaryQuestions: [
      'What is your favorite sports team?',
      'Do you prefer tea or coffee?',
      'Have you traveled outside the country recently?',
    ],
    correctDiagnosis: 'Diabetic Ketoacidosis (DKA)',
    differentialDiagnoses: ['Alcoholic ketoacidosis', 'Sepsis', 'Acute pancreatitis', 'Toxic ingestion (methanol, ethylene glycol)'],
    idealWorkup: ['BMP with electrolytes', 'ABG or VBG', 'CBC', 'Urinalysis', 'Serum and urine ketones', 'Lipase', 'Blood cultures', 'Venous lactate'],
    teachingPoints: [
      'DKA diagnostic criteria: pH <7.3, HCO3 <15, positive serum/urine ketones, anion gap metabolic acidosis',
      'Insulin omission is common precipitant in known T1DM; always assess adherence and access',
      'Kussmaul respirations are compensatory response to metabolic acidosis; fruity breath from acetone',
    ],
  },
  {
    id: 'osce-stroke',
    patientName: 'Dorothy Patterson',
    chiefComplaint: 'Sudden right-sided weakness and slurred speech 90 minutes ago',
    age: 68,
    sex: 'female',
    vitalSigns: {
      bp: '182/98',
      hr: 78,
      rr: 16,
      temp: '98.4°F',
      spo2: '97%',
    },
    historyData: {
      hpi: 'Patient woke 90 minutes ago with sudden onset right-sided facial droop, arm weakness, and slurred speech. Wife reports no prior neurologic deficits. Last known well was at bedtime 3 hours ago. Denies headache, vision changes, or loss of consciousness. No recent falls or head trauma.',
      pmh: ['Atrial fibrillation (not anticoagulated)', 'Hypertension x 15 years', 'Hyperlipidemia'],
      psh: 'Hysterectomy age 48',
      medications: ['Metoprolol 50mg daily', 'Amlodipine 5mg daily', 'Atorvastatin 40mg daily'],
      allergies: 'Aspirin (GI upset)',
      social: 'Former smoker (quit 10 years ago, 25 pack-year history), occasional alcohol',
      family: 'Father with stroke age 70, mother with Afib',
    },
    physicalExamData: {
      general: 'Alert, oriented woman, obvious right facial droop',
      neuro: 'Right-sided weakness (arm 3/5, leg 4/5), facial asymmetry, dysarthria, positive pronator drift right arm, NIHSS ~8-10',
      cardiovascular: 'Irregular rate and rhythm (Afib), BP 182/98',
      pulmonary: 'Clear bilaterally',
    },
    labData: {
      ctHeadNoncontrast: 'No acute intracranial hemorrhage',
      glucose: '110 mg/dL',
      inr: '1.0',
      pt: '12.2 sec',
      cbc: 'WBC 8,900/μL, Hgb 13.8 g/dL',
      bmp: 'Na 138, K 4.2, Cl 104, CO2 24, BUN 20, Cr 1.0',
      ecg: 'Atrial fibrillation with RVR 92',
    },
    essentialQuestions: [
      'When did the weakness start?',
      'Is this sudden onset?',
      'Any facial droop or speech difficulties?',
      'Do you have a heart condition?',
      'Are you on any blood thinners?',
    ],
    helpfulQuestions: [
      'Any recent headache or vision changes?',
      'Do you have high blood pressure?',
      'Any recent chest pain or palpitations?',
    ],
    unnecessaryQuestions: [
      'What color are your eyes?',
      'Do you play any musical instruments?',
      'What year did you graduate high school?',
    ],
    correctDiagnosis: 'Acute Ischemic Stroke (Cardioembolic, secondary to Atrial Fibrillation)',
    differentialDiagnoses: ['Transient Ischemic Attack (TIA)', 'Hemorrhagic stroke', "Todd's paralysis", 'Hypoglycemia'],
    idealWorkup: ['CT head non-contrast STAT', 'Serum glucose', 'CBC', 'BMP', 'PT/INR', 'aPTT', 'ECG', 'CXR', 'Lipid panel', 'MRI brain with DWI/PWI'],
    teachingPoints: [
      'Uncontrolled Afib significantly increases stroke risk; 90-minute window is critical for thrombolytic therapy (tPA)',
      'CT must rule out hemorrhage before thrombolysis; absent aspirin allergy should not prevent acute stroke care',
      'CHA2DS2-VASc score for this patient: C=1, H=1, A2=2, S2=2, V=1 = 7 (very high risk, should be on anticoagulation)',
    ],
  },
  {
    id: 'osce-ectopic',
    patientName: 'Jessica Rivera',
    chiefComplaint: 'Sharp left lower abdominal pain with vaginal spotting',
    age: 28,
    sex: 'female',
    vitalSigns: {
      bp: '98/62',
      hr: 112,
      rr: 20,
      temp: '98.8°F',
      spo2: '99%',
    },
    historyData: {
      hpi: 'Sharp left lower quadrant pain that started acutely 2 hours ago. Associated with light vaginal spotting (dark color). LMP 7 weeks ago, sexually active, not using reliable contraception. Denies nausea/vomiting currently but had 1 episode this morning. Baseline regular menses. Denies fever. Pain 9/10, constant.',
      pmh: ['Prior pelvic inflammatory disease (age 24)', 'Irregular cycles'],
      psh: 'IUD removed 6 months ago (reason: concern for infection)',
      medications: 'None',
      allergies: 'NKDA',
      social: 'Monogamous relationship x 1 year, non-smoker, occasional alcohol',
      family: 'Maternal grandmother with ovarian cancer',
    },
    physicalExamData: {
      general: 'Anxious, pale, writhing in pain',
      abdomen: 'Acute left LQ tenderness, guarding, positive Cullen sign concerning for peritoneal irritation',
      cardiovascular: 'Tachycardic (112), normal rhythm, capillary refill 2 sec, skin cool/diaphoretic',
      pelvis: 'Cervical motion tenderness, left adnexal mass palpable, no cervical discharge noted',
      extremities: 'No cyanosis',
    },
    labData: {
      betaHcg: '3,200 mIU/mL (qualitative positive, quantitative low for 7 weeks)',
      transvaginalUs: 'No intrauterine gestational sac despite positive hCG; left adnexal free fluid with echogenic debris; left tube dilated with heterogeneous contents',
      cbc: 'WBC 11,600/μL, Hgb 10.8 g/dL (lower than expected, suggests hemorrhage)',
      typeAndScreen: 'O-negative, antibody negative',
      bmp: 'Na 138, K 3.8, Cl 102, CO2 22, BUN 22, Cr 0.9',
    },
    essentialQuestions: [
      'When was your last period?',
      'Could you be pregnant?',
      'When did the pain start?',
      'Any vaginal bleeding?',
      'Any fever or chills?',
    ],
    helpfulQuestions: [
      'Is the pain constant or coming and going?',
      'Any shoulder pain?',
      'Any prior pelvic infections?',
    ],
    unnecessaryQuestions: [
      'Do you prefer morning or evening exercise?',
      'What is your favorite color?',
      'Have you traveled internationally recently?',
    ],
    correctDiagnosis: 'Ruptured Ectopic Pregnancy',
    differentialDiagnoses: ['Threatened spontaneous abortion', 'Ovarian torsion', 'Acute appendicitis', 'Ruptured ovarian cyst'],
    idealWorkup: ['Quantitative beta-hCG', 'Transvaginal ultrasound', 'Type and screen', 'CBC', 'BMP', 'RhoGAM if Rh negative', 'CBC trending q2h if stable'],
    teachingPoints: [
      'Ectopic pregnancy risk factors: prior PID, IUD use, tubal scarring; consider in any reproductive-age female with positive hCG',
      'Classic triad: positive pregnancy test, abdominal pain, free fluid on ultrasound with no IUP',
      'Ruptured ectopic is OB/GYN surgical emergency; hemodynamic stability guides expectant vs surgical management',
    ],
  },
  {
    id: 'osce-asthma',
    patientName: 'Tyler Washington',
    chiefComplaint: 'Progressive shortness of breath and wheezing for 6 hours',
    age: 16,
    sex: 'male',
    vitalSigns: {
      bp: '110/70',
      hr: 130,
      rr: 32,
      temp: '98.6°F',
      spo2: '88%',
    },
    historyData: {
      hpi: 'Previously healthy 16-year-old with intermittent asthma (last exacerbation 2 years ago) presents with 6 hours of progressive shortness of breath, diffuse wheezing. Triggered by playing basketball. Tried his albuterol inhaler 2 hours ago, minimal relief. Can only speak 2-3 word phrases due to dyspnea. Denies chest pain, fever, sick contacts. No recent URI.',
      pmh: ['Asthma (intermittent, not on controller therapy)', 'Environmental allergies'],
      psh: 'None',
      medications: ['Albuterol HFA inhaler (as-needed)', 'Loratadine seasonal'],
      allergies: 'NKDA',
      social: 'High school athlete, non-smoker, no substance use',
      family: 'Father with asthma, mother with seasonal allergies',
    },
    physicalExamData: {
      general: 'Anxious teen, using accessory muscles (intercostal, suprasternal retractions)',
      pulmonary: 'Diffuse bilateral wheezing throughout, decreased air movement, prolonged expiratory phase, unable to complete full sentences',
      cardiovascular: 'Tachycardic (130), regular, normal S1/S2',
      extremities: 'Cyanosis of lips and fingertips (SpO2 88%)',
      pulsusParadoxus: 'Present (systolic BP drop >10 mmHg with inspiration)',
    },
    labData: {
      peakFlow: '220 L/min (50-60% predicted for 16M)',
      cxr: 'Hyperinflation, no focal consolidation or pneumothorax',
      abg: 'pH 7.35, pCO2 42 mmHg (normal but abnormal in context of RR 32 - indicates fatigue), pO2 68 mmHg, HCO3 24',
      cbc: 'WBC 7,800/μL, Hgb 14.8 g/dL',
    },
    essentialQuestions: [
      'When did the wheezing start?',
      'What made it worse?',
      'Have you used your rescue inhaler?',
      'Do you have asthma?',
      'Any difficulty breathing at rest?',
    ],
    helpfulQuestions: [
      'Any recent fever, cough, or upper respiratory symptoms?',
      'Any chest pain with breathing?',
      'Have you ever been hospitalized or intubated for asthma?',
    ],
    unnecessaryQuestions: [
      'What is your favorite sports team?',
      'Do you have any siblings?',
      'What grade are you in school?',
    ],
    correctDiagnosis: 'Severe Acute Asthma Exacerbation (Status Asthmaticus)',
    differentialDiagnoses: ['Pneumothorax', 'Foreign body aspiration', 'Anaphylaxis', 'Community-acquired pneumonia'],
    idealWorkup: ['Peak flow', 'CXR (to rule out complications)', 'ABG or VBG', 'CBC', 'Continuous pulse oximetry', 'Albuterol and ipratropium nebulizers', 'Systemic corticosteroids'],
    teachingPoints: [
      'Severe asthma signs: RR >30, SpO2 <90%, inability to speak full sentences, use of accessory muscles, pulsus paradoxus',
      'Normal or elevated pCO2 during asthma exacerbation indicates respiratory muscle fatigue and impending respiratory failure',
      'Oxygen target SpO2 92-95% in asthma; avoid high-flow oxygen which may reduce respiratory drive',
    ],
  },
  {
    id: 'osce-urosepsis',
    patientName: 'Helen Crawford',
    chiefComplaint: 'Confusion, fever, and flank pain for 2 days',
    age: 78,
    sex: 'female',
    vitalSigns: {
      bp: '88/52',
      hr: 110,
      rr: 24,
      temp: '103.4°F',
      spo2: '94%',
    },
    historyData: {
      hpi: 'Elderly female with recurrent UTIs presents with 2 days of fever, left flank pain, and acute onset confusion. Daughter reports patient was independent yesterday but now disoriented to time/place. Weak, minimal oral intake. Denies dysuria or urinary frequency specifically noted, but has had recent UTI-like symptoms intermittently. Lives in assisted living facility.',
      pmh: ['Type 2 Diabetes Mellitus', 'Chronic Kidney Disease stage 3 (baseline Cr 1.6)', 'Recurrent UTIs (4-5 per year)', 'HTN', 'Osteoarthritis'],
      psh: 'Cholecystectomy age 60',
      medications: ['Metformin 500mg BID', 'Lisinopril 10mg daily', 'Amlodipine 5mg daily', 'Aspirin 81mg daily'],
      allergies: 'Sulfa drugs (rash)',
      social: 'Widow, lives in assisted living, former teacher, non-smoker',
      family: 'Daughter in area, son lives out of state',
    },
    physicalExamData: {
      general: 'Elderly frail female, lethargic, confused about date and location',
      heent: 'Dry mucous membranes, icteric sclera',
      cardiovascular: 'Tachycardic (110), regular, hypotensive (88/52), decreased capillary refill (3 sec)',
      pulmonary: 'Tachypneic (24), clear bilaterally',
      abdomen: 'Left costovertebral angle (CVA) tenderness, mild suprapubic tenderness, soft, no rebound/guarding',
      extremities: 'Cool, mottled skin; delayed capillary refill',
      neuro: 'Disoriented to time and place, not following commands consistently, pupils reactive',
    },
    labData: {
      ua: 'Leukocyte esterase positive, nitrites positive, WBC 50-100/hpf, bacteria present, RBC 5-10/hpf',
      uaCulture: 'Pending (presumed >100,000 CFU/mL)',
      bloodCultures: 'x2 obtained, pending (likely gram-negative rod)',
      cbc: 'WBC 16,200/μL with left shift, Hgb 9.8 g/dL (chronic anemia), Plt 98,000/μL (mild thrombocytopenia)',
      bmp: 'Na 132 mEq/L (hyponatremia), K 5.8 mEq/L, Cl 98 mEq/L, CO2 18 mEq/L (low), BUN 42 mg/dL, Cr 2.4 mg/dL (acute on chronic)',
      lactate: '4.2 mmol/L (elevated, suggests tissue hypoperfusion)',
      procalcitonin: '8.6 ng/mL (markedly elevated, supports bacterial infection)',
    },
    essentialQuestions: [
      'How long have you had the fever?',
      'Any pain when you urinate?',
      'Where is the pain?',
      'Have you been confused or forgetful?',
      'Do you have a history of urinary tract infections?',
    ],
    helpfulQuestions: [
      'Any nausea, vomiting, or diarrhea?',
      'Any recent antibiotic use?',
      'Any difficulty with urination?',
    ],
    unnecessaryQuestions: [
      'What was your favorite vacation destination?',
      'How many grandchildren do you have?',
      'Do you prefer tea or coffee?',
    ],
    correctDiagnosis: 'Urosepsis (Complicated Urinary Tract Infection with Sepsis)',
    differentialDiagnoses: ['Nephrolithiasis with obstruction', 'Pyelonephritis without sepsis', 'Intra-abdominal abscess', 'Meningitis'],
    idealWorkup: ['Urinalysis with culture', 'Blood cultures x2 before antibiotics', 'CBC', 'BMP', 'Lactate', 'Procalcitonin', 'CT abdomen/pelvis (concern for obstruction)', 'ECG'],
    teachingPoints: [
      'Elderly present atypically: delirium is sentinel sign in UTI/sepsis; may lack fever or dysuria',
      'Sepsis criteria: SIRS + suspected infection; qSOFA score positive (altered mental status, SBP <100, RR >22)',
      'Early recognition and aggressive fluid resuscitation critical; lactate >4 associated with increased mortality',
    ],
  },
  {
    id: 'osce-chf',
    patientName: 'William Foster',
    chiefComplaint: 'Worsening shortness of breath for 1 week with weight gain',
    age: 65,
    sex: 'male',
    vitalSigns: {
      bp: '158/94',
      hr: 96,
      rr: 28,
      temp: '98.4°F',
      spo2: '90%',
    },
    historyData: {
      hpi: 'Known heart failure (EF 30% on last echo 6 months ago) with 1 week of progressive dyspnea, worst at night (orthopnea requiring 3 pillows). Notes 10 lb weight gain in past 10 days. Reports increased lower extremity swelling bilaterally. Denies chest pain or palpitations. Mild cough, no hemoptysis.',
      pmh: ['Systolic Heart Failure (EF 30%, ischemic etiology from prior MI)', 'Type 2 Diabetes', 'Hypertension', 'Hyperlipidemia', 'CKD stage 2 (baseline Cr 1.2)'],
      psh: 'CABG 2008',
      medications: ['Carvedilol 12.5mg BID', 'Lisinopril 20mg daily', 'Furosemide 40mg daily', 'Spironolactone 25mg daily', 'Atorvastatin 80mg daily', 'Metformin 1000mg daily'],
      allergies: 'NKDA',
      social: 'Retired accountant, widow, lives alone, non-smoker, denies alcohol',
      family: 'Son lives 2 hours away, daughter lives out of state',
    },
    physicalExamData: {
      general: 'Elderly male, slightly dyspneic at rest',
      heent: 'JVD present at 8 cm with positive hepatojugular reflex',
      pulmonary: 'Bilateral crackles mid-lung fields, no wheezes, respiratory effort elevated',
      cardiovascular: 'Regular rate and rhythm (HR 96), S3 gallop audible, no murmurs',
      abdomen: 'Hepatomegaly (liver palpable 2 cm below costal margin), soft, non-tender, no ascites',
      extremities: '3+ bilateral pitting edema to knee level; skin cool, no cyanosis; dorsalis pedis pulses 1+ bilaterally',
    },
    labData: {
      bnp: '680 pg/mL (significantly elevated; >400 suggests decompensation)',
      bmp: 'Na 138, K 5.2, Cl 102, CO2 24, BUN 28, Cr 1.4 (acute rise from baseline 1.2)',
      cbc: 'WBC 8,200/μL, Hgb 12.8 g/dL, Plt 220,000/μL',
      cxr: 'Pulmonary edema with bilateral interstitial and alveolar infiltrates; Kerley B lines; enlarged cardiac silhouette',
      ecg: 'Sinus rhythm, rate 96, LBBB pattern (unchanged from prior), no acute ST changes',
      troponin: '0.02 ng/mL (normal, rules out ACS)',
    },
    essentialQuestions: [
      'When did the shortness of breath start?',
      'What makes it worse - lying flat?',
      'How much weight have you gained?',
      'Do you have swelling in your legs?',
      'Have you had heart failure before?',
    ],
    helpfulQuestions: [
      'Any chest pain or pressure?',
      'Any palpitations or irregular heartbeat?',
      'Have you been able to take your medications regularly?',
    ],
    unnecessaryQuestions: [
      'Do you prefer watching movies or reading?',
      'What is your favorite restaurant?',
      'Do you have any hobbies?',
    ],
    correctDiagnosis: 'Acute Decompensated Heart Failure (ADHF, systolic dysfunction)',
    differentialDiagnoses: ['Community-acquired pneumonia', 'COPD exacerbation', 'Pulmonary embolism', 'Acute coronary syndrome'],
    idealWorkup: ['BNP or NT-proBNP', 'BMP with renal function', 'CBC', 'CXR', 'ECG', 'Troponin', 'Echocardiography', 'Urinalysis'],
    teachingPoints: [
      'Systolic vs diastolic HF: EF 30% is systolic; treatment includes ACE-I, beta-blocker, aldosterone antagonist, diuretics',
      'Acute decompensation triggers: non-adherence, dietary sodium, renal disease progression, arrhythmia, ACS; address underlying cause',
      'Worsening renal function common in HF; must balance diuresis with perfusion; cautious with beta-blockers/ACE-I during decompensation',
    ],
  },
];

async function main() {
  console.log('Seeding OSCE cases...');

  for (const caseData of osceCases) {
    await prisma.patientEncounterCase.upsert({
      where: { id: caseData.id },
      update: { ...caseData, updatedAt: new Date() },
      create: { ...caseData, updatedAt: new Date() },
    });
    console.log(`✓ Created/updated case: ${caseData.patientName}`);
  }

  console.log(`\n✅ Seeded ${osceCases.length} OSCE cases`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
