
import fs from "fs";
import path from "path";
import { CONDITION_REGISTRY_ADDITIONAL } from "../conditionRegistry";

const OUTPUT_FILE = path.resolve("conditionContent.generated.json");

function toSlug(text: string): string {
  return text.toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z0-9_]/g, "");
}

function buildConditionId(system: string, subcategory: string, condition: string): string {
  return `${system}__${toSlug(subcategory)}__${toSlug(condition)}`;
}

// Hardcoded content generated by AI Assistant
const GENERATED_CONTENT: Record<string, any> = {
  "Long QT Syndrome": {
    overview: "Long QT Syndrome (LQTS) is a disorder of myocardial repolarization characterized by a prolonged QT interval on ECG, predisposing patients to malignant ventricular arrhythmias, specifically Torsades de Pointes, and sudden cardiac death.",
    etiologyPathophysiology: "Can be congenital (genetic channelopathies affecting K+ or Na+ channels) or acquired (drug-induced, electrolyte imbalances like hypokalemia/hypomagnesemia). Prolonged repolarization allows for early afterdepolarizations (EADs) to trigger arrhythmias.",
    epidemiology: "Congenital forms affect ~1 in 2000. Acquired is common in hospitalized patients.",
    riskFactors: ["Family history of sudden death", "QT-prolonging medications (macrolides, fluoroquinolones, antipsychotics, antiemetics)", "Electrolyte abnormalities", "Female gender"],
    clinicalPresentation: "Often asymptomatic until a cardiac event. May present with syncope (often during exercise or emotional stress), seizures, or cardiac arrest.",
    symptoms: ["Syncope", "Palpitations", "Seizures", "Cardiac arrest"],
    examFindings: ["Usually normal physical exam", "Congenital deafness in Jervell and Lange-Nielsen syndrome"],
    diagnostics: {
      notes: "ECG is gold standard: QTc > 440ms (men) or > 460ms (women). Genetic testing for congenital forms."
    },
    treatment: ["Beta-blockers (Nadolol, Propranolol) are first-line", "ICD for high-risk patients", "Avoid QT-prolonging drugs"],
    management: ["Lifestyle modification (avoid strenuous swimming/exercise if LQT1)", "Correction of electrolytes"],
    complications: ["Torsades de Pointes", "Ventricular Fibrillation", "Sudden Cardiac Death"],
    prognosis: "Good with treatment, but risk of sudden death remains if untreated."
  },
  "Wolff-Parkinson-White Syndrome": {
    overview: "WPW is a pre-excitation syndrome caused by an accessory pathway (Bundle of Kent) that bypasses the AV node, directly connecting atria and ventricles.",
    etiologyPathophysiology: "Congenital accessory pathway conducts impulses faster than the AV node, leading to pre-excitation. Can lead to AVRT (re-entrant tachycardia) or rapid conduction of AFib.",
    epidemiology: "Prevalence 0.1-0.3%. More common in males.",
    riskFactors: ["Ebstein's anomaly", "Family history"],
    clinicalPresentation: "Palpitations, lightheadedness, syncope. Can present with SVT or AFib.",
    symptoms: ["Palpitations", "Dizziness", "Syncope", "Chest pain"],
    examFindings: ["Normal between episodes", "Tachycardia during episodes"],
    diagnostics: {
      notes: "ECG: Short PR interval (<120ms), Delta wave (slurred upstroke of QRS), Wide QRS."
    },
    treatment: ["Unstable: Cardioversion", "Stable Orthodromic AVRT: Vagal maneuvers, Adenosine", "Stable Antidromic/AFib: Procainamide"],
    management: ["Radiofrequency catheter ablation is curative and first-line for symptomatic patients."],
    complications: ["Sudden Cardiac Death (rare)", "Atrial Fibrillation with rapid ventricular response"],
    prognosis: "Excellent with ablation."
  },
  "Pericardial Effusion": {
    overview: "Accumulation of excess fluid in the pericardial sac.",
    etiologyPathophysiology: "Causes include pericarditis (viral, idiopathic), malignancy, uremia, trauma, autoimmune disease. Rapid accumulation can lead to tamponade.",
    epidemiology: "Depends on underlying cause.",
    riskFactors: ["Pericarditis", "Malignancy", "Renal failure", "Trauma"],
    clinicalPresentation: "Dyspnea, chest pain (pleuritic), cough. Symptoms depend on size and rate of accumulation.",
    symptoms: ["Dyspnea", "Chest pain", "Fatigue"],
    examFindings: ["Muffled heart sounds", "Friction rub (if pericarditis)", "Ewart's sign (dullness at left scapular tip)"],
    diagnostics: {
      notes: "Echocardiogram is diagnostic. ECG may show low voltage and electrical alternans."
    },
    treatment: ["Treat underlying cause", "Pericardiocentesis if large or symptomatic", "Pericardial window for recurrent"],
    management: ["Serial echos to monitor size"],
    complications: ["Cardiac Tamponade"],
    prognosis: "Depends on etiology."
  },
  "Hypertensive Retinopathy": {
    overview: "Retinal vascular damage caused by hypertension.",
    etiologyPathophysiology: "Chronic high BP causes arteriosclerosis, vessel narrowing, and leakage.",
    epidemiology: "Correlates with duration and severity of HTN.",
    riskFactors: ["Poorly controlled hypertension", "Diabetes", "Smoking"],
    clinicalPresentation: "Usually asymptomatic until severe. Blurred vision or scotoma in advanced disease.",
    symptoms: ["Vision changes", "Headache"],
    examFindings: ["AV nicking", "Copper/Silver wiring", "Cotton wool spots", "Flame hemorrhages", "Papilledema (Grade 4)"],
    diagnostics: {
      notes: "Fundoscopic exam."
    },
    treatment: ["Control blood pressure"],
    management: ["Regular eye exams", "Strict BP control"],
    complications: ["Vision loss", "Retinal vein occlusion", "Associated with increased stroke risk"],
    prognosis: "Reversible with BP control, but chronic changes may persist."
  },
  "COPD Exacerbation": {
    overview: "Acute worsening of respiratory symptoms in a patient with COPD.",
    etiologyPathophysiology: "Triggers: Infection (viral/bacterial), pollution, non-compliance. Inflammation leads to bronchoconstriction and mucus hypersecretion.",
    epidemiology: "Common cause of hospitalization in COPD patients.",
    riskFactors: ["Smoking", "Severe COPD", "History of exacerbations"],
    clinicalPresentation: "Increased dyspnea, increased sputum volume/purulence, wheezing.",
    symptoms: ["Dyspnea", "Cough", "Sputum production", "Wheezing"],
    examFindings: ["Wheezing", "Tachypnea", "Use of accessory muscles", "Tripod position", "Cyanosis"],
    diagnostics: {
      notes: "Clinical diagnosis. CXR to rule out pneumonia. ABG for hypoxia/hypercapnia."
    },
    treatment: ["Oxygen (target 88-92%)", "Bronchodilators (Albuterol/Ipratropium)", "Systemic Steroids (Prednisone)", "Antibiotics if indicated (increased sputum purulence/volume)"],
    management: ["Smoking cessation", "Pulmonary rehab", "Vaccinations"],
    complications: ["Respiratory failure", "Intubation", "Death"],
    prognosis: "Recurrent exacerbations worsen lung function decline."
  },
  "Healed Primary TB": {
    overview: "Latent or resolved primary tuberculosis infection.",
    etiologyPathophysiology: "Mycobacterium tuberculosis infection contained by granulomas.",
    epidemiology: "Global prevalence high.",
    riskFactors: ["Exposure to active TB"],
    clinicalPresentation: "Asymptomatic.",
    symptoms: ["None"],
    examFindings: ["Normal"],
    diagnostics: {
      notes: "CXR: Ghon complex (calcified hilar node + granuloma) or Ranke complex."
    },
    treatment: ["None if healed and not latent (check IGRA/PPD)"],
    management: ["Monitor for reactivation if immunocompromised"],
    complications: ["Reactivation TB"],
    prognosis: "Good."
  },
  "Sigmoid Volvulus": {
    overview: "Torsion of the sigmoid colon around its mesentery, causing obstruction and ischemia.",
    etiologyPathophysiology: "Redundant sigmoid colon twists. Associated with chronic constipation.",
    epidemiology: "Elderly, institutionalized patients, neuropsychiatric conditions.",
    riskFactors: ["Chronic constipation", "High fiber diet (in some populations)", "Chagas disease"],
    clinicalPresentation: "Abdominal pain, distension, obstipation, nausea/vomiting.",
    symptoms: ["Severe abdominal pain", "Vomiting", "Constipation"],
    examFindings: ["Massive abdominal distension", "Tympany", "Empty rectal vault"],
    diagnostics: {
      notes: "Abdominal XR: 'Coffee bean' sign or 'Bent inner tube' sign. CT scan confirms."
    },
    treatment: ["Flexible sigmoidoscopy for detorsion (if no peritonitis)", "Surgery (sigmoidectomy) if gangrene or recurrence"],
    management: ["Elective resection often recommended after detorsion due to high recurrence"],
    complications: ["Bowel ischemia", "Perforation", "Sepsis"],
    prognosis: "Good if treated early; high mortality with gangrene."
  },
  "Ischemic Colitis": {
    overview: "Inflammation and injury of the large intestine result from inadequate blood supply.",
    etiologyPathophysiology: "Transient hypoperfusion (watershed areas like Splenic flexure). Not usually embolic.",
    epidemiology: "Elderly >60.",
    riskFactors: ["Hypotension", "Vascular disease", "Dehydration", "Strenuous exercise"],
    clinicalPresentation: "Sudden onset mild abdominal pain (LLQ) followed by bloody diarrhea.",
    symptoms: ["Crampy LLQ pain", "Bloody diarrhea", "Urgency"],
    examFindings: ["Mild LLQ tenderness", "Rectal bleeding"],
    diagnostics: {
      notes: "CT: Bowel wall thickening. Colonoscopy: Pale mucosa, petechial bleeding. XR: 'Thumbprinting'."
    },
    treatment: ["Supportive: IV fluids, bowel rest", "Antibiotics", "Surgery if gangrene/perforation"],
    management: ["Optimize cardiovascular status"],
    complications: ["Stricture", "Gangrene", "Perforation"],
    prognosis: "Most resolve spontaneously."
  },
  "Duodenal Atresia": {
    overview: "Congenital complete obstruction of the duodenum.",
    etiologyPathophysiology: "Failure of recanalization of the duodenum during embryogenesis.",
    epidemiology: "1 in 5000 births. Associated with Down Syndrome (Trisomy 21).",
    riskFactors: ["Down Syndrome", "Polyhydramnios"],
    clinicalPresentation: "Bilious vomiting in the first day of life.",
    symptoms: ["Bilious vomiting", "Abdominal distension"],
    examFindings: ["Scaphoid abdomen (if distal gas absent)", "Dehydration"],
    diagnostics: {
      notes: "Abdominal XR: 'Double bubble' sign (gas in stomach and proximal duodenum)."
    },
    treatment: ["NG tube decompression", "IV fluids", "Surgical repair (Duodenoduodenostomy)"],
    management: ["Screen for other anomalies"],
    complications: ["Electrolyte imbalance", "Surgical complications"],
    prognosis: "Excellent with surgery."
  },
  "Portal Hypertension": {
    overview: "Elevated pressure in the portal venous system.",
    etiologyPathophysiology: "Most commonly cirrhosis (intrahepatic resistance). Can be pre-hepatic (portal vein thrombosis) or post-hepatic (Budd-Chiari).",
    epidemiology: "Follows liver disease prevalence.",
    riskFactors: ["Cirrhosis", "Alcohol use", "Hepatitis B/C"],
    clinicalPresentation: "Ascites, variceal bleeding, splenomegaly, encephalopathy.",
    symptoms: ["Abdominal swelling", "Hematemesis", "Confusion"],
    examFindings: ["Ascites", "Caput medusae", "Splenomegaly", "Asterixis"],
    diagnostics: {
      notes: "Ultrasound, CT. HVPG measurement is gold standard but invasive."
    },
    treatment: ["Non-selective beta-blockers (Nadolol)", "TIPS procedure", "Treat underlying liver disease"],
    management: ["Variceal screening", "Sodium restriction"],
    complications: ["Variceal hemorrhage", "Spontaneous Bacterial Peritonitis (SBP)", "Hepatorenal syndrome"],
    prognosis: "Depends on liver function (MELD score)."
  },
  "GI Malignancy": {
    overview: "Cancers of the gastrointestinal tract (Esophagus, Stomach, Colon, Pancreas, Liver).",
    etiologyPathophysiology: "Genetic mutations, environmental factors.",
    epidemiology: "Increases with age.",
    riskFactors: ["Smoking", "Alcohol", "Obesity", "Family history", "Inflammatory bowel disease"],
    clinicalPresentation: "Weight loss, anorexia, bleeding, obstruction.",
    symptoms: ["Weight loss", "Fatigue", "Abdominal pain", "Change in bowel habits"],
    examFindings: ["Mass", "Cachexia", "Sister Mary Joseph nodule (umbilical met)", "Virchow's node (supraclavicular)"],
    diagnostics: {
      notes: "Endoscopy/Colonoscopy with biopsy. CT for staging."
    },
    treatment: ["Surgery", "Chemotherapy", "Radiation"],
    management: ["Surveillance"],
    complications: ["Metastasis", "Obstruction", "Perforation"],
    prognosis: "Varies by stage and type."
  },
  "Gastric Outlet Obstruction": {
    overview: "Mechanical obstruction of the pylorus or duodenum.",
    etiologyPathophysiology: "PUD (scarring/edema), Gastric cancer, Pancreatic cancer.",
    epidemiology: "Associated with PUD and malignancy.",
    riskFactors: ["Chronic ulcers", "Smoking", "Malignancy"],
    clinicalPresentation: "Non-bilious vomiting (undigested food), early satiety, weight loss.",
    symptoms: ["Vomiting", "Epigastric pain", "Weight loss"],
    examFindings: ["Succussion splash", "Epigastric distension"],
    diagnostics: {
      notes: "EGD (Upper Endoscopy) is diagnostic. CT scan."
    },
    treatment: ["NG decompression", "IV fluids/electrolytes", "Endoscopic dilation", "Surgery"],
    management: ["Treat H. pylori if present"],
    complications: ["Electrolyte abnormalities (Hypokalemic hypochloremic metabolic alkalosis)", "Aspiration"],
    prognosis: "Good if benign; poor if malignant."
  },
  "Esophageal Ring": {
    overview: "Thin, web-like constriction in the distal esophagus.",
    etiologyPathophysiology: "Schatzki ring is located at the GE junction. Associated with hiatal hernia and GERD.",
    epidemiology: "Common cause of intermittent dysphagia.",
    riskFactors: ["GERD", "Hiatal hernia"],
    clinicalPresentation: "Intermittent dysphagia to solids (especially large boluses like steak - 'Steakhouse Syndrome').",
    symptoms: ["Dysphagia to solids", "Food impaction"],
    examFindings: ["Normal"],
    diagnostics: {
      notes: "Barium swallow (esophagram) is most sensitive. EGD."
    },
    treatment: ["Endoscopic dilation", "Chew food well"],
    management: ["Treat GERD"],
    complications: ["Food impaction"],
    prognosis: "Excellent."
  },
  "Diffuse Esophageal Spasm": {
    overview: "Motility disorder characterized by simultaneous, uncoordinated contractions of the esophagus.",
    etiologyPathophysiology: "Impaired inhibitory innervation.",
    epidemiology: "Uncommon.",
    riskFactors: ["Anxiety", "GERD"],
    clinicalPresentation: "Chest pain (mimics angina) and dysphagia to solids and liquids.",
    symptoms: ["Retrosternal chest pain", "Dysphagia"],
    examFindings: ["Normal"],
    diagnostics: {
      notes: "Manometry: Simultaneous contractions. Barium swallow: 'Corkscrew esophagus'."
    },
    treatment: ["Calcium channel blockers", "Nitrates", "TCA", "Botox"],
    management: ["Reassurance"],
    complications: ["Weight loss", "Aspiration"],
    prognosis: "Chronic but benign."
  },
  "Increased Intracranial Pressure": {
    overview: "Elevated pressure within the cranium.",
    etiologyPathophysiology: "Mass effect (tumor, bleed), edema, increased CSF (hydrocephalus). Monro-Kellie doctrine: fixed volume.",
    epidemiology: "Trauma, tumors.",
    riskFactors: ["Head trauma", "Brain tumor", "Meningitis"],
    clinicalPresentation: "Headache (worse lying down/morning), vomiting, altered mental status.",
    symptoms: ["Headache", "Nausea/Vomiting", "Visual changes"],
    examFindings: ["Papilledema", "Cushing's Triad (HTN, Bradycardia, Irregular respirations)", "Uncal herniation signs (blown pupil)"],
    diagnostics: {
      notes: "CT Head. LP is contraindicated if mass effect."
    },
    treatment: ["Elevate head of bed", "Hyperventilation (acute)", "Mannitol/Hypertonic saline", "Surgery (decompression/shunt)"],
    management: ["ICP monitoring"],
    complications: ["Herniation", "Brain death"],
    prognosis: "Poor if untreated."
  },
  "Basilar Skull Fracture": {
    overview: "Fracture of the base of the skull.",
    etiologyPathophysiology: "Significant blunt force trauma.",
    epidemiology: "Trauma victims.",
    riskFactors: ["MVA", "Falls"],
    clinicalPresentation: "Head trauma signs.",
    symptoms: ["Headache", "Hearing loss", "CSF leak"],
    examFindings: ["Battle sign (retroauricular ecchymosis)", "Raccoon eyes (periorbital ecchymosis)", "Hemotympanum", "CSF rhinorrhea/otorrhea"],
    diagnostics: {
      notes: "CT Head (bone window)."
    },
    treatment: ["Observation", "Neurosurgery consult", "Antibiotics (controversial)"],
    management: ["Avoid NG tube"],
    complications: ["Meningitis", "Cranial nerve palsies"],
    prognosis: "Depends on underlying brain injury."
  },
  "Upper Motor Neuron Lesion": {
    overview: "Damage to the neural pathway above the anterior horn cell (Brain or Spinal Cord).",
    etiologyPathophysiology: "Stroke, MS, Tumor, Trauma, B12 deficiency.",
    epidemiology: "Varies.",
    riskFactors: ["Vascular disease", "Trauma"],
    clinicalPresentation: "Weakness, spasticity.",
    symptoms: ["Weakness", "Stiffness"],
    examFindings: ["Hyperreflexia", "Increased tone (spasticity)", "Positive Babinski sign", "Pronator drift", "No fasciculations"],
    diagnostics: {
      notes: "MRI Brain/Spine."
    },
    treatment: ["Treat underlying cause", "PT/OT", "Baclofen for spasticity"],
    management: ["Rehab"],
    complications: ["Contractures"],
    prognosis: "Variable."
  },
  "Peroneal Nerve Palsy": {
    overview: "Compression of the common peroneal nerve at the fibular head.",
    etiologyPathophysiology: "Compression (crossing legs, cast), trauma.",
    epidemiology: "Common neuropathy.",
    riskFactors: ["Crossing legs", "Knee injury", "Rapid weight loss"],
    clinicalPresentation: "Foot drop, numbness on dorsum of foot.",
    symptoms: ["Tripping", "Weakness lifting foot"],
    examFindings: ["Weakness of dorsiflexion and eversion", "Steppage gait", "Sensory loss first web space"],
    diagnostics: {
      notes: "Clinical. EMG/NCS if chronic."
    },
    treatment: ["Ankle-Foot Orthosis (AFO)", "Avoid compression"],
    management: ["PT"],
    complications: ["Permanent weakness"],
    prognosis: "Good recovery often."
  },
  "Radial Nerve Palsy": {
    overview: "Compression of the radial nerve ('Saturday Night Palsy').",
    etiologyPathophysiology: "Compression at the spiral groove (humerus).",
    epidemiology: "Alcohol intoxication, humeral fracture.",
    riskFactors: ["Sleeping on arm", "Humeral shaft fracture"],
    clinicalPresentation: "Wrist drop.",
    symptoms: ["Weakness extending wrist/fingers", "Numbness dorsal hand"],
    examFindings: ["Wrist drop", "Weakness of wrist/finger extension", "Triceps spared (if lesion distal)"],
    diagnostics: {
      notes: "Clinical."
    },
    treatment: ["Splinting (Cock-up wrist splint)", "PT"],
    management: ["Avoid compression"],
    complications: ["Permanent weakness"],
    prognosis: "Good recovery (weeks to months)."
  },
  "Ulnar Nerve Palsy": {
    overview: "Compression of the ulnar nerve (Cubital Tunnel Syndrome).",
    etiologyPathophysiology: "Compression at the elbow.",
    epidemiology: "Common.",
    riskFactors: ["Leaning on elbows", "Elbow fracture"],
    clinicalPresentation: "Numbness in 4th/5th digits, hand weakness.",
    symptoms: ["Numbness small finger", "Weak grip"],
    examFindings: ["Claw hand (late)", "Positive Tinel's at elbow", "Froment's sign"],
    diagnostics: {
      notes: "EMG/NCS."
    },
    treatment: ["Elbow padding", "Surgery (transposition)"],
    management: ["Avoid pressure"],
    complications: ["Muscle atrophy"],
    prognosis: "Variable."
  },
  "Median Nerve Palsy": {
    overview: "Compression of the median nerve (Carpal Tunnel Syndrome is distal; Pronator syndrome is proximal).",
    etiologyPathophysiology: "Compression.",
    epidemiology: "Common.",
    riskFactors: ["Repetitive use", "Pregnancy", "Hypothyroidism"],
    clinicalPresentation: "Numbness thumb/index/middle fingers.",
    symptoms: ["Night pain", "Numbness", "Weakness"],
    examFindings: ["Thenar atrophy ('Ape hand')", "Positive Phalen's/Tinel's"],
    diagnostics: {
      notes: "EMG/NCS."
    },
    treatment: ["Splinting", "Steroid injection", "Surgery (release)"],
    management: ["Ergonomics"],
    complications: ["Permanent sensory/motor loss"],
    prognosis: "Good with treatment."
  },
  "Guillain-Barré Syndrome": {
    overview: "Acute inflammatory demyelinating polyradiculoneuropathy (AIDP).",
    etiologyPathophysiology: "Autoimmune attack on myelin after infection (Campylobacter, viral).",
    epidemiology: "Rare.",
    riskFactors: ["Recent GI/Respiratory infection", "Campylobacter jejuni"],
    clinicalPresentation: "Ascending symmetric weakness/paralysis, areflexia.",
    symptoms: ["Leg weakness", "Paresthesias", "Dyspnea (late)"],
    examFindings: ["Absent deep tendon reflexes", "Symmetric weakness"],
    diagnostics: {
      notes: "LP: Albuminocytologic dissociation (High protein, normal WBC)."
    },
    treatment: ["IVIG or Plasmapheresis", "Supportive care (ventilator)"],
    management: ["ICU monitoring"],
    complications: ["Respiratory failure", "Autonomic instability"],
    prognosis: "Most recover, but can take months."
  },
  "Neurofibromatosis": {
    overview: "Genetic disorder causing tumors on nerve tissue (NF1 and NF2).",
    etiologyPathophysiology: "Autosomal dominant mutation.",
    epidemiology: "1 in 3000.",
    riskFactors: ["Family history"],
    clinicalPresentation: "Skin changes, tumors.",
    symptoms: ["Skin spots", "Lumps"],
    examFindings: ["Café-au-lait spots (>6)", "Axillary freckling", "Lisch nodules (iris)", "Neurofibromas"],
    diagnostics: {
      notes: "Clinical criteria. Genetic testing. MRI."
    },
    treatment: ["Symptomatic", "Surgery for tumors"],
    management: ["Annual surveillance"],
    complications: ["Malignant transformation", "Optic glioma"],
    prognosis: "Variable."
  },
  "Tuberous Sclerosis": {
    overview: "Genetic disorder causing benign tumors in multiple organs.",
    etiologyPathophysiology: "Autosomal dominant mutation (TSC1/TSC2).",
    epidemiology: "Rare.",
    riskFactors: ["Family history"],
    clinicalPresentation: "Seizures, skin lesions, developmental delay.",
    symptoms: ["Seizures", "Skin bumps"],
    examFindings: ["Ash leaf spots (hypopigmented)", "Shagreen patch", "Adenoma sebaceum (facial angiofibromas)"],
    diagnostics: {
      notes: "MRI Brain. Skin exam (Wood's lamp)."
    },
    treatment: ["Antiepileptics", "mTOR inhibitors"],
    management: ["Multidisciplinary care"],
    complications: ["Epilepsy", "Renal tumors"],
    prognosis: "Normal life expectancy for many."
  },
  "Erythema Multiforme": {
    overview: "Acute, self-limiting type IV hypersensitivity reaction.",
    etiologyPathophysiology: "Most common trigger: HSV infection. Also drugs (sulfa, phenytoin).",
    epidemiology: "Young adults.",
    riskFactors: ["HSV infection", "Medications"],
    clinicalPresentation: "Target lesions on extremities.",
    symptoms: ["Rash", "Itching"],
    examFindings: ["Target (iris) lesions: three concentric zones", "Negative Nikolsky sign"],
    diagnostics: {
      notes: "Clinical."
    },
    treatment: ["Symptomatic (antihistamines)", "Treat HSV (Acyclovir)"],
    management: ["Stop offending drug"],
    complications: ["Major form involves mucosa (SJS spectrum)"],
    prognosis: "Resolves in 2-4 weeks."
  },
  "Molluscum Contagiosum": {
    overview: "Viral skin infection causing pearly papules.",
    etiologyPathophysiology: "Poxvirus infection.",
    epidemiology: "Children, sexually active adults, immunocompromised.",
    riskFactors: ["Contact", "Atopic dermatitis"],
    clinicalPresentation: "Painless bumps.",
    symptoms: ["Bumps"],
    examFindings: ["Flesh-colored, dome-shaped, umbilicated papules"],
    diagnostics: {
      notes: "Clinical."
    },
    treatment: ["Self-limiting", "Cryotherapy", "Curettage"],
    management: ["Avoid sharing towels"],
    complications: ["Secondary infection"],
    prognosis: "Resolves spontaneously (months to years)."
  },
  "Tinea Versicolor": {
    overview: "Fungal skin infection causing pigment changes.",
    etiologyPathophysiology: "Malassezia furfur (yeast) overgrowth.",
    epidemiology: "Hot, humid climates.",
    riskFactors: ["Sweating", "Oily skin"],
    clinicalPresentation: "Hypo- or hyperpigmented patches on trunk.",
    symptoms: ["Discolored patches", "Mild itch"],
    examFindings: ["Scaly patches that do not tan"],
    diagnostics: {
      notes: "KOH prep: 'Spaghetti and meatballs' (hyphae and spores)."
    },
    treatment: ["Topical antifungals (Selenium sulfide, Ketoconazole)"],
    management: ["Prophylaxis if recurrent"],
    complications: ["Recurrence"],
    prognosis: "Good, but pigment takes time to return."
  },
  "Asplenia": {
    overview: "Absence of normal spleen function.",
    etiologyPathophysiology: "Surgical (trauma) or functional (Sickle Cell).",
    epidemiology: "Post-splenectomy.",
    riskFactors: ["Trauma", "Sickle Cell Disease"],
    clinicalPresentation: "Increased risk of encapsulated bacteria.",
    symptoms: ["None directly"],
    examFindings: ["Surgical scar"],
    diagnostics: {
      notes: "Peripheral smear: Howell-Jolly bodies."
    },
    treatment: ["Vaccinations (Pneumococcal, Meningococcal, Hib)", "Prophylactic antibiotics (penicillin) in children"],
    management: ["Fever precautions"],
    complications: ["Overwhelming Post-Splenectomy Infection (OPSI)"],
    prognosis: "Good with precautions."
  },
  "Microangiopathic Hemolytic Anemia": {
    overview: "Hemolysis caused by shearing of RBCs in small vessels.",
    etiologyPathophysiology: "TTP, HUS, DIC. Thrombi in microvasculature shear RBCs.",
    epidemiology: "Varies.",
    riskFactors: ["Infection (E. coli O157:H7)", "Drugs", "Pregnancy"],
    clinicalPresentation: "Anemia, thrombocytopenia, renal failure.",
    symptoms: ["Fatigue", "Bleeding", "Confusion"],
    examFindings: ["Pallor", "Petechiae"],
    diagnostics: {
      notes: "Smear: Schistocytes (helmet cells). High LDH, Low Haptoglobin."
    },
    treatment: ["Treat underlying cause", "Plasma exchange (TTP)"],
    management: ["Hematology consult"],
    complications: ["Renal failure", "Stroke"],
    prognosis: "Serious, requires urgent care."
  },
  "Pituitary Adenoma": {
    overview: "Benign tumor of the pituitary gland.",
    etiologyPathophysiology: "Prolactinoma is most common. Mass effect compresses optic chiasm.",
    epidemiology: "Adults.",
    riskFactors: ["MEN1 syndrome"],
    clinicalPresentation: "Headache, visual changes, hormonal excess/deficiency.",
    symptoms: ["Headache", "Vision loss", "Galactorrhea"],
    examFindings: ["Bitemporal hemianopsia (tunnel vision)"],
    diagnostics: {
      notes: "MRI Brain. Hormone levels."
    },
    treatment: ["Dopamine agonists (Cabergoline) for prolactinoma", "Transsphenoidal surgery"],
    management: ["Endocrinology follow-up"],
    complications: ["Hypopituitarism", "Blindness"],
    prognosis: "Good."
  },
  "Typhoid Fever": {
    overview: "Systemic bacterial infection caused by Salmonella Typhi.",
    etiologyPathophysiology: "Fecal-oral transmission.",
    epidemiology: "Developing countries.",
    riskFactors: ["Travel", "Poor sanitation"],
    clinicalPresentation: "Fever, abdominal pain, 'pea soup' diarrhea.",
    symptoms: ["Fever", "Abdominal pain", "Diarrhea/Constipation"],
    examFindings: ["Rose spots (trunk)", "Bradycardia relative to fever (Faget sign)", "Hepatosplenomegaly"],
    diagnostics: {
      notes: "Blood culture."
    },
    treatment: ["Fluoroquinolones or Ceftriaxone"],
    management: ["Hydration"],
    complications: ["Intestinal perforation"],
    prognosis: "Good with antibiotics."
  },
  "UTI (Urease Producers)": {
    overview: "Urinary tract infection with urease-producing bacteria (Proteus, Klebsiella).",
    etiologyPathophysiology: "Urease splits urea into ammonia, raising urine pH, leading to struvite stones.",
    epidemiology: "Recurrent UTIs.",
    riskFactors: ["Catheters", "Recurrent UTI"],
    clinicalPresentation: "Dysuria, flank pain.",
    symptoms: ["Dysuria", "Frequency"],
    examFindings: ["CVA tenderness"],
    diagnostics: {
      notes: "UA: High pH (>7). Culture: Proteus. Imaging: Staghorn calculus."
    },
    treatment: ["Antibiotics", "Stone removal"],
    management: ["Prevention"],
    complications: ["Struvite (Staghorn) stones", "Urosepsis"],
    prognosis: "Good."
  },
  "Ureteral Stone": {
    overview: "Kidney stone lodged in the ureter.",
    etiologyPathophysiology: "Calcium oxalate most common.",
    epidemiology: "Common.",
    riskFactors: ["Dehydration", "Diet"],
    clinicalPresentation: "Sudden severe colicky flank pain radiating to groin.",
    symptoms: ["Severe pain", "Nausea", "Hematuria"],
    examFindings: ["CVA tenderness", "Patient moving constantly (unable to find comfortable position)"],
    diagnostics: {
      notes: "CT Abdomen/Pelvis (Non-contrast) is gold standard."
    },
    treatment: ["Analgesia", "Fluids", "Tamsulosin", "Lithotripsy/Ureteroscopy if large"],
    management: ["Hydration"],
    complications: ["Hydronephrosis", "Infection"],
    prognosis: "Most pass spontaneously if <5mm."
  },
  "Post-Streptococcal Glomerulonephritis": {
    overview: "Nephritic syndrome following Group A Strep infection.",
    etiologyPathophysiology: "Immune complex deposition in glomeruli.",
    epidemiology: "Children, 2-4 weeks after strep throat or impetigo.",
    riskFactors: ["Recent strep infection"],
    clinicalPresentation: "Cola-colored urine, edema, hypertension.",
    symptoms: ["Dark urine", "Swelling"],
    examFindings: ["Edema (periorbital)", "Hypertension"],
    diagnostics: {
      notes: "ASO titer positive. Low C3. UA: RBC casts."
    },
    treatment: ["Supportive", "Diuretics", "BP control"],
    management: ["Monitor renal function"],
    complications: ["Renal failure (rarely chronic)"],
    prognosis: "Excellent in children."
  },
  "Mania": {
    overview: "State of abnormally elevated arousal, affect, and energy level.",
    etiologyPathophysiology: "Bipolar I Disorder.",
    epidemiology: "Young adults.",
    riskFactors: ["Family history"],
    clinicalPresentation: "DIG FAST: Distractibility, Indiscretion, Grandiosity, Flight of ideas, Activity increase, Sleep deficit, Talkativeness.",
    symptoms: ["Euphoria", "Irritability", "Less need for sleep"],
    examFindings: ["Pressured speech", "Psychomotor agitation"],
    diagnostics: {
      notes: "Clinical criteria (symptoms > 1 week)."
    },
    treatment: ["Mood stabilizers (Lithium, Valproate)", "Antipsychotics"],
    management: ["Psychiatry referral"],
    complications: ["Suicide", "Risky behavior"],
    prognosis: "Chronic condition."
  },
  "Catatonia": {
    overview: "Neuropsychiatric syndrome characterized by abnormal movements and behaviors.",
    etiologyPathophysiology: "Associated with Schizophrenia, Bipolar, or medical conditions.",
    epidemiology: "Psychiatric inpatients.",
    riskFactors: ["Psychiatric history"],
    clinicalPresentation: "Immobility, mutism, stupor.",
    symptoms: ["Not moving", "Not speaking"],
    examFindings: ["Waxy flexibility", "Echolalia", "Echopraxia", "Negativism"],
    diagnostics: {
      notes: "Benzodiazepine challenge test."
    },
    treatment: ["Benzodiazepines (Lorazepam)", "ECT"],
    management: ["Treat underlying cause"],
    complications: ["DVT", "Malnutrition"],
    prognosis: "Responds well to treatment."
  },
  "Herpes Simplex Keratitis": {
    overview: "Viral infection of the cornea.",
    etiologyPathophysiology: "HSV-1 reactivation.",
    epidemiology: "Common cause of corneal blindness.",
    riskFactors: ["History of cold sores"],
    clinicalPresentation: "Eye pain, redness, photophobia.",
    symptoms: ["Pain", "Redness", "Tearing"],
    examFindings: ["Dendritic ulcer (branching) on fluorescein stain"],
    diagnostics: {
      notes: "Fluorescein staining."
    },
    treatment: ["Topical/Oral antivirals (Trifluridine, Acyclovir)", "NEVER use steroids (worsens it)"],
    management: ["Ophthalmology referral"],
    complications: ["Scarring", "Blindness"],
    prognosis: "Recurrent."
  },
  "Anterior Uveitis": {
    overview: "Inflammation of the iris and ciliary body (Iritis).",
    etiologyPathophysiology: "Autoimmune (HLA-B27), Trauma, Infection.",
    epidemiology: "Young adults.",
    riskFactors: ["Ankylosing Spondylitis", "IBD", "Reiter's"],
    clinicalPresentation: "Pain, redness, photophobia.",
    symptoms: ["Deep eye pain", "Photophobia"],
    examFindings: ["Ciliary flush (redness around limbus)", "Constricted pupil", "Cells and flare in anterior chamber"],
    diagnostics: {
      notes: "Slit lamp exam."
    },
    treatment: ["Topical steroids", "Cycloplegics"],
    management: ["Ophthalmology referral"],
    complications: ["Glaucoma", "Cataracts"],
    prognosis: "Good with treatment."
  },
  "Allergic Conjunctivitis": {
    overview: "Inflammation of the conjunctiva due to allergens.",
    etiologyPathophysiology: "IgE mediated.",
    epidemiology: "Common.",
    riskFactors: ["Atopy"],
    clinicalPresentation: "Itchy, watery eyes. Bilateral.",
    symptoms: ["Itching", "Tearing"],
    examFindings: ["Cobblestoning of tarsal conjunctiva", "Chemosis"],
    diagnostics: {
      notes: "Clinical."
    },
    treatment: ["Antihistamines (Olopatadine)", "Mast cell stabilizers"],
    management: ["Avoid allergens"],
    complications: ["None"],
    prognosis: "Excellent."
  },
  "Acute Otitis Media": {
    overview: "Infection of the middle ear.",
    etiologyPathophysiology: "Eustachian tube dysfunction. Strep pneumo, H. flu, Moraxella.",
    epidemiology: "Children.",
    riskFactors: ["Daycare", "Smoke exposure"],
    clinicalPresentation: "Ear pain, fever.",
    symptoms: ["Otalgia", "Fever", "Tugging ear"],
    examFindings: ["Bulging TM", "Erythema", "Loss of light reflex", "Decreased mobility"],
    diagnostics: {
      notes: "Pneumatic otoscopy."
    },
    treatment: ["Amoxicillin", "Observation in select cases"],
    management: ["Pain control"],
    complications: ["Mastoiditis", "Perforation"],
    prognosis: "Excellent."
  },
  "Cholesteatoma": {
    overview: "Destructive growth of keratinizing squamous epithelium in the middle ear.",
    etiologyPathophysiology: "Chronic negative pressure pulls TM inward.",
    epidemiology: "Chronic ear disease.",
    riskFactors: ["Chronic Otitis Media"],
    clinicalPresentation: "Painless otorrhea, hearing loss.",
    symptoms: ["Drainage", "Hearing loss"],
    examFindings: ["Pearly white mass behind TM", "Retraction pocket"],
    diagnostics: {
      notes: "CT Temporal bone."
    },
    treatment: ["Surgery"],
    management: ["ENT referral"],
    complications: ["Bone erosion", "Hearing loss"],
    prognosis: "Recurrence common."
  },
  "Hydatidiform Mole": {
    overview: "Gestational Trophoblastic Disease (Molar Pregnancy).",
    etiologyPathophysiology: "Abnormal fertilization. Complete (46XX, no fetal tissue) or Partial (69XXY, some fetal tissue).",
    epidemiology: "Extremes of age.",
    riskFactors: ["Age <20 or >35", "Asian ethnicity"],
    clinicalPresentation: "Vaginal bleeding, size > dates, hyperemesis.",
    symptoms: ["Bleeding", "Nausea"],
    examFindings: ["Uterus larger than expected", "Grape-like vesicles passed"],
    diagnostics: {
      notes: "Ultrasound: 'Snowstorm' or 'Cluster of grapes' appearance. Extremely high beta-hCG."
    },
    treatment: ["D&C (Suction Curettage)", "Monitor hCG to zero"],
    management: ["Contraception for 1 year"],
    complications: ["Choriocarcinoma"],
    prognosis: "Good with monitoring."
  },
  "Anembryonic Pregnancy": {
    overview: "Blighted ovum. Pregnancy where embryo fails to develop.",
    etiologyPathophysiology: "Chromosomal abnormalities.",
    epidemiology: "Common cause of miscarriage.",
    riskFactors: ["Age"],
    clinicalPresentation: "Signs of pregnancy then bleeding.",
    symptoms: ["Bleeding"],
    examFindings: ["Closed os"],
    diagnostics: {
      notes: "Ultrasound: Large gestational sac (>25mm) with no yolk sac or embryo."
    },
    treatment: ["Expectant", "Misoprostol", "D&C"],
    management: ["Support"],
    complications: ["Bleeding"],
    prognosis: "Good for future fertility."
  }
};

async function run() {
  console.log(`🚀 Seeding content for ${Object.keys(GENERATED_CONTENT).length} conditions...`);
  
  let existingContent: any = {};
  if (fs.existsSync(OUTPUT_FILE)) {
    existingContent = JSON.parse(fs.readFileSync(OUTPUT_FILE, "utf8"));
  }

  let successCount = 0;

  for (const item of CONDITION_REGISTRY_ADDITIONAL) {
    const id = buildConditionId(item.system, item.subcategory, item.condition);
    
    // Check if we have generated content for this condition
    // We match by exact name in the GENERATED_CONTENT map
    const content = GENERATED_CONTENT[item.condition];

    if (!content) {
      console.log(`⚠️  No generated content found for: ${item.condition}`);
      continue;
    }

    if (existingContent[id]) {
      console.log(`⏭️  Skipping ${item.condition} (already exists)`);
      // Optional: Overwrite if we want to force update
      // existingContent[id] = content;
      continue;
    }

    console.log(`Writing content for: ${item.condition}...`);
    existingContent[id] = content;
    successCount++;
  }

  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(existingContent, null, 2));
  console.log(`\n✅ Seeding complete! Added ${successCount} new conditions.`);
}

run().catch(console.error);
