/**
 * Contextual Retrieval Preprocessing
 *
 * Prepends context to each content chunk before embedding, improving
 * retrieval accuracy by ~35% (Anthropic benchmark).
 *
 * How it works:
 * 1. For each content chunk, use a fast LLM to generate a 1-2 sentence
 *    context prefix explaining what the chunk is about and where it fits.
 * 2. Prepend the context to the chunk text.
 * 3. Re-embed the contextualized text.
 * 4. Store both the original and contextualized text.
 *
 * This is a one-time batch process per content item.
 *
 * @module lib/services/search/contextualRetrieval
 */

// ─── Types ─────────────────────────────────────────────────────────────────

export interface ContentChunk {
  id: string;
  text: string;
  /** Source document title or condition name */
  sourceTitle: string;
  /** Section within the source (e.g., "Treatment", "Pathophysiology") */
  section?: string;
  /** Parent document/condition metadata */
  metadata?: Record<string, unknown>;
}

export interface ContextualizedChunk extends ContentChunk {
  /** Context prefix generated by LLM */
  contextPrefix: string;
  /** Full text with context prepended */
  contextualizedText: string;
}

export interface ContextualizationOptions {
  /** Max concurrent LLM calls. Default: 5 */
  concurrency?: number;
  /** Callback for progress tracking */
  onProgress?: (completed: number, total: number) => void;
}

// ─── Context Generation ────────────────────────────────────────────────────

/**
 * Build the prompt for generating a context prefix for a chunk.
 */
export function buildContextPrompt(chunk: ContentChunk, documentSummary?: string): string {
  const docContext = documentSummary
    ? `Document: ${documentSummary}\n`
    : chunk.sourceTitle
      ? `Source: ${chunk.sourceTitle}\n`
      : '';

  const sectionContext = chunk.section
    ? `Section: ${chunk.section}\n`
    : '';

  return `${docContext}${sectionContext}
Here is a chunk from the document:

<chunk>
${chunk.text.slice(0, 2000)}
</chunk>

Write a SHORT context (1-2 sentences max) explaining what this chunk is about and where it fits in the source document. The context should help a search engine understand what information this chunk contains. Do NOT repeat the chunk content — just provide the framing context.

Context:`;
}

/**
 * Generate context prefix for a single chunk using any text generation function.
 * The caller provides the LLM call function (supports both Vercel AI SDK and LangChain).
 */
export async function contextualizeChunk(
  chunk: ContentChunk,
  generateFn: (prompt: string) => Promise<string>,
  documentSummary?: string
): Promise<ContextualizedChunk> {
  const prompt = buildContextPrompt(chunk, documentSummary);
  const contextPrefix = await generateFn(prompt);

  const trimmedContext = contextPrefix.trim().replace(/^Context:\s*/i, '');

  return {
    ...chunk,
    contextPrefix: trimmedContext,
    contextualizedText: `${trimmedContext}\n\n${chunk.text}`,
  };
}

/**
 * Batch contextualize multiple chunks with concurrency control.
 *
 * @example
 * ```ts
 * import { aiGenerateText } from '@/lib/ai-sdk';
 *
 * const contextualized = await batchContextualize(
 *   chunks,
 *   async (prompt) => {
 *     const result = await aiGenerateText(env, {
 *       model: 'gemini-2.0-flash',
 *       prompt,
 *       temperature: 0.3,
 *       maxTokens: 150,
 *     });
 *     return result.text;
 *   },
 *   { concurrency: 10, onProgress: (done, total) => console.log(`${done}/${total}`) }
 * );
 * ```
 */
export async function batchContextualize(
  chunks: ContentChunk[],
  generateFn: (prompt: string) => Promise<string>,
  options: ContextualizationOptions = {}
): Promise<ContextualizedChunk[]> {
  const { concurrency = 5, onProgress } = options;
  const results: ContextualizedChunk[] = [];
  let completed = 0;

  // Process in batches
  for (let i = 0; i < chunks.length; i += concurrency) {
    const batch = chunks.slice(i, i + concurrency);
    const batchResults = await Promise.allSettled(
      batch.map((chunk) => contextualizeChunk(chunk, generateFn))
    );

    for (let j = 0; j < batchResults.length; j++) {
      const result = batchResults[j];
      if (result.status === 'fulfilled') {
        results.push(result.value);
      } else {
        // On failure, use the chunk as-is with empty context
        console.warn(
          `[contextualRetrieval] Failed to contextualize chunk ${batch[j].id}:`,
          result.reason
        );
        results.push({
          ...batch[j],
          contextPrefix: '',
          contextualizedText: batch[j].text,
        });
      }

      completed++;
      onProgress?.(completed, chunks.length);
    }

    // Rate limit between batches
    if (i + concurrency < chunks.length) {
      await new Promise((r) => setTimeout(r, 200));
    }
  }

  return results;
}

// ─── Chunk Splitting ───────────────────────────────────────────────────────

/**
 * Split text into parent-child chunks for two-tier retrieval.
 *
 * Parent chunks: 800-1500 tokens (returned to LLM for context)
 * Child chunks: 200-400 tokens (used for retrieval matching)
 */
export function splitIntoParentChild(
  text: string,
  options: {
    parentMaxChars?: number;
    childMaxChars?: number;
    overlap?: number;
  } = {}
): Array<{ parent: string; children: string[] }> {
  const {
    parentMaxChars = 4000,  // ~1000 tokens
    childMaxChars = 1200,   // ~300 tokens
    overlap = 100,
  } = options;

  const paragraphs = text.split(/\n\n+/).filter((p) => p.trim().length > 0);

  // Build parent chunks from paragraphs
  const parents: Array<{ text: string; children: string[] }> = [];
  let currentParent = '';

  for (const para of paragraphs) {
    if (currentParent.length + para.length > parentMaxChars && currentParent.length > 0) {
      parents.push({ text: currentParent.trim(), children: [] });
      // Overlap: keep last sentence of current parent
      const lastSentence = currentParent.match(/[^.!?]*[.!?]\s*$/)?.[0] ?? '';
      currentParent = lastSentence.length < overlap ? lastSentence + para : para;
    } else {
      currentParent += (currentParent ? '\n\n' : '') + para;
    }
  }
  if (currentParent.trim()) {
    parents.push({ text: currentParent.trim(), children: [] });
  }

  // Split each parent into child chunks
  for (const parent of parents) {
    const sentences = parent.text.match(/[^.!?]+[.!?]+/g) ?? [parent.text];
    let currentChild = '';

    for (const sentence of sentences) {
      if (currentChild.length + sentence.length > childMaxChars && currentChild.length > 0) {
        parent.children.push(currentChild.trim());
        currentChild = sentence;
      } else {
        currentChild += sentence;
      }
    }
    if (currentChild.trim()) {
      parent.children.push(currentChild.trim());
    }
  }

  return parents.map((p) => ({ parent: p.text, children: p.children }));
}
