import type { AnatomyModel } from '@/types/anatomy-model';

const accessedDate = '2026-05-16';
const timestamp = '2026-05-16T00:00:00.000Z';

export const NIH_HUMAN_HEART_MODEL: AnatomyModel = {
  id: 'heart-basic',
  name: 'Human Heart - NIH 3D Atlas Model',
  description:
    'Public-domain GLB model of the human heart from NIH 3D for educational spatial anatomy review.',
  system: 'cardiovascular',
  structures: [
    'left atrium',
    'right atrium',
    'left ventricle',
    'right ventricle',
    'aorta',
    'pulmonary artery',
    'pulmonary veins',
    'vena cava',
  ],
  modelUrl: '/models/nih/human-heart-3dpx-022787.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/human-heart-3dpx-022787.png',
  assetSizeBytes: 3986136,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-022787',
    title: 'Human Heart 3d Model',
    author: 'Sourav Pan',
    institution: 'National Institutes of Health',
    license: 'Public Domain',
    url: 'https://3d.nih.gov/entries/3DPX-022787?version=1.01',
    dateAccessed: accessedDate,
    citationText:
      'Sourav Pan. Human Heart 3d Model. NIH 3D. https://3d.nih.gov/entries/3DPX-022787?version=1.01. Accessed 2026-05-16.',
  },
  clinicalRelevance: [
    'Orient chamber and great-vessel relationships before cardiovascular questions.',
    'Use as a spatial reference for valves, flow direction, and gross anatomy relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['heart-failure', 'myocardial-infarction', 'valvular-heart-disease'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'left atrium',
    'right atrium',
    'left ventricle',
    'right ventricle',
    'aorta',
    'pulmonary artery',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_VISIBLE_HUMAN_HEART_LUNGS_MODEL: AnatomyModel = {
  id: 'visible-human-heart-lungs',
  name: 'Visible Human Heart Vessels and Lungs - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of the lungs, trachea, and heart vessels from NIH 3D for educational cardiopulmonary spatial review.',
  system: 'respiratory',
  structures: [
    'right lung',
    'left lung',
    'trachea',
    'main bronchi',
    'heart vessels',
    'pulmonary vessels',
  ],
  modelUrl: '/models/nih/visible-human-heart-lungs-3dpx-023212.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/visible-human-heart-lungs-3dpx-023212.png',
  assetSizeBytes: 2590240,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-023212',
    title: 'Visible Human Heart Vessels and Lungs',
    author: 'kbrowne',
    institution: 'National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-023212',
    dateAccessed: accessedDate,
    citationText:
      'kbrowne. Visible Human Heart Vessels and Lungs. NIH 3D. https://3d.nih.gov/entries/3DPX-023212. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review gross cardiopulmonary positioning before respiratory and cardiovascular questions.',
    'Use as a spatial reference for trachea, lungs, and heart-vessel relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['asthma', 'copd', 'pulmonary-embolism', 'heart-failure'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'right lung',
    'left lung',
    'trachea',
    'main bronchi',
    'heart vessels',
    'pulmonary vessels',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_LEFT_KIDNEY_MODEL: AnatomyModel = {
  id: 'hra-left-kidney-male',
  name: 'Human Reference Atlas Left Kidney - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a left kidney reference organ from NIH 3D and the Human Reference Atlas for educational urinary-system spatial review.',
  system: 'urinary',
  structures: [
    'left kidney',
    'renal cortex',
    'renal medulla',
    'renal pelvis',
    'renal vessels',
    'proximal ureter',
  ],
  modelUrl: '/models/nih/hra-left-kidney-male-3dpx-021001.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-left-kidney-male-3dpx-021001.png',
  assetSizeBytes: 1536532,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-021001',
    title: '3D Reference Organ for Kidney, Male, Left v1.2',
    author: 'Kristen Browne; Heidi Schlehlein',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-021001',
    dateAccessed: accessedDate,
    citationText:
      'Kristen Browne; Heidi Schlehlein. 3D Reference Organ for Kidney, Male, Left v1.2. NIH 3D. https://3d.nih.gov/entries/3DPX-021001. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review kidney orientation before urinary-system questions and renal anatomy recall.',
    'Use as a spatial reference for cortex, medulla, renal pelvis, vessels, and proximal ureter relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['acute-kidney-injury', 'nephrolithiasis', 'pyelonephritis'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'left kidney',
    'renal cortex',
    'renal medulla',
    'renal pelvis',
    'renal vessels',
    'proximal ureter',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_LIVER_MODEL: AnatomyModel = {
  id: 'hra-liver-female',
  name: 'Human Reference Atlas Liver - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a liver reference organ from NIH 3D and the Human Reference Atlas for educational digestive-system spatial review.',
  system: 'digestive',
  structures: [
    'liver',
    'right hepatic lobe',
    'left hepatic lobe',
    'porta hepatis',
    'hepatic vessels',
    'biliary anatomy',
  ],
  modelUrl: '/models/nih/hra-liver-female-3dpx-020973.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-liver-female-3dpx-020973.png',
  assetSizeBytes: 1738032,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-020973',
    title: '3D Reference Organ for Liver, Female v1.1',
    author: 'Kristen Browne',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-020973',
    dateAccessed: accessedDate,
    citationText:
      'Kristen Browne. 3D Reference Organ for Liver, Female v1.1. NIH 3D. https://3d.nih.gov/entries/3DPX-020973. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review liver orientation before hepatobiliary and abdominal anatomy questions.',
    'Use as a spatial reference for hepatic lobes, porta hepatis, vessels, and biliary relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['hepatitis', 'cirrhosis', 'cholelithiasis'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'liver',
    'right hepatic lobe',
    'left hepatic lobe',
    'porta hepatis',
    'hepatic vessels',
    'biliary anatomy',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_MAIN_BRONCHUS_MODEL: AnatomyModel = {
  id: 'hra-main-bronchus-female',
  name: 'Human Reference Atlas Main Bronchus - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of the main bronchus reference organ from NIH 3D and the Human Reference Atlas for educational airway spatial review.',
  system: 'respiratory',
  structures: [
    'trachea',
    'carina',
    'right main bronchus',
    'left main bronchus',
    'main bronchi',
    'proximal airway',
  ],
  modelUrl: '/models/nih/hra-main-bronchus-female-3dpx-020976.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-main-bronchus-female-3dpx-020976.png',
  assetSizeBytes: 2858776,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-020976',
    title: '3D Reference Organ for Main Bronchus, Female v1.0',
    author: 'Kristen Browne; Heidi Schlehlein',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-020976',
    dateAccessed: accessedDate,
    citationText:
      'Kristen Browne; Heidi Schlehlein. 3D Reference Organ for Main Bronchus, Female v1.0. NIH 3D. https://3d.nih.gov/entries/3DPX-020976. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review airway branching before respiratory-system questions and image-pattern drills.',
    'Use as a spatial reference for trachea, carina, and main bronchus relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['asthma', 'copd', 'foreign-body-aspiration'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'trachea',
    'carina',
    'right main bronchus',
    'left main bronchus',
    'main bronchi',
    'proximal airway',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_PANCREAS_MODEL: AnatomyModel = {
  id: 'hra-pancreas-female',
  name: 'Human Reference Atlas Pancreas - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a pancreas reference organ from NIH 3D and the Human Reference Atlas for educational endocrine and abdominal spatial review.',
  system: 'endocrine',
  structures: [
    'pancreas',
    'pancreatic head',
    'pancreatic neck',
    'pancreatic body',
    'pancreatic tail',
    'pancreatic duct region',
  ],
  modelUrl: '/models/nih/hra-pancreas-female-3dpx-020983.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-pancreas-female-3dpx-020983.png',
  assetSizeBytes: 714668,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-020983',
    title: '3D Reference Organ for Pancreas, Female v1.3',
    author: 'Human Reference Atlas',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-020983',
    dateAccessed: accessedDate,
    citationText:
      'Human Reference Atlas. 3D Reference Organ for Pancreas, Female v1.3. NIH 3D. https://3d.nih.gov/entries/3DPX-020983. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review pancreatic orientation before endocrine, abdominal, and hepatobiliary study blocks.',
    'Use as a spatial reference for head, neck, body, tail, and duct-region relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['diabetes-mellitus', 'pancreatitis', 'pancreatic-cancer'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'pancreas',
    'pancreatic head',
    'pancreatic neck',
    'pancreatic body',
    'pancreatic tail',
    'pancreatic duct region',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_SPLEEN_MODEL: AnatomyModel = {
  id: 'hra-spleen-female',
  name: 'Human Reference Atlas Spleen - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a spleen reference organ from NIH 3D and the Human Reference Atlas for educational lymphatic and hematology spatial review.',
  system: 'lymphatic',
  structures: [
    'spleen',
    'splenic hilum',
    'superior border',
    'inferior border',
    'visceral surface',
    'splenic capsule',
  ],
  modelUrl: '/models/nih/hra-spleen-female-3dpx-020989.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-spleen-female-3dpx-020989.png',
  assetSizeBytes: 276712,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-020989',
    title: '3D Reference Organ for Spleen, Female v1.2',
    author: 'Human Reference Atlas',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-020989',
    dateAccessed: accessedDate,
    citationText:
      'Human Reference Atlas. 3D Reference Organ for Spleen, Female v1.2. NIH 3D. https://3d.nih.gov/entries/3DPX-020989. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review spleen orientation before hematology, infectious disease, and abdominal anatomy questions.',
    'Use as a spatial reference for splenic surface, hilum, and left-upper-quadrant relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['splenomegaly', 'mononucleosis', 'hematologic-disorders'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'spleen',
    'splenic hilum',
    'superior border',
    'inferior border',
    'visceral surface',
    'splenic capsule',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_PROSTATE_MODEL: AnatomyModel = {
  id: 'hra-prostate-male',
  name: 'Human Reference Atlas Prostate - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a prostate reference organ from NIH 3D and the Human Reference Atlas for educational reproductive and urinary spatial review.',
  system: 'reproductive',
  structures: [
    'prostate',
    'prostatic base',
    'prostatic apex',
    'peripheral region',
    'central region',
    'urethral relationship',
  ],
  modelUrl: '/models/nih/hra-prostate-male-3dpx-021015.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-prostate-male-3dpx-021015.png',
  assetSizeBytes: 4086328,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-021015',
    title: '3D Reference Organ for Prostate, Male v1.1',
    author: 'Human Reference Atlas',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-021015',
    dateAccessed: accessedDate,
    citationText:
      'Human Reference Atlas. 3D Reference Organ for Prostate, Male v1.1. NIH 3D. https://3d.nih.gov/entries/3DPX-021015. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review prostate orientation before reproductive, urinary, and screening-topic study blocks.',
    'Use as a spatial reference for base, apex, regional anatomy, and urethral relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['benign-prostatic-hyperplasia', 'prostatitis', 'prostate-cancer'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'prostate',
    'prostatic base',
    'prostatic apex',
    'peripheral region',
    'central region',
    'urethral relationship',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_HRA_SPINAL_CORD_MODEL: AnatomyModel = {
  id: 'hra-spinal-cord-female',
  name: 'Human Reference Atlas Spinal Cord - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a spinal cord reference organ from NIH 3D and the Human Reference Atlas for educational nervous-system spatial review.',
  system: 'nervous',
  structures: [
    'spinal cord',
    'cervical region',
    'thoracic region',
    'lumbar region',
    'sacral region',
    'central canal region',
  ],
  modelUrl: '/models/nih/hra-spinal-cord-female-3dpx-020988.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/hra-spinal-cord-female-3dpx-020988.png',
  assetSizeBytes: 7656588,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-020988',
    title: '3D Reference Organ for Spinal Cord, Female v1.0',
    author: 'Human Reference Atlas',
    institution: 'Human Reference Atlas / National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-020988',
    dateAccessed: accessedDate,
    citationText:
      'Human Reference Atlas. 3D Reference Organ for Spinal Cord, Female v1.0. NIH 3D. https://3d.nih.gov/entries/3DPX-020988. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review spinal cord orientation before neurologic localization and spinal anatomy questions.',
    'Use as a spatial reference for cervical, thoracic, lumbar, and sacral relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['spinal-cord-injury', 'multiple-sclerosis', 'cauda-equina-syndrome'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'spinal cord',
    'cervical region',
    'thoracic region',
    'lumbar region',
    'sacral region',
    'central canal region',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_RIGHT_FEMUR_MODEL: AnatomyModel = {
  id: 'right-femur',
  name: 'Right Femur - NIH 3D Atlas Model',
  description:
    'CC-BY GLB model of a right human femur from NIH 3D for educational musculoskeletal spatial review.',
  system: 'musculoskeletal',
  structures: [
    'right femur',
    'femoral head',
    'femoral neck',
    'greater trochanter',
    'femoral shaft',
    'distal femur',
  ],
  modelUrl: '/models/nih/right-femur-3dpx-016822.glb',
  format: 'glb',
  thumbnailUrl: '/thumbnails/nih/right-femur-3dpx-016822.png',
  assetSizeBytes: 5136244,
  citation: {
    source: 'NIH 3D Print Exchange',
    modelId: '3DPX-016822',
    title: 'Femur Right_Human Skeleton',
    author: 'My Segmenter',
    institution: 'National Institutes of Health',
    license: 'CC-BY 4.0',
    url: 'https://3d.nih.gov/entries/3DPX-016822',
    dateAccessed: accessedDate,
    citationText:
      'My Segmenter. Femur Right_Human Skeleton. NIH 3D. https://3d.nih.gov/entries/3DPX-016822. Accessed 2026-05-16. Licensed under CC-BY 4.0.',
  },
  clinicalRelevance: [
    'Review femur orientation before musculoskeletal, trauma, and orthopedics study blocks.',
    'Use as a spatial reference for hip, shaft, trochanter, and distal femur relationships.',
    'Supports PANCE study review only; not for patient diagnosis or treatment planning.',
  ],
  relatedConditions: ['hip-fracture', 'osteoporosis', 'osteoarthritis'],
  annotations: [],
  scale: 1,
  defaultRotation: [0, 0, 0],
  highlightableStructures: [
    'right femur',
    'femoral head',
    'femoral neck',
    'greater trochanter',
    'femoral shaft',
    'distal femur',
  ],
  createdAt: timestamp,
  updatedAt: timestamp,
};

export const NIH_ANATOMY_MODELS: AnatomyModel[] = [
  NIH_HUMAN_HEART_MODEL,
  NIH_VISIBLE_HUMAN_HEART_LUNGS_MODEL,
  NIH_HRA_LEFT_KIDNEY_MODEL,
  NIH_HRA_LIVER_MODEL,
  NIH_HRA_MAIN_BRONCHUS_MODEL,
  NIH_HRA_PANCREAS_MODEL,
  NIH_HRA_SPLEEN_MODEL,
  NIH_HRA_PROSTATE_MODEL,
  NIH_HRA_SPINAL_CORD_MODEL,
  NIH_RIGHT_FEMUR_MODEL,
];
